greenpeace/planet4-plugin-gutenberg-blocks

planet4-gutenberg-blocks.php

- Filter allowed block types per post type

PLANET-3905 Register/Hide blocks per post type

---

classes/class-loader.php

Ref: https://jira.greenpeace.org/browse/PLANET-3975

PLANET-3975: Ensure frontend facing assets are loaded for all Gutenberg blocks

---

classes/blocks/class-articles.php

[JIRA 4072](https://jira.greenpeace.org/browse/PLANET-4072)

PLANET-4072 Fix articles block on Post page show all posts

---

planet4-gutenberg-blocks.php

Ref: https://jira.greenpeace.org/browse/PLANET-4148

PLANET-4148: Disable some native Gutenberg blocks 

---

planet4-gutenberg-blocks.php

- added Take-action-boxout block to whitelist for posts

PLANET-4214 Allow take action boxout in posts

---

templates/blocks/articles.twig
templates/blocks/campaign_thumbnail.twig
templates/blocks/content_four_column.twig
templates/blocks/cookies.twig
templates/blocks/counter.twig
templates/blocks/gallery.twig
templates/blocks/old_covers.twig
templates/blocks/timeline.twig

This was fixed greenpeace/planet4-plugin-blocks@a39d52fc18ce94d15fb210e435ee5e893bc452d5 but we never transfer it to this repo.

Convert page header descriptions elements to divs

---

templates/blocks/columns.twig

Ref: https://jira.greenpeace.org/browse/PLANET-4209

PLANET-4209: Column Block: Vertical Spacing of Description Field text	

---

classes/command/class-shortcode-to-gutenberg.php

Add suppress_filters arg to query for all posts (wpml enabled sites)

Fix convert to gutenberg for wpml enabled sites

---

classes/command/class-shortcode-to-gutenberg.php

Add conversion logging per post so ci does not timeout because of no ouput

Add conversion logging per post

---

planet4-gutenberg-blocks.php

- added take-action-boxout block to Pages whitelist
- added spacer block to whitelist

PLANET-4312  Add missing blocks to whitelist in pages and posts

---

classes/blocks/class-happypoint.php
public/js/happy_point.js
templates/blocks/happy_point.twig

Transfer happy_point js from old blocks
Remove hardcoded iframe in happy_point template

PLANET-4297 FIx happy point iframe

---

classes/class-loader.php
public/js/post_action.js

- Added missing JS file to force take action card to scroll with page

PLANET-4313 Take action boxout: not floating on posts

---

classes/blocks/class-counter.php
public/js/counter.js

- Added missing JS to append counter block inside en-form block

PLANET-4320 Counter block- progress bar style: counter not added to form

---

classes/command/class-shortcode-to-gutenberg.php

Print out the post id before it's converted

Move conversion log on top of for loop

---

classes/class-loader.php

Ref: https://jira.greenpeace.org/browse/PLANET-4208
It's ready, but needs greenpeace/planet4-styleguide#24 to be merged first.

PLANET-4208 - Set prefined color palette

---

classes/controller/menu/class-blocks-usage-controller.php

* get planet4 block types using get_all_registered instead of coupling to shortcake codes
* add some core block types

PLANET-4268 Also report on some core block types

---

assets/src/styles/campaigns/themes/_theme_climate.scss
assets/src/styles/campaigns/themes/_theme_oil.scss

Ref: https://jira.greenpeace.org/browse/PLANET-4466

PLANET-4466: CPP - Oil and Climate Emergency templates: Remove B&W filters from

---

assets/src/blocks/Gallery/Gallery.js
assets/src/blocks/Gallery/GalleryBlock.js
assets/src/styles/blocks/ColumnsEditor.scss
assets/src/styles/blocks/GalleryEditor.scss
classes/class-loader.php

[JIRA 4251](https://jira.greenpeace.org/browse/PLANET-4251)

PLANET-4251 Add option to remove single image from Gallery block

---

assets/src/styles/campaigns/themes/_theme_plastic.scss

Ref: https://jira.greenpeace.org/browse/PLANET-4505

PLANET-4505: CPP - Plastics - Mobile - CSS fixes

---

assets/src/styles/campaigns/block-overrides/_campaign_columns.scss

Ref: https://jira.greenpeace.org/browse/PLANET-4504

PLANET-4504: CPP - Columns block - Tasks style alignment to left on all templates

---

.githooks/prepare-commit-msg
bin/copy-git-hooks.sh
package.json

Ref: https://jira.greenpeace.org/browse/PLANET-4395

PLANET-4395: Recreate Git hooks Gulp task in NPM

---

classes/controller/menu/class-blocks-usage-controller.php

[JIRA 4527](https://jira.greenpeace.org/browse/PLANET-4527)
Block Usage API endpoint example: https://k8s.p4.greenpeace.org/sagardev/wp-json/plugin_blocks/v2/plugin_blocks_report/

PLANET-4527 Add API endpoint for Blocks Usage

---

public/js/social_media_cards.js
templates/blocks/social_media_cards.twig

Apparently requires CORS header to be set on the requested resource.

PLANET-4538 Remove download trick

---

assets/src/styles/campaigns/block-overrides/_campaign_columns.scss

This adds a rule for the Columns - Tasks CTA styles, not taken into account in the previous fixes.

PLANET-4399: CPP - Investigate primary and secondary button usage across blocks - Fix

---

assets/src/styles/campaigns/block-overrides/_campaign_columns.scss

This fixes #2 in the ticket.
Ref: https://jira.greenpeace.org/browse/PLANET-4589

PLANET-4589: CPP - Minor frontend issues introduced

---

templates/blocks/columns_tasks.twig

Adds a condition for columns_tasks in Campaign pages. 
Ref: https://jira.greenpeace.org/browse/PLANET-4399

PLANET-4399: CPP - Investigate primary and secondary button usage across blocks

---

planet4-gutenberg-blocks.php

[JIRA 4546](https://jira.greenpeace.org/browse/PLANET-4546)

PLANET-4546 Disable split two column block from CPP

---

assets/src/styles/blocks/Gallery_grid.scss

Ref: https://jira.greenpeace.org/browse/PLANET-4455

PLANET-4455: Gallery Block (Grid Style) : thumbnails get massively Zoomed in

---

assets/src/blocks/Spreadsheet/Spreadsheet.js
assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
assets/src/editorIndex.js
assets/src/styles/blocks/Spreadsheet.scss
assets/src/styles/campaigns/themes/_theme_oceans.scss
assets/src/styles/style.scss
classes/blocks/class-spreadsheet.php
classes/class-loader.php
planet4-gutenberg-blocks.php
public/js/spreadsheet.js
templates/blocks/spreadsheet.twig

This is based on https://github.com/alagregor/planet4-plugin-gutenberg-blocks/tree/e8f5065e3e8885ab851117ee5fc7671b8b782782
* Block that allows you to enter a spreadsheet URL and display the
contents in a table that can be sorted and filtered.

PLANET-4562 Add Spreadsheet block

---

assets/src/blocks/SocialMediaCards/SocialMediaCards.js
assets/src/blocks/SocialMediaCards/SocialMediaCardsBlock.js
classes/blocks/class-socialmediacards.php
public/js/social_media_cards.js
templates/blocks/social_media_cards.twig

* Use a single nested "cards" attribute instead of separate flat attributes.
* Remove the interface for focal points as they don't work yet. Use
plain img element instead.
* Use bootstrap cols to dramatically decrease editor height by placing
fields next to image.
* Use textarea instead for social media message.
* Add button to remove image.
* Use p4ge translation domain everywhere.
* Add some actual help to the help texts.
* Pass title and description to server side renderer.
* Remove gallery naming leftovers from copy.

Planet 4609

---

assets/src/styles/blocks/core-overrides/Image.scss

Ref: https://jira.greenpeace.org/browse/PLANET-4566

PLANET-4566: Posts: Image embed caption misaligned on mobile

---

public/js/submenu.js

this was in the previous blocks plugin but wasn't migrated.

PLANET-4481 Add script for back-top button

---

assets/src/styles/blocks/Spreadsheet.scss
assets/src/styles/campaigns/themes/_theme_oceans.scss
templates/blocks/spreadsheet.twig

* Remove unneeded button height
* Move background-color to oceans stylesheets
* Remove spacing around cell contents

PLANET-4560 Move rules to campaign style / fix spacing

---

planet4-gutenberg-blocks.php

[JIRA 4569](https://jira.greenpeace.org/browse/PLANET-4569)

PLANET-4569 Disable submenu block from CPP

---

assets/src/addButtonLinkPasteWarning.js
assets/src/editorIndex.js

I tried replacing the a tag with only its contents in the edited element,
however modifying the richtext element contents messes with the js
controlling it.

PLANET-4473 Show alert when pasting a link into button text

---

classes/rest/class-rest-api.php

This was added for wpml but not for others, now it is for both.

PLANET-4439 Order posts by post_date desc

---

assets/src/blocks/Carouselheader/FullWidthCarouselHeader.js

Ref: https://jira.greenpeace.org/browse/PLANET-4688

PLANET-4688: Carousel Header MENA: Double-check all possible interactions

---

assets/src/components/PostMeta/withPostMeta.js
assets/src/components/Sidebar/CampaignSidebar.js

* Use "theme" label instead of "campaign template"
* Add default values if meta is empty

PLANET-4603 Fixes after testing

---

public/js/load_more.js

Hotfix: Update lazy loaded images on "Load More" clicks.

---

assets/src/components/PostMeta/withPostMeta.js
assets/src/components/Sidebar/CampaignSidebar.js
assets/src/components/fromThemeOptions/fromThemeOptions.js
assets/src/connectCssVariables.js
classes/class-loader.php

* Add a way to specifiy the values of a field based on the current value
of another field in the json file.

PLANET-4735 Add dependencies on other fields in theme

---

assets/src/styles/campaigns/themes/_theme_antarctic.scss
assets/src/styles/campaigns/themes/_theme_arctic.scss
assets/src/styles/campaigns/themes/_theme_climate.scss
assets/src/styles/campaigns/themes/_theme_forest.scss
assets/src/styles/campaigns/themes/_theme_oceans.scss
assets/src/styles/campaigns/themes/_theme_oil.scss
assets/src/styles/campaigns/themes/_theme_plastic.scss

Ref: https://jira.greenpeace.org/browse/PLANET-4740
Styleguide PR: greenpeace/planet4-styleguide#37
Master Theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1009

PLANET-4740: CSS: Remove :not(#hidecookie) rule 

---

assets/src/styles/blocks/Columns.scss
assets/src/styles/campaigns/base/_mixins.scss
assets/src/styles/campaigns/block-overrides/_campaign_columns.scss
assets/src/styles/campaigns/themes/_theme_forest.scss
assets/src/styles/campaigns/themes/_theme_oil.scss

Ref: https://jira.greenpeace.org/browse/PLANET-4747

PLANET-4747: Campaigns CSS: Columns block CTA should follow main CTA style

---

assets/src/blocks/SubPages/SubPages.js
assets/src/blocks/SubPages/SubPagesBlock.js
assets/src/components/Sidebar/CampaignSidebar.js
assets/src/editorIndex.js
classes/blocks/class-subpages.php
classes/class-loader.php
planet4-gutenberg-blocks.php
templates/blocks/sub-pages.twig

* Add beta block for displaying links to all immediate child pages.
* Only show sidebar on top level campaign pages, else show link to
parent page.

PLANET-4712 Add block to display children of current page.

---

assets/src/styles/blocks/Spreadsheet.scss

Ref: https://jira.greenpeace.org/browse/PLANET-4767

PLANET-4767: Spreadsheet block: Adjust vertical spacing

---

assets/src/blocks/Carouselheader/FullWidthCarouselHeader.js
assets/src/blocks/Carouselheader/ZoomAndSlideCarouselHeader.js

Ref: https://jira.greenpeace.org/browse/PLANET-4842

PLANET-4842 Carousel: Make swipe scroll more responsive

---

assets/src/blocks/Articles/Articles.js
assets/src/blocks/Articles/ArticlesBlock.js
assets/src/blocks/Covers/Covers.js
assets/src/blocks/Covers/CoversBlock.js
assets/src/components/PostSelector/PostSelector.js
assets/src/components/PostTypeSelector/PostTypeSelector.js
assets/src/components/TagSelector/TagSelector.js
classes/class-loader.php

* Move more logic into Covers.js, instead of CoversBlock.js which should
only do the registering of the block.

PLANET-4806 Fix article selection in Covers.

---

assets/src/components/Sidebar/CampaignSidebar.js
assets/src/styles/blocks/Spreadsheet.scss
assets/src/styles/campaigns/themes/_theme_oceans.scss
public/js/spreadsheet.js
templates/blocks/spreadsheet.twig

Ref: https://jira.greenpeace.org/browse/PLANET-4561

PLANET-4561: Make sure P4 Spreadsheet embed (New Block) respects all Campaign Styles

---

assets/src/blocks/Gallery/Gallery.js
assets/src/blocks/Gallery/GalleryBlock.js
assets/src/styles/blocks/GalleryEditor.scss
assets/src/styles/editorOverrides.scss
assets/src/styles/editorStyle.scss
planet4-gutenberg-blocks.php

Ref: https://jira.greenpeace.org/browse/PLANET-4822

PLANET-4822: Gallery block: image selector not visible

---

assets/src/styles/campaigns/themes/_theme_antarctic.scss
assets/src/styles/campaigns/themes/_theme_arctic.scss
assets/src/styles/campaigns/themes/_theme_climate.scss
assets/src/styles/campaigns/themes/_theme_forest.scss
assets/src/styles/campaigns/themes/_theme_oceans.scss
assets/src/styles/campaigns/themes/_theme_oil.scss
assets/src/styles/campaigns/themes/_theme_plastic.scss

Ensuring the right rules and styles are applied.
Master theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1048
Styleguide PR: https://github.com/greenpeace/planet4-styleguide/pull/42
Ref: https://jira.greenpeace.org/browse/PLANET-4820

PLANET-4820: P4CG - Footer color should not be applied when "Main website navigation" is selected

---

classes/controller/menu/class-archive-import.php
classes/controller/menu/class-controller.php
planet4-gutenberg-blocks.php

This should probably be in master-theme instead, but started off here
and it takes a while to move this to master-theme as the it doesn't have
the same controllers. So pushing this one to have it on the server
already.

PLANET-4827 Add page to import archive files

---

assets/src/styles/blocks/Articles.scss
assets/src/styles/blocks/CarouselHeader.scss
assets/src/styles/blocks/CarouselHeader_full_width_classic.scss
assets/src/styles/blocks/Columns.scss
assets/src/styles/blocks/Covers/ContentCovers.scss
assets/src/styles/blocks/Gallery_carousel.scss
assets/src/styles/blocks/Happypoint.scss
assets/src/styles/blocks/SocialMediaCards.scss

Note: this branch is based on the PLANET-4919 branch.
UAT Passed.
Ref: https://jira.greenpeace.org/browse/PLANET-4887
Master theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1056
Styleguide PR: https://github.com/greenpeace/planet4-styleguide/pull/45

PLANET-4887: Text that is #000000 should be #1A1A1A

---

assets/src/components/PostMeta/withPostMeta.js
assets/src/components/Sidebar/CampaignSidebar.js
assets/src/components/fromThemeOptions/fromThemeOptions.js
assets/src/components/withDefaultLabel/withDefaultLabel.js

their values are not allowed anymore.

Find all fields that depend on a field and update them with defaults if

---

classes/controller/menu/class-blocks-usage-controller.php

[JIRA 5015](https://jira.greenpeace.org/browse/PLANET-5015)

PLANET-5015 Blocks report API - Fix carousel header block counts

---

assets/src/styles/campaigns/themes/_theme_oceans.scss
assets/src/styles/campaigns/themes/_theme_plastic.scss

See https://jira.greenpeace.org/browse/PLANET-5001

PLANET-5001 Limit link color to page template in order not to affect footer

---

assets/src/styles/blocks.scss
assets/src/styles/blocks/Covers/TakeActionCovers.scss
assets/src/styles/blocks/core-overrides/Spacer.scss

See https://jira.greenpeace.org/browse/PLANET-4653

PLANET-4653 - Remove Spacer override and fix Take Action Boxout positioning

---

classes/blocks/class-counter.php

[JIRA 4695 ](https://jira.greenpeace.org/browse/PLANET-4695)
Issue: 
- Handle a 404 error return by API response

PLANET-4695 Fix Sentry Issue: PLANET4-6D

---

assets/src/styles/blocks/Submenu.scss

See https://jira.greenpeace.org/browse/PLANET-5027

PLANET-5027 Add padding to Submenu ul

---

assets/src/blocks/Spreadsheet/Spreadsheet.js
assets/src/styles/blocks/Spreadsheet.scss

See Will's last comment on https://jira.greenpeace.org/browse/PLANET-5037:
```
Because of accessibility we are moving from warm red greys to cooler blue greys. I will add the colour changes here.
On all #1A1A1A becomes #020202
on Grey colour scheme
#F7F7F7 becomes #F5F7F8
#DCDCDC becomes #ECECEC
#666666 becomes #45494C
```

PLANET-5037 Update Spreadsheet grey colors for better accessibility

---

assets/src/styles/blocks/core-overrides/BlockSpacing.scss

See https://jira.greenpeace.org/browse/PLANET-5029

PLANET-5029 Fix inline images alignment

---

assets/src/blocks/Articles/Articles.js
assets/src/blocks/Columns/Columns.js
assets/src/blocks/Counter/Counter.js
assets/src/blocks/Media/Media.js
assets/src/blocks/Socialmedia/Socialmedia.js
assets/src/blocks/Splittwocolumns/Splittwocolumns.js
assets/src/blocks/Takeactionboxout/Takeactionboxout.js
assets/src/blocks/Timeline/Timeline.js
assets/src/components/URLInput/URLInput.js
assets/src/components/URLValidationMessage/URLValidationMessage.js
assets/src/styles/editorOverrides.scss

- Added new control to handle the URL inputs.
- Added styling for the error mesasage

PLANET-4143 All blocks: Add https:// validation error for url fields

---

assets/src/blocks/Spreadsheet/Spreadsheet.js

See https://jira.greenpeace.org/browse/PLANET-5022

PLANET-5022 Update Spreadsheet block description

---

assets/src/styles/blocks.scss
assets/src/styles/blocks/core-overrides/Separator.scss

See https://jira.greenpeace.org/browse/PLANET-4511
There is also a PR for this in master-theme repo: https://github.com/greenpeace/planet4-master-theme/pull/1095

PLANET-4511 Separator block default styles

---

planet4-gutenberg-blocks.php

Can be verified on test instances by setting them up with debug bar and EP debug bar plugins. I already set up the test instance for this ticket with them, and also have another search related ticket that has the plugins but doesn't have this change. So the latter can be used for comparison. You need to login to access the debug bar.
https://k8s.p4.greenpeace.org/test-jupiter/?s=test&orderby=_score If you click "Debug" and then "ElasticPress" in the upper right corner, you can see that it logged 1 query.
https://k8s.p4.greenpeace.org/test-deimos/?s=spread+sheet&orderby=_score Checking in the same location you can see that 2 queries were executed.
* We actually don't use the main query and execute a query ourselves to
perform the search, so we can make the main query return an empty and …

PLANET-4923 Prevent the main query in search

---

assets/src/components/URLValidationMessage/URLValidationMessage.js

- fix invalid URL message to show https validation error and then invalid URL(based on the domain) Message.

PLANET-4143-fix improve invalid URL message

---

templates/blocks/campaign_covers.twig
templates/blocks/content_covers.twig
templates/blocks/counter.twig
templates/blocks/covers.twig
templates/blocks/old_covers.twig
templates/blocks/take_action_boxout.twig

[JIRA 5071](https://jira.greenpeace.org/browse/PLANET-5071)
- Added a data attributes on Cover and TA boxout blocks
- For consistency, change the indentation of twig file from spaces to tab

PLANET-5071 Add data attributes on Covers Block

---

public/js/submenu.js

- Changed regex to replace normal dash character and unicodes for all occurrences in the string.

PLANET-5101 Planet 4 Bug Report: Submenu block: Dash breaks anchor link

---

planet4-gutenberg-blocks.php

https://jira.greenpeace.org/browse/PLANET-5160

PLANET-5160 Don't cancel main search query in admin

---

classes/controller/menu/class-blocks-usage-controller.php

Adding the permalink to the overview allows for quick linking from the overview to the public link.
Added benefit (reason I worked on it): It's easier (and faster) to make overviews as deliverables

Add permalink to the blocks usage overview

---

classes/blocks/class-articles.php
classes/class-loader.php

One of these referenced a class in master theme so needs to be changed before we move to psr4, the other one is the only internal string class reference I found.

PLANET-5099 Use class symbol instead of string

---

assets/src/styles/blocks/Articles.scss
assets/src/styles/blocks/Columns.scss

See https://jira.greenpeace.org/browse/PLANET-5080 (including Will's latest comment, a lot of the information is there)
- Corresponding styleguide PR: greenpeace/planet4-styleguide#65
- Corresponding master-theme PR: greenpeace/planet4-master-theme#1126

Planet 5080 Apply same typography across all P4 blocks

---

assets/src/components/p4_button/edit.js
assets/src/styles/blocks/Articles.scss
assets/src/styles/blocks/CarouselHeader.scss
assets/src/styles/blocks/CarouselHeader_full_width_classic.scss
assets/src/styles/blocks/Columns.scss
assets/src/styles/blocks/Covers/ContentCovers.scss
assets/src/styles/blocks/Gallery_carousel.scss
assets/src/styles/blocks/Happypoint.scss
assets/src/styles/blocks/SocialMediaCards.scss
assets/src/styles/campaigns/themes/_theme_climate.scss
assets/src/styles/editorOverrides.scss
classes/class-loader.php

Just changing some grey shades.
Ref: https://jira.greenpeace.org/browse/PLANET-5082
Related PRs:
https://github.com/greenpeace/planet4-master-theme/pull/1128
https://github.com/greenpeace/planet4-plugin-gutenberg-engagingnetworks/pull/53
https://github.com/greenpeace/planet4-styleguide/pull/64

PLANET-5082: Accessibility change red based greys to blue based ones.	

---

assets/src/styles/blocks/Covers/TakeActionCovers.scss
assets/src/styles/blocks/Media.scss
assets/src/styles/blocks/Spreadsheet.scss
assets/src/styles/blocks/core-overrides/BlockSpacing.scss
assets/src/styles/blocks/core-overrides/Image.scss
assets/src/styles/blocks/core-overrides/Separator.scss

See https://jira.greenpeace.org/browse/PLANET-5116 (UAT already passed)
- Corresponding styleguide PR: https://github.com/greenpeace/planet4-styleguide/pull/61
- Corresponding master-theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1109

PLANET-5116 - Fix block vertical spacing

---

README.md

Updating the README to be consistent with the new way of rendering blocks. 
Ref: https://jira.greenpeace.org/browse/PLANET-4793

PLANET-4793: WYSIWYG preparation: decide on the rendering approach

---

.circleci/config.yml
.eslintrc.json
assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
jest-puppeteer.config.js
jest.config.js
jest.setup.js
package-lock.json
package.json
tests/js/__snapshots__/spreadsheet.spec.js.snap
tests/js/e2e-tests-helpers.js
tests/js/spreadsheet.spec.js

Ref: https://jira.greenpeace.org/browse/PLANET-5077
To test, run `npm install` and `npm test`. 
Use `npm run test:watch` to run the tests in slow motion and see what happens in the browser.

PLANET-5077: Measure JS code test coverage

---

assets/src/styles/campaigns/block-overrides/_campaign_carousel.scss

⚠️ Note: this is based on the `planet-4820` branch. 
Ref: https://jira.greenpeace.org/browse/PLANET-4554

PLANET-4554: #408717: Gallery block: Caption completely covers image gallery on mobile

---

assets/src/blocks/Articles/ArticlesBlock.js
assets/src/blocks/Articles/ArticlesEditor.js
assets/src/blocks/Articles/ArticlesFrontend.js
assets/src/blocks/Articles/ArticlesList.js
assets/src/blocks/Articles/useArticlesFetch.js
classes/blocks/class-articles.php

* That way we can call both hooks inside of it and registerBlockType
is a lot simpler.

PLANET-4801 Make ArticlesEditor function compo

---

assets/src/blocks/Articles/ArticlePreview.js

See https://jira.greenpeace.org/browse/PLANET-5376
- You can see the **broken** version here: https://k8s.p4.greenpeace.org/test-phoebe/
- You can see the **fixed** version here: https://k8s.p4.greenpeace.org/test-uranus/

PLANET-5376 Fix date parsing in ArticlePreview

---

assets/src/blocks/Articles/ArticlePreview.js
assets/src/blocks/Articles/ArticlesFrontend.js

Ref. [JIRA 5204](https://jira.greenpeace.org/browse/PLANET-5204)

PLANET-5204 Add data attributes on Articles Block

---

templates/blocks/carousel_header_full-width-classic.twig

added google analytics data attributes to carousel header

PLANET-5200 Implement data attributes on Carousel Header

---

templates/blocks/carousel_header_full-width-classic.twig

PLANET-5200 Fix removed duplicate '>' in twig file

---

assets/src/blocks/Counter/CounterFrontend.js

Added role=test to the counter text to stop screen reader splitting up the text from the spans

PLANET-5227 added role=text to counter text for accessibility

---

assets/src/blocks/Counter/CounterFrontend.js
tests/js/__snapshots__/counter.spec.js.snap
tests/js/counter.spec.js
tests/js/e2e-tests-helpers.js

Ref. [JIRA 5300](https://jira.greenpeace.org/browse/PLANET-5300)
To test, run `npm install` and `npm test`.
Use `npm run test:watch` to run the tests in slow motion and see what happens in the browser.

PLANET-5300 Add JS acceptance tests for Counter block

---

assets/src/blocks/Cookies/CookiesFrontend.js

Secure attribute added based on protocol

PLANET-5320 P4 Cookies should implement the 'Secure' attribute

---

classes/blocks/class-articles.php

It's pretty straightforward, see https://jira.greenpeace.org/browse/PLANET-5462

PLANET-5462 Order articles by date when manual override

---

assets/src/blocks/Articles/ArticlesEditor.js

No corresponding ticket, just a tiny typo I spotted while working on something else 😬

Fix small typo in ArticlesEditor

---

assets/src/BlockEditorValidation.js
assets/src/blocks/Carouselheader/CarouselHeaderBlock.js
assets/src/editorIndex.js

- Added solution for pre-publish validation
- Added to carousel header

PLANET-4904 Carousel Header: Add validation to prevent slides without image

---

assets/src/blocks/Articles/ArticlePreview.js
assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
templates/blocks/old_covers.twig
templates/blocks/take_action_boxout.twig

added span with aria-label for hashtag accessibility in blocks
Fixes greenpeace/planet4#71

PLANET-5229 Hashtags Accessibility

---

assets/src/styles/blocks/Happypoint.scss

- Remove top padding from the wrapper
- Vertical align the iframe by placing it at 50% and using a negative top margin

PLANET-5502 Vertical align happypoint block iframe

---

tests/js/__snapshots__/articles.editor.spec.js.snap
tests/js/articles.editor.spec.js

Related to [JIRA #5493](https://jira.greenpeace.org/browse/PLANET-5493)

PLANET-5493 Fix articles block manual override JS test

---

assets/src/blocks/Gallery/GalleryCarousel.js

This PR allows us to use React for the Gallery slider transitions, instead of relying on the bootstrap JS code (however I took a lot of inspiration from their code, specifically [this function](https://github.com/twbs/bootstrap/blob/main/js/src/carousel.js#L412))
This means that now the slider is fully functional in the editor too 🙂 which was requested during UAT!

PLANET-4800 Use React for GalleryCarousel

---

assets/src/styles/blocks/Columns.scss

See https://jira.greenpeace.org/browse/PLANET-5374
I've added a CSS variable for the Columns header color, @Inwerpsel please let me know if the name fits the rules 🙂

PLANET-5374 Update Columns header color

---

.circleci/config.yml
composer.json

* Upload a zip file to the corresponding release on tag.
Same changes as were applied for master theme here https://github.com/greenpeace/planet4-master-theme/pull/1182
Ref: https://jira.greenpeace.org/browse/PLANET-5484

PLANET-5484 Build zip on tag

---

classes/class-loader.php

Ref. [PLANET-5377](https://jira.greenpeace.org/browse/PLANET-5377)
Related PR [#5](https://github.com/greenpeace/planet4-handbook/pull/5)

PLANET-5377 Sets translated strings for a JS script

---

assets/src/styles/blocks/Gallery_carousel.scss
assets/src/styles/campaigns/block-overrides/_campaign_carousel.scss
assets/src/styles/campaigns/themes/_theme_antarctic.scss
assets/src/styles/campaigns/themes/_theme_arctic.scss
assets/src/styles/campaigns/themes/_theme_climate.scss
assets/src/styles/campaigns/themes/_theme_forest.scss
assets/src/styles/campaigns/themes/_theme_oceans.scss
assets/src/styles/campaigns/themes/_theme_oil.scss
assets/src/styles/campaigns/themes/_theme_plastic.scss

See https://jira.greenpeace.org/browse/PLANET-4622

PLANET-4622 Remove blue caption from Gallery slider

---

assets/src/styles/blocks/ENForm/components/_enform.scss
assets/src/styles/blocks/Happypoint.scss

See https://jira.greenpeace.org/browse/PLANET-5613
- [styleguide](https://github.com/greenpeace/planet4-styleguide/pull/82)
- [master-theme](https://github.com/greenpeace/planet4-master-theme/pull/1237)

PLANET-5613 Add border-radius to all form fields

---

classes/controller/menu/class-blocks-usage-controller.php
planet4-gutenberg-blocks.php

This just enables the group block in the list of allowed blocks.

PLANET-5499: Enable Group block

---

assets/src/styles/blocks/Covers/TakeActionCovers.scss
templates/blocks/campaign_covers.twig
templates/blocks/content_covers.twig
templates/blocks/old_covers.twig

Improved accessibility for all covers block styles

PLANET-5228 Covers block accessibility

---

assets/src/blocks/Takeactionboxout/Takeactionboxout.js
assets/src/styles/blocks.scss
assets/src/styles/blocks/Covers/TakeActionBoxoutBottom.scss
assets/src/styles/blocks/Covers/TakeActionBoxoutScroll.scss
assets/src/styles/blocks/Covers/TakeActionCovers.scss
public/js/post_action.js
templates/blocks/take_action_boxout.twig

See https://jira.greenpeace.org/browse/PLANET-5325 and latest designs in https://jira.greenpeace.org/browse/PLANET-5108
If you want to test the RTL changes, just add `dir="rtl"` in the inspector to the `html` element!
**Bottom variant**
- Add `action-card-bottom` to the classes of the `action-card` element
- In `post_action.js` write the following in an `else` statement:
```
const element = document.querySelector('.action-card-bottom');
const post = document.querySelector('.post-content');
if (post) {
post.appendChild(element);
element.style.display = 'block';
}
```
**Scroll variant**
- Add `action-card-scroll` to the classes of the `action-card` element
- In `post_action.js` write the following in an `else` statement:
```
window.addEventListener('scroll', action_card_scroll); …
```

Planet 5325 Take Action Boxout A/B test

---

.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

- Link to main CoC
- De-duplicate information from README and link to main repo for info and tickets
- Added a simple PR template.

De-duplicate contribution information

---

assets/src/blocks/Articles/ArticlesFrontend.js

See https://jira.greenpeace.org/browse/PLANET-5593

PLANET-5593 Hide Articles block if no articles to display

---

classes/blocks/class-articles.php

[JIRA 5726](https://jira.greenpeace.org/browse/PLANET-5726)
**Task :**
- Hide password protected posts on articles block

PLANET-5726 Hide password protected post on articles block

---

assets/src/styles/blocks/Columns.scss
templates/blocks/columns_tasks.twig

See https://jira.greenpeace.org/browse/PLANET-5522 (including the comments where Magali added more specs)
- After discussion with Magali I've also removed the links on images, since it's not something that we do in other P4 blocks and we already have title and CTA as links.
- I've also cleaned up the code a bit from unused classes (`blue-button`, `steps-action`) and unnecessary ones (`has-cta`)

PLANET-5522 Fix Columns Tasks block styles

---

assets/src/styles/blocks/Submenu.scss

Ref: https://jira.greenpeace.org/browse/PLANET-5754
---
This will be moved to the styleguide.

PLANET-5754 Remove smooth scrolling from block code

---

assets/src/blocks/Counter/CounterFrontend.js
public/js/counter.js

Ref: https://jira.greenpeace.org/browse/PLANET-5747
---
Moved the script that appends the counter bar to the en-form block into the Frontend file and removed the old script

PLANET-5747 Counter block: Counter is not inserted into EN Form

---

.circleci/config.yml
assets/src/styles/style.scss
composer.json
composer.lock

Ref: https://jira.greenpeace.org/browse/PLANET-5434

PLANET-5434 Split frontend linters and update composer dependencies

---

composer.json
composer.lock

To accommodate composer 1. Need to be merged after greenpeace/planet4-circleci-unit-tests#6

Switch to github-archive-installer 1.1

---

classes/controller/api/class-rest-controller.php
classes/controller/menu/class-blocks-usage-controller.php
classes/rest/class-rest-api.php

Preparatory fixes for WP 5.5. For now only consists of specifying permission callbacks.

PLANET-5458 Prep for WP 5.5

---

.circleci/config.yml

Ref: https://jira.greenpeace.org/browse/PLANET-5685
Same changes as https://github.com/greenpeace/planet4-master-theme/pull/1244/files

PLANET-5685 Book instance, do lighthouse

---

assets/src/blocks/Cookies/CookiesFrontend.js
assets/src/styles/blocks.scss
assets/src/styles/blocks/Cookies.scss
assets/src/styles/blocks/ENForm/components/_enform-full-width.scss
assets/src/styles/blocks/ENForm/components/_enform-side-style.scss
assets/src/styles/blocks/ENForm/components/_enform.scss
assets/src/styles/blocks/Spreadsheet.scss
templates/blocks/enform/country_select.twig
templates/blocks/enform/enform_post.twig
templates/blocks/enform/position_select.twig

- [PLANET-5705](https://jira.greenpeace.org/browse/PLANET-5705): update form input styles (border, fonts, colors)
- [PLANET-5512](https://jira.greenpeace.org/browse/PLANET-5512): add label/placeholder animation
- styleguide: https://github.com/greenpeace/planet4-styleguide/pull/87
- master-theme: https://github.com/greenpeace/planet4-master-theme/pull/1253

PLANET-5705 - Update form inputs UI

---

.circleci/config.yml

Ref: https://jira.greenpeace.org/browse/PLANET-5883
Same changes as https://github.com/greenpeace/planet4-master-theme/pull/1283 to run the workflow on merge commits.

PLANET-5883 Reset instance on merge

---

assets/src/ImageBlockExtension.js

See [PLANET-5873](https://jira.greenpeace.org/browse/PLANET-5873)
This PR solves the latest task listed in the ticket, a.k.a:
- Fix caption alignment option in the sidebar (from P4 options) which now doesn't update properly, probably due to this line taking the previous value of `captionAlignment`

PLANET-5873 Fix Image block caption alignment update for WP 5.6

---

assets/src/blocks/Cookies/CookiesFrontend.js

See https://jira.greenpeace.org/browse/PLANET-5755
- master-theme: https://github.com/greenpeace/planet4-master-theme/pull/1306
- styleguide: https://github.com/greenpeace/planet4-styleguide/pull/99

PLANET-5755 Remove jQuery from cookies

---

.circleci/config.yml
assets/src/styles/blocks/Covers/TakeActionCovers.scss
assets/src/styles/campaigns/themes/_theme_oceans.scss
assets/src/styles/campaigns/themes/_theme_plastic.scss
assets/src/styles/vendors/photoswipe/_main-settings.scss
assets/src/styles/vendors/photoswipe/main.scss
assets/src/styles/vendors/photoswipe/p4-skin.scss
assets/src/styles/vendors/photoswipe/planet4-photoswipe.scss

stylelint needs a double-quoted path, otherwise it doesn't make a recursive lookup.
Fixed all pending issues stylelint did't report correctly up until now.

Fix stylelint recursive path

---

assets/src/styles/blocks/SplitTwoColumns.scss

Ref: [JIRA 5815](https://jira.greenpeace.org/browse/PLANET-5815)
---
- I don’t have a big monitor to test the exact screen sizes, but with browser debugger tool I tested the fix

PLANET-5815 Fix split two columns text size on large screen

---

admin/css/admin_en.css
assets/src/styles/blocks/CarouselHeader_full_width_classic.scss
assets/src/styles/blocks/Columns.scss
assets/src/styles/blocks/Covers/CampaignCovers.scss
assets/src/styles/blocks/Covers/TakeActionBoxoutBottom.scss
assets/src/styles/blocks/Covers/TakeActionBoxoutScroll.scss
assets/src/styles/blocks/Covers/TakeActionCovers.scss
assets/src/styles/blocks/ENForm/components/_enform-side-style.scss
assets/src/styles/blocks/ENForm/components/_enform.scss
assets/src/styles/blocks/SplitTwoColumns.scss
assets/src/styles/blocks/Submenu.scss
assets/src/styles/campaigns/components/_campaign_covers.scss
assets/src/styles/campaigns/themes/_theme_antarctic.scss
assets/src/styles/editorOverrides.scss
classes/class-loader.php

See https://jira.greenpeace.org/browse/PLANET-5843
**Black / Grey colors:**
- ~~#000000 = $black -> replace by #020202 = $grey-80~~
- ~~#030403 = $header-footer-bg -> replace by #020202 = $grey-80~~
- ~~#1a1a1a = none -> replace by #020202 = $grey-80~~
- ~~#052a30 = $dark-tiber -> replace by #020202 = $grey-80~~
- ~~#242424 = none -> replace by #23292d = $grey~~
- #a7a7a7 = $step-number -> unused, was removed with https://jira.greenpeace.org/browse/PLANET-5842
- #aaaaaa = none -> replace by #a3a5a7 = $grey-20 -> couldn't find it, seems unused
**Blue colors:**
- ~~#0a3351 = $med-blue -> replace by #074365 = $dark-blue~~
- ~~#094464 = $cookie-blue -> replace by #074365 = $dark-blue~~
- ~~#014c8c = $menu-blue ->replace by #020202 = $grey-80~~
- ~~#0058cc = $link-hover-color -> replace by …

PLANET-5843 Replace some colors to align with the design system

---

assets/src/blocks/Gallery/GalleryCarousel.js
templates/blocks/carousel_header_full-width-classic.twig

Ref: https://jira.greenpeace.org/browse/PLANET-5906
We need to check this update changes nothing.
See the [master theme PR](https://github.com/greenpeace/planet4-master-theme/pull/1305) for more info.
There's a [styleguide PR](https://github.com/greenpeace/planet4-styleguide/pull/98) too.
---

PLANET-5906: Migrate to Bootstrap 5

---

planet4-gutenberg-blocks.php

Ref: https://jira.greenpeace.org/browse/PLANET-5986

PLANET-5986 Disable Take Action Boxout from Pages

---

composer.json
composer.lock

Ref:  https://jira.greenpeace.org/browse/PLANET-6020

Upgrade github-archive-installer to support composer 2

---

phpcs.xml
tests/acceptance/CarouselHeaderClassicCept.php
tests/acceptance/ColumnsIconsCept.php
tests/acceptance/ColumnsImagesCept.php
tests/acceptance/ColumnsNoImageCept.php
tests/acceptance/ColumnsTasksCept.php
tests/acceptance/CoversCampaignCept.php
tests/acceptance/CoversContentCept.php
tests/acceptance/CoversTakeActionCept.php
tests/acceptance/ENFormCest.php
tests/acceptance/MediaCept.php
tests/acceptance/SplitTwoColumnsCept.php
tests/acceptance/TakeActionBoxoutCept.php

Ref: https://jira.greenpeace.org/browse/PLANET-6045
---
First step in moving tests to app repos. These are the tests that test blocks functionality.

PLANET-6045 Add relevant Acceptance tests

---

assets/src/styles/campaigns/themes/_theme_antarctic.scss
assets/src/styles/campaigns/themes/_theme_arctic.scss
assets/src/styles/campaigns/themes/_theme_climate.scss
assets/src/styles/campaigns/themes/_theme_forest.scss
assets/src/styles/campaigns/themes/_theme_oceans.scss
assets/src/styles/campaigns/themes/_theme_oil.scss
assets/src/styles/campaigns/themes/_theme_plastic.scss

---
Needs to be updated to track the new format of generated variable names https://github.com/greenpeace/planet4-master-theme/blob/d1189ab0148b2ab6c35ffc0b67ae3788224fdb3d/assets/src/scss/base/_typography.scss#L134-L138

PLANET-5983 Follow variable name change

---

assets/src/blocks/OldCarouselheader/CarouselHeader.js
assets/src/blocks/OldCarouselheader/CarouselHeaderBlock.js
assets/src/blocks/OldCarouselheader/CarouselHeaderFront.js
assets/src/blocks/OldCarouselheader/CarouselHeaderImage.js
assets/src/blocks/OldCarouselheader/CarouselHeaderSlide.js
assets/src/blocks/OldCarouselheader/FullWidthCarouselHeader.js
assets/src/blocks/OldCarouselheader/ImagePlaceholder.js
assets/src/carouselHeaderFrontIndex.js
assets/src/editorIndex.js
assets/src/styles/blocks.scss
assets/src/styles/blocks/OldCarouselHeader.scss
assets/src/styles/blocks/OldCarouselHeaderEditor.scss
assets/src/styles/blocks/OldCarouselHeaderEditorOverrides.scss
assets/src/styles/blocks/OldCarouselHeader_full_width_classic.scss
assets/src/styles/editorStyle.scss
classes/blocks/class-oldcarouselheader.php
classes/class-loader.php

This PR is to prepare the CarouselHeader block for adding the WYSIWYG version (https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/483) to beta blocks.

PLANET-4809 Copy CarouselHeader to OldCarouselHeader

---

.circleci/config.yml

Follow up PR from: greenpeace/planet4-circleci#46
Simliar to: greenpeace/planet4-master-theme#1372

Add a job for posting a PR comment when test instance is ready

---

classes/blocks/class-carouselheader.php

Ref: https://jira.greenpeace.org/browse/PLANET-4809
---
I wanted to push this to https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/483, but I missed that my push failed before we merged that one :sweat_smile:

PLANET-4809 Enqueue hammer only if block is present

---

.circleci/config.yml
composer.json
composer.lock

Ref: https://jira.greenpeace.org/browse/PLANET-6020
---
Counterpart of https://github.com/greenpeace/planet4-master-theme/pull/1383

PLANET-6020 Upgrade github-archive-installer to support composer 2

---

.circleci/config.yml
commitlint.config.js
package-lock.json
package.json

Ref: https://jira.greenpeace.org/browse/PLANET-6114
---
Same as planet4-master-theme/pull/1386

PLANET-6114 Add commitlint CI job

---

assets/src/blocks/SocialMediaCards/SocialMediaCardsBlock.js
planet4-gutenberg-blocks.php

Ref: [JIRA 6165](https://jira.greenpeace.org/browse/PLANET-6165)
---

PLANET-6165 Move Social Media Card block to Beta

---

.circleci/config.yml

This is just the counterpart of greenpeace/planet4-master-theme#1392

Inject version key in composer file on zip creation

---

composer.json
composer.lock

To make it work with both Composer 1 and 2.

Bump github-archive-installer to 1.3.2

---

composer.json
composer.lock

This should be merged along with https://github.com/greenpeace/planet4-builder/pull/83

Remove Github Archive Downloader plugin #1394

---

assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
assets/src/styles/blocks/Spreadsheet/SpreadsheetStyle.scss

Just pulling in the commit so that protected jobs can run on the fork's code.

PLANET-5247 (Just for running protected tests against fork code) A11y: Address accessibility of spreadsheet block

---

templates/blocks/enform/tease-thankyou.twig

This PR is blocked by https://github.com/greenpeace/planet4-master-theme/pull/1419
Ref: https://jira.greenpeace.org/browse/PLANET-6083

PLANET-6083: Pass utm_medium param to share buttons Twig template

---

.circleci/config.yml

Add missing quotes

---

assets/src/blocks/CarouselHeader/Sidebar.js
assets/src/styles/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss

Add first implementation of re-ordering to Carousel Header Slides. See commit message and code comments for detailed explanation.
Ref: https://jira.greenpeace.org/browse/PLANET-6137

PLANET-6137 Allow re-ordering slides

---

.circleci/config.yml

Ref: https://jira.greenpeace.org/browse/PLANET-6306
Add PHP 7.4 job on Circleci

PLANET-6306: Run tests on PHP 7.4

---

assets/src/components/Sidebar/CampaignSidebar.js

* Renamed in other repo.
See https://github.com/greenpeace/planet4-master-theme/pull/1451
I also renamed the variables relating to these options in the code within this file. I'll do some further changes in a follow up PR once this one is merged, so that it can have a diff that is somewhat understandable.

Use files from renamed location

---

assets/src/blocks/Cookies/CookiesFrontend.js
classes/class-loader.php

See https://jira.greenpeace.org/browse/PLANET-6223
Go to https://www-dev.greenpeace.org/test-iocaste/privacy/ to test all the possible cookie combinations (also the "Got it!" button from the cookies banner) and check that the correct events are firing.
- [master-theme](https://github.com/greenpeace/planet4-master-theme/pull/1442)

PLANET-6223 Implement Google's Consent Mode on Planet 4

---

.circleci/config.yml

Counterpart of https://github.com/greenpeace/planet4-master-theme/pull/1516

Keep tests folder on zip creation

---

assets/src/blocks/Submenu/getHeadingsFromDom.js
assets/src/components/Lightbox/setupLightboxForImages.js
assets/src/styles/blocks/core-overrides/BlockSpacing.scss
public/js/enform_side_style.js
tests/acceptance/CarouselHeaderClassicCept.php
tests/js/articles.frontend.spec.js

Ref: https://jira.greenpeace.org/browse/PLANET-5321
---
Counterpart of https://github.com/greenpeace/planet4-master-theme/pull/1533

Replace page-template with page-content as its main class

---

classes/blocks/class-covers.php

Ref: https://jira.greenpeace.org/browse/PLANET-6489
Core bug: https://core.trac.wordpress.org/ticket/51019
The _Content covers_ style for Covers blocks currently [includes all related posts data](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/3b65aa8502dfa03fd5f750b17d07b33e3f6a8dc5/classes/blocks/class-covers.php#L443) in its attributes, including `post_content`.
A core wordpress function `convert_smilies()` has a [known bug](https://core.trac.wordpress.org/ticket/51019) that will return an empty output if given a text too large.
In the ticket situation, the language encoding makes a regular post weight 3 to 4 times more than using only ascii characters, which leads to passing over the [`preg_split`](https://github.com/WordPress/wordpress-develop/blob/5.8/src/wp-includ …

PLANET-6489: Reduce data included in Covers block

---

tests/acceptance/MediaCept.php

* Needed to allow a master theme PR to pass.

Allow lite-youtube element in Media test

---

assets/src/blocks/Articles/ArticlePreview.js
classes/blocks/class-articles.php

Ref: https://jira.greenpeace.org/browse/PLANET-6432
Cf. https://github.com/greenpeace/planet4-master-theme/pull/1542

PLANET-6432: Add reading time to post details

---

assets/src/blocks/Happypoint/EmbedCodeHelp.js
assets/src/blocks/Happypoint/HappypointBlock.js
assets/src/blocks/Happypoint/HappypointEditor.js
assets/src/blocks/Happypoint/HappypointFrontend.js
assets/src/blocks/Happypoint/useHubspotEmbedCode.js
assets/src/components/useScript/useScript.js
classes/blocks/class-happypoint.php

See https://jira.greenpeace.org/browse/PLANET-6496
---
Added the "embed code" options to happy point block editor. -

PLANET-6496 Happy Point: Add option for code snippet embed

---

planet4-gutenberg-blocks.php

Ref.https://jira.greenpeace.org/browse/PLANET-6594

PLANET-6594 Enable core WP "Media & Text" block

---

classes/controller/menu/class-blocks-usage-controller.php
classes/search/block/class-blockusage.php
classes/search/block/class-blockusagetable.php
classes/search/block/class-query.php
classes/search/block/query/class-parameters.php
classes/search/block/sql/class-regex.php
classes/search/block/sql/class-sqlquery.php
classes/search/class-blocksearch.php

_Following [experimentation day](https://docs.google.com/document/d/1-UX-5TNLow9766yaTGUa0I2KxpfeUtgl6sf0iCizWoM/edit) - no ticket_
This page is accessible in the menu **Blocks > Report (beta)**
- native table (`WP_List_Table`), native block parser (`WP_Block_Parser`)
- filter by block namespace or block type
- group by block or post
- search in block options
- quick action links - edit/(pre)view/clone/new draft  
- detailed block attributes
```
classes/search
├── block
│   ├── class-blockusage.php       // Block usage, parsing/filtering/sorting posts and blocks
│   ├── class-blockusagetable.php  // Extension of WordPress List Table, for presentation
│   ├── class-query.php            // Query interface to retrieve posts ids
│   ├── class-queryparameters.php  // Query parameters bag
│   …
```

PLANET-6634: Experimentation on block usage report

---

planet4-gutenberg-blocks.php

**Task:**
- Allowed all blocks which are whitelisted for page and campaign post types

PLANET-6515 Add Allowed blocks in action page type

---

assets/src/blocks/ENForm/ENFormFrontend.js
classes/rest/class-rest-api.php

- Move form post to Engaging Networks to backend
- Remove auth token public endpoint
- Add Sentry logs in case of failure

Remove EN form auth public endpoint

---

assets/src/blocks/Articles/ArticlesEditor.js
classes/blocks/class-articles.php
planet4-gutenberg-blocks.php

The 'Include Articles in Post' setting is moved as articles block at the end of post
Ref.: https://jira.greenpeace.org/browse/PLANET-6612

PLANET-6612 Whitelist the articles block in Post

---

classes/controller/menu/class-blocks-usage-controller.php

* I need to easily see which pages use these on GP Brasil site, so we
can check the scale of the image resolution issue.
* Also add Query Pagination, they're not allowed but we'd definitely
want to know if someone starts using, even on the dev site.

Add Query and Query pagination to post report

---

assets/src/styles/blocks/ENForm/campaigns/_mixins.scss
assets/src/styles/blocks/ENForm/components/_enform.scss

[PLANET-4993](https://jira.greenpeace.org/browse/PLANET-4993)
* Also remove CSS variable with no default.

PLANET-4993 Remove EN Form font families

---

classes/controller/menu/class-blocks-usage-controller.php

Also alphabetize core blocks list.

Add Columns block on blocks usage report

---

classes/blocks/class-blocklist.php

A reusable block including itself generates an infinite loop on parsing.
The page crashes anyway with or without this code, this fix only limits recursion in the block check itself.
Keeping a list of reusable blocks already parsed helps getting out of the loop.
- Create a reusable block in _Blocks > All Reusable blocks_ and save
- Edit it and include it in itself (with `/` command or code ``)
- Create a page, include your reusable block
To see the effect of the fix, you can add a log and check what happens:
- Add `error_log(__METHOD__);` on l.56
- Clear blocklist cache with `make flush`
- Check logs with `docker-compose logs -f php-fpm`
- Display your page on frontend
- Without fix (comment l.95/96) you'll get thousands of `NOTICE: PHP message: P4GBKS\Blocks\BlockList::get_block_list`
- …

Fix reusable block loop on parsing

---

classes/controller/menu/class-blocks-usage-controller.php
classes/search/block/class-blockusage.php
classes/search/block/class-blockusageapi.php
classes/search/block/class-blockusagetable.php

Ref: https://jira.greenpeace.org/browse/PLANET-6781
Block report is paginated, which greatly reduces page weight
WordPress uses a redirection scheme to verify nonce, filter parameters and redirect to the proper page.
We use the same system here, with a hook on `admin_action_*`, this allows to switch to GET mode and simplifies url handling.
Style used for a block is listed in the search results (detection based on classname)
It is always possible to search for a specific style by searching for its name in the search box, ie `is-style-cta` will return all blocks with this string in their attributes.
Attempt at an API replacement, that includes all pages, blocks and styles
```shell
> curl -k https://www.planet4.test/wp-json/plugin_blocks/v3/plugin_blocks_report/ | jq 
```
<details> …

PLANET-6781: Block report - pagination, block style, api

---

classes/class-loader.php
classes/patterns/class-blankpage.php
classes/patterns/class-getinformed.php

This commit also includes adding the `-pattern-layout` suffix to the Get Informed layout and updating its category

Rename Pages patterns category to Layouts

---

tests/acceptance/PatternsCept.php

Added by a suggestion of @sagarsdeshmukh from [here](https://github.com/greenpeace/planet4-master-theme/pull/1754#issuecomment-1180061228)

Create specs to patterns

---

classes/blocks/class-blocklist.php

Follows https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/861
The current code triggers a log if a specific reusable block is included multiple times in the same page, which is not the goal.
- Skip block pasted multiple times in same post.
- Change log content to include current post id and a log of blocks seen and contained.
On test instance I created a series of [4 reusable blocks](https://www-dev.greenpeace.org/test-leda/wp-admin/edit.php?post_type=wp_block), 3 looping and one alone
- block 1 -> includes -> block 2 -> includes -> block 3 -> includes -> block 1
- block 4
and 2 pages
- [Page failing with the looping blocks](https://www-dev.greenpeace.org/test-leda/test-page-block-loop/)
- [Page pasting block 4 multiple …

Fix block loop detection

---

classes/patterns/class-block-pattern.php
classes/patterns/class-homepage.php
classes/patterns/templates/class-carouselheader.php

Ref: [PLANET-6524](https://jira.greenpeace.org/browse/PLANET-6524)
Create a new homepage layout pattern.
[Demo page](https://www-dev.greenpeace.org/test-phobos/51534-2/) 
1. Create a new page
2. Go to the Patterns > Pages and chose the Homepage.

PLANET-6524: New homepage block pattern

---

assets/src/styles/blocks.scss
classes/patterns/class-issues.php

Change the item template. 
Also the spacing is now defined by the [theme](https://github.com/greenpeace/planet4-master-theme/pull/1765/files#diff-160c735a986cf8c05e1f6b2e9ac89dd0410562d2fe5ccbdc93157bd92f3dc2bcR91-R95).
[Demo page](https://www-dev.greenpeace.org/test-venus/custom-paddings-demo-page/)
Ref: [PLANET-6768](https://jira.greenpeace.org/browse/PLANET-6768)

PLANET-6768: Update issues pattern

---

admin/js/editor.js
assets/src/styles/blocks.scss
classes/patterns/class-action.php

We can now use the theme padding options instead 🎉

Remove custom padding classes from some core blocks

---

classes/patterns/class-block-pattern.php
classes/patterns/class-highleveltopic.php

See [PLANET-6737](https://jira.greenpeace.org/browse/PLANET-6737)
On an empty page, add the `High-Level Topic` layout either via the block inserter or via the page creation modal. You can then see its initial state and edit it as you want 🙂

PLANET-6737 Implement High-Level Topic pattern layout

---

classes/patterns/class-highleveltopic.php

We forgot to update the template name before merging 🤦‍♀️

Use new GravityFormWithText template in High Level Topic

---

classes/patterns/class-highleveltopic.php
classes/patterns/templates/class-covers.php

This is needed for some pattern layouts such as [High Level Topic](https://jira.greenpeace.org/browse/PLANET-6737) or [Campaign](https://jira.greenpeace.org/browse/PLANET-6528). This commit actually also updates the High Level topic one, which you can use to test the changes!

Add title_placeholder param to Covers template

---

classes/patterns/class-highleveltopic.php
classes/patterns/class-pageheader.php

This is needed for some pattern layouts such as [High Level Topic](https://jira.greenpeace.org/browse/PLANET-6737) or [Campaign](https://jira.greenpeace.org/browse/PLANET-6528). This commit actually also updates the High Level topic one, which you can use for testing these changes!

Add title_placeholder param to PageHeader pattern

---

classes/patterns/class-action.php
classes/patterns/class-homepage.php
classes/patterns/templates/class-covers.php

This is to avoid duplicate code and also to add the Take Action style as default, since it's the most used one in pattern layouts
On local, you can add either the Homepage or Action pattern layout to a page and make sure it still looks as expected!

Refactor Covers template

---

classes/patterns/class-action.php
classes/patterns/class-blankpage.php
classes/patterns/class-block-pattern.php
classes/patterns/class-campaign.php
classes/patterns/class-deepdive.php
classes/patterns/class-deepdivetopic.php
classes/patterns/class-getinformed.php
classes/patterns/class-highleveltopic.php
classes/patterns/class-highlightedcta.php
classes/patterns/class-homepage.php
classes/patterns/class-issues.php
classes/patterns/class-quicklinks.php
classes/patterns/class-realitycheck.php
classes/patterns/class-sideimagewithtextandcta.php
classes/patterns/class-takeaction.php

See [PLANET-6525](https://jira.greenpeace.org/browse/PLANET-6525)
You can add the Take Action pattern layout to a page either via the block inserter or the page creation modal, then you can edit it as you wish!

PLANET-6525 Implement Take Action pattern layout

---

assets/src/BlockEditorValidation.js
assets/src/blocks/Accordion/AccordionEditorScript.js
assets/src/blocks/Articles/ArticlePreview.js
assets/src/blocks/Articles/ArticlesBlock.js
assets/src/blocks/Columns/ColumnsBlock.js
assets/src/blocks/Cookies/CookiesFrontend.js
assets/src/blocks/Counter/CounterBlock.js
assets/src/blocks/Covers/ContentCovers.js
assets/src/blocks/Gallery/GalleryBlock.js
assets/src/blocks/GuestBook/GuestBookBlock.js
assets/src/blocks/ShareButtons/ShareButtonsBlock.js
assets/src/blocks/SocialMedia/SocialMediaBlock.js
assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
assets/src/blocks/Spreadsheet/SpreadsheetEditorScript.js
assets/src/blocks/Submenu/SubmenuLevel.js
assets/src/blocks/Timeline/TimelineBlock.js
assets/src/blocks/Timeline/TimelineEditorScript.js
assets/src/components/ShareButtons/ShareButtons.js
classes/class-loader.php

Ref. https://jira.greenpeace.org/browse/PLANET-6676
- Remove translation of block name, block style name etc.
- Update text-domain name where-ever needed.

PLANET-6676 Update proper textdomain name in JS files

---

package-lock.json
package.json

As far as I have been investigated, we don't need to migrate any part of our code.
More info: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

Upgrade React DOM to version 18

---

.circleci/config.yml

Ref: https://jira.greenpeace.org/browse/PLANET-5872
---
Counterpart of https://github.com/greenpeace/planet4-master-theme/pull/1811

PLANET-5872 Run a11y against test instances

---

assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js

Otherwise we get errors since the function is used before being defined

Fix translation function import order

---

planet4-gutenberg-blocks.php

Ref: https://jira.greenpeace.org/browse/PLANET-6951
**Demo page**: You can test this functionality trough you local environment and test a listing pagination of campaigns, or any other listing page with only 1 page or wait after [#1812](https://github.com/greenpeace/planet4-master-theme/pull/1812) is being merged.

PLANET-6951: Implement new filter hook applied to query pagination

---

.circleci/config.yml

Couterpart of https://github.com/greenpeace/planet4-master-theme/pull/1828

Simplify Ci config

---

assets/src/block-templates/deep-dive/block.json
assets/src/block-templates/deep-dive/index.js
assets/src/block-templates/deep-dive/template.js
assets/src/block-templates/quick-links/template.js
assets/src/block-templates/template-list.js
classes/patterns/class-deepdive.php
classes/patterns/class-deepdivetopic.php
classes/patterns/class-highleveltopic.php
classes/patterns/class-takeaction.php
planet4-gutenberg-blocks.php

See [PLANET-6940](https://jira.greenpeace.org/browse/PLANET-6940)
You should be able to add a Deep Dive pattern as before without any problems! And the layouts using it should also still work as expected.

PLANET-6940 Convert Deep Dive pattern into a block template

---

assets/src/styles/blocks/Accordion/AccordionStyle.scss
assets/src/styles/blocks/Articles.scss
assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
assets/src/styles/blocks/Columns.scss
assets/src/styles/blocks/Cookies.scss
assets/src/styles/blocks/CookiesEditor.scss
assets/src/styles/blocks/Counter.scss
assets/src/styles/blocks/Covers/styles/CampaignCovers.scss
assets/src/styles/blocks/Covers/styles/ContentCovers.scss
assets/src/styles/blocks/Covers/styles/TakeActionCovers.scss
assets/src/styles/blocks/ENForm/components/_enform.scss
assets/src/styles/blocks/Gallery/styles/GalleryCarousel.scss
assets/src/styles/blocks/Happypoint.scss
assets/src/styles/blocks/OldENForm/components/_enform.scss
assets/src/styles/blocks/SplitTwoColumns.scss
assets/src/styles/blocks/Submenu.scss
assets/src/styles/blocks/SubmenuEditor.scss
assets/src/styles/blocks/TakeActionBoxout/style.scss
assets/src/styles/blocks/Timeline/TimelineStyle.scss
assets/src/styles/blocks/core-overrides/Image.scss
assets/src/styles/blocks/core-overrides/Table.scss
assets/src/styles/components/EmptyMessage.scss
assets/src/styles/components/LayoutSelector.scss
assets/src/styles/components/ValidationMessage.scss

Counterpart of https://github.com/greenpeace/planet4-master-theme/pull/1878

Add font-family css variables

---

.eslintrc.json
package-lock.json
package.json

**Ref: [PLANET-7112](https://jira.greenpeace.org/browse/PLANET-7112?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D)**
Description
Upgraded two packages for ESLint.

PLANET-7112 Upgrade ESLint and Wordpress Plugin

---

.circleci/config.yml
playwright.config.js
tests/e2e/404.spec.js
tests/e2e/tickets/PLANET-7064/PLANET-7064.test.js
tests/e2e/tools/lib/login.js
tests/e2e/tools/lib/nonce.js
tests/e2e/tools/lib/rest.js

Ref: https://jira.greenpeace.org/browse/PLANET-7064
Copy of: https://github.com/greenpeace/planet4-master-theme/pull/1925
Duplicate PR of https://github.com/greenpeace/planet4-master-theme/pull/1925 to add e2e CI tests to this repository.

PLANET-7064: Playwright CI job

---

.circleci/config.yml

Ref: https://github.com/greenpeace/planet4-circleci/pull/69

Adjust test user trigger to new instance parameter

---

classes/search/class-patternsearch.php

Ref: https://jira.greenpeace.org/browse/PLANET-7179
**Testing:**
- The [blocks report](https://www-dev.greenpeace.org/test-neptune/wp-json/plugin_blocks/v3/plugin_blocks_report/) should works expected on test instance.

PLANET-7179 Fix Block report API error

---

.circleci/config.yml
admin/js/editor.js
admin/js/enforms.js
assets/src/blocks/ENForm/ENFormFrontend.js
assets/src/blocks/ENForm/FormGenerator.js
tests/e2e/enform.spec.js
tests/e2e/fixtures/enform/enformData.js
tests/e2e/take-action-boxout.spec.js
tests/e2e/tickets/PLANET-7064/PLANET-7064.test.js
tests/e2e/tools/lib/rest.js

- Include tests and admin scripts
- Use double quotes to properly interpret glob patterns
- Fixed remaining eslint issues

Expand eslint check on all js code

---

assets/src/components/Sidebar/AnalyticsTrackingSidebar.js
classes/rest/class-rest-api.php

Fetch global & local project analytics values considering current post id
Related PR: https://github.com/greenpeace/planet4-master-theme/pull/2059

PLANET-7169 Fix deprecated value bug in analytics field

---

tests/e2e/articles.spec.js

See [PLANET-5419](https://jira.greenpeace.org/browse/PLANET-5419)
This is to increase our test coverage
On local, you can check the test either using the VSCode extension, or via command line by running `npx playwright test tests/e2e/articles.spec.js`

PLANET-5419 Add Playwright test for Articles block

---

classes/blocks/class-covers.php

Fix notices when act_page is not defined

Fix act_page notices

---

assets/src/styles/blocks/Columns.scss

Ref: https://jira.greenpeace.org/browse/PLANET-7204
The current PR is part of [#2080](https://github.com/greenpeace/planet4-master-theme/pull/2080).

PLANET-7204: Update Columns font weight

---

package-lock.json

Update Browserslist DB
Cf. https://github.com/browserslist/update-db#readme

Update Browserslist DB

---

assets/src/blocks/Articles/ArticlesFrontend.js
assets/src/blocks/Columns/ColumnsFrontend.js
assets/src/blocks/Covers/CoversFrontend.js
assets/src/blocks/Gallery/GalleryFrontend.js
assets/src/blocks/Media/MediaFrontend.js
assets/src/blocks/SocialMedia/SocialMediaFrontend.js
assets/src/blocks/Timeline/TimelineFrontend.js

As a part of https://github.com/greenpeace/planet4-master-theme/pull/2066
- Mostly replace div's description to paragraphs to make it more semantic
- Fix gallery block
Using the [Umbriel's instance](https://github.com/greenpeace/planet4-test-umbriel/blob/main/composer-local.json#L6-L7) as a demo page.

Adjust code regarding the new design tokens

---

assets/src/components/Parallax/setupParallax.js
assets/src/styles/blocks/PageHeader.scss

This PR is open for discussions and think the best solution about this [PLANET-6927](https://jira.greenpeace.org/browse/PLANET-6927)
Fix the page header spacing issue. Here is the [#1969](https://github.com/greenpeace/planet4-master-theme/pull/1969) from the theme.
Here is the [demo page](https://www-dev.greenpeace.org/test-pluto/page-header-demo-page)

PLANET-6927: Fix Page Header spacing issue

---

classes/search/class-patternsearch.php
classes/search/pattern/class-patternusage.php

Fix on Pattern report (API + admin report)
- count block templates as their pattern counterpart
- we use one block template per pattern declared, so we use this as additional pattern identification
- fix query escape issue with `%` char
- WP uses [`vsprintf`](https://www.php.net/vsprintf) to prepare query with args, we need to escape % as `%%`
- this was generating [errors in Sentry](https://sentry.greenpeace.org/organizations/greenpeace-org/issues/25/?query=is%3Aunresolved+vsprintf&referrer=issue-stream&statsPeriod=14d&stream_index=0)
Locally or on [test instance](https://www-dev.greenpeace.org/test-pandora/wp-json/plugin_blocks/v3/plugin_blocks_report/)
- Pattern report (Blocks > Pattern Report) should show `template` matches for each block template registered as a Pattern
- Pattern …

Pattern report is missing template usage

---

assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
assets/src/blocks/Gallery/GalleryFrontend.js

This reverts commit 4969b074b405123362aea7caf78b06f40595c5bb.
This fix was causing duplicated blocks in some sites, so we should revert it for now and then investigate further.

Revert "Fix hydration-related console errors"

---

assets/src/blocks/Covers/CoversScript.js
assets/src/blocks/ENForm/ENFormScript.js
assets/src/blocks/Timeline/TimelineScript.js

The query selector was wrong, resulting in console errors and some blocks not rendering 😬

Fix some blocks fallback rendering

---

assets/src/blocks/Articles/ArticlesEditor.js
assets/src/blocks/Articles/ArticlesFrontend.js
assets/src/blocks/CarouselHeader/Caption.js
assets/src/blocks/CarouselHeader/StaticCaption.js
assets/src/blocks/Covers/CoversEditor.js
assets/src/blocks/Covers/CoversGridLoadMoreButton.js
assets/src/blocks/ENForm/ENFormFrontend.js
assets/src/blocks/ENForm/ENFormInPlaceEdit.js
assets/src/blocks/SplitTwoColumns/SplitTwoColumnsFrontend.js
assets/src/blocks/SplitTwoColumns/SplitTwoColumnsInPlaceEdit.js
assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
assets/src/blocks/TakeActionBoxout/TakeActionBoxoutFrontend.js
assets/src/styles/blocks/TakeActionBoxout/style.scss
templates/blocks/carousel_header_full-width-classic.twig
templates/blocks/enform.twig
templates/blocks/enform/enblock.twig
templates/blocks/enform/tease-thankyou.twig
templates/blocks/take-action-boxout.twig

See [PLANET-7329](https://jira.greenpeace.org/browse/PLANET-7329)
This PR also includes a commit removing the unnecessary `btn-block` button class.
Either on local or on [this post](https://www-dev.greenpeace.org/test-janus/press/1113/duis-posuere-6/) from the janus test instance, make sure to check all screen sizes!

PLANET-7329 Fix Take Action boxout button styles

---

assets/src/blocks/Cookies/CookiesFrontend.js
assets/src/styles/blocks/Columns.scss
assets/src/styles/blocks/ColumnsEditor.scss
assets/src/styles/blocks/Cookies/Cookies.scss

**Ref: [PLANET-7237](https://jira.greenpeace.org/browse/PLANET-7237)**
Testing:
On the assigned test instance or locally blocks should match figma designs.

PLANET-7237 Apply the Design tokens font-family & font-size on certain blocks

---

classes/blocks/class-spreadsheet.php

Ref: https://jira.greenpeace.org/browse/PLANET-7303

Make sure Spreadsheet block is not registered twice.

---

classes/blocks/class-happypoint.php

Ref: [PLANET-7378](https://jira.greenpeace.org/browse/PLANET-7378)
Move the Happypoint block to master-theme
**Related theme's PR**
- https://github.com/greenpeace/planet4-master-theme/pull/2184

PLANET-7378: Make sure to not instantiate twice the Happypoint class

---

classes/blocks/class-gallery.php

Ref: https://jira.greenpeace.org/browse/PLANET-7255
Avoid registering block twice

PLANET-7255: Move Gallery block to master theme

---

classes/blocks/class-submenu.php

Ref: https://github.com/greenpeace/planet4-master-theme/pull/2195
Added check to make sure block is not registered twice.

PLANET-7382 Move Submenu block into master theme

---

.circleci/config.yml
classes/search/block/sql/class-like.php

Ref: https://jira.greenpeace.org/browse/PLANET-7388
- Fix deprecated message on strpos() first arg null
- Remove php7.4 tests

PLANET-7388: Fix deprecated message on strpos

---

.circleci/config.yml

fix: change gsutil into gcloud

---

classes/blocks/class-socialmedia.php

Ref: https://github.com/greenpeace/planet4-master-theme/pull/2224

Add code to prevent registering Social Media block twice

---

classes/blocks/class-articles.php

Ref: https://jira.greenpeace.org/browse/PLANET-7426
Requires: https://github.com/greenpeace/planet4-master-theme/pull/2221

PLANET-7426: Integrate reading time display value

---

classes/blocks/class-media.php

**Ref: https://github.com/greenpeace/planet4-master-theme/pull/2225**

Add check for Media block

---

classes/rest/class-published.php

Ref: https://jira.greenpeace.org/browse/PLANET-7415
Cf. https://github.com/greenpeace/planet4-master-theme/pull/2208

PLANET-7415: Allow API query for P4 action type

---

classes/blocks/class-timeline.php

Ref. https://jira.greenpeace.org/browse/PLANET-7290
Move the Timeline block to master-theme

PLANET-7290 Make sure Timeline block is not registered twice

---

classes/class-loader.php
planet4-gutenberg-blocks.php

See [PLANET-7304](https://jira.greenpeace.org/browse/PLANET-7304)
We need this check to make sure we don't load assets twice, see comment [here](https://github.com/greenpeace/planet4-master-theme/pull/2190#pullrequestreview-1979216923)
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2247

PLANET-7304 Move ENForm block to master theme

---

assets/src/BlockEditorValidation.js
tests/e2e/articles.spec.js
tests/e2e/carousel-header.spec.js
tests/e2e/columns-icons.spec.js
tests/e2e/columns-images.spec.js
tests/e2e/columns-no-image.spec.js
tests/e2e/columns-tasks.spec.js
tests/e2e/covers-campaign.spec.js
tests/e2e/covers-content.spec.js
tests/e2e/covers-take-action.spec.js
tests/e2e/editor-selector.spec.js
tests/e2e/enform.spec.js
tests/e2e/related-articles.spec.js
tests/e2e/split-two-columns.spec.js
tests/e2e/spreadsheet.spec.js
tests/e2e/take-action-boxout.spec.js
tests/e2e/tools/lib/columns.js
tests/e2e/tools/lib/editor.js
tests/e2e/tools/lib/post.js

See [PLANET-7344](https://jira.greenpeace.org/browse/PLANET-7344)
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2223
You should no longer be able to publish or update a Page/Post/Action without setting a featured image or adding an image in the content.

PLANET-7344 Make featured image mandatory for publishing

---

classes/class-loader.php
composer.json
planet4-gutenberg-blocks.php

Ref: https://jira.greenpeace.org/browse/PLANET-7390
Requires: https://github.com/greenpeace/planet4-base/pull/291
Requires: https://github.com/greenpeace/planet4-master-theme/pull/2228
- clarify autoload logic
- remove required plugins check
- _planet4-develop_ branch for tests: `update/timber-composer-7390`
- fully deployed on [test-leda](https://www-dev.greenpeace.org/test-leda/)

PLANET-7390: Use Timber as composer package

---

assets/src/block-templates/highlighted-cta/template.js

Ref: https://jira.greenpeace.org/browse/PLANET-7508
Modify its template, by changing columns to group for a better consistency.
[Here is its related theme's PR](https://github.com/greenpeace/planet4-master-theme/pull/2275)
[Demo page](https://www-dev.greenpeace.org/test-venus/highlighted-cta-demo-page/). Currently using the venus dev instance (manually assigned) to test both repos.

PLANET-7508: Modify Highlighted CTA block pattern template

---

tests/e2e/split-two-columns.spec.js
tests/e2e/tools/lib/editor.js

Similar to https://github.com/greenpeace/planet4-master-theme/pull/2289

Fix panel editor spec

---

assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
assets/src/blocks/CarouselHeader/EditableBackground.js
classes/blocks/class-carouselheader.php

Ref: https://github.com/greenpeace/planet4-master-theme/pull/2282

PLANET-7263 Media Archive: add in editor option for P4 blocks

---

classes/rest/class-rest-api.php

Ref https://jira.greenpeace.org/browse/PLANET-7380

PLANET-7380 Remove Campaigns theme customizer endpoints

---

assets/src/blocks/ShareButtons/ShareButtonsFrontend.js
assets/src/components/ShareButtons/ShareButtons.js
public/js/social_media_cards.js
templates/blocks/social_media_cards.twig

See [Slack](https://greenpeace.slack.com/archives/C0151L0KKNX/p1716900694930299)
X made this change since tweets are now called posts. As far as I understood no other changes are necessary?
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2296

Change tweet to post

---

assets/src/blocks/Submenu/SubmenuEditor.js

Ref: https://jira.greenpeace.org/browse/PLANET-7496
This PR updates texts of the Submenu Block's settings area.

PLANET-7496: Backend Text Changes on Submenu Block

---

.circleci/config.yml
composer.json
composer.lock

See [PLANET-7389](https://jira.greenpeace.org/browse/PLANET-7389)
It seems no fixes were needed.
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2341

PLANET-7389 Add PHP8.3 tests job

---

assets/src/blocks/Happypoint/HappyPointConstants.js
assets/src/blocks/Happypoint/HappypointBlock.js
assets/src/blocks/Happypoint/HappypointEditor.js
assets/src/blocks/Happypoint/HappypointFrontend.js
assets/src/blocks/Happypoint/OverrideFormHelp.js
assets/src/blocks/Happypoint/deprecated/HappyPointV1.js
assets/src/blocks/Happypoint/useHappypointImageData.js
assets/src/blocks/Happypoint/useHubspotEmbedCode.js
assets/src/editorIndex.js
assets/src/frontendIndex.js
assets/src/styles/blocks.scss
assets/src/styles/blocks/Happypoint.scss
assets/src/styles/blocks/HappypointEditor.scss
assets/src/styles/editorStyle.scss
classes/blocks/class-happypoint.php
classes/class-loader.php
classes/rest/class-rest-api.php

This reverts commit c015ea344ae13bcd45ef049c2a2646f60d74f010.
Just to unblock the release while we figure out the issue.
- Make sure that the Happy Point block is not affected and it's working as expected

Revert "PLANET-7611: Remove the Happy Point block (#1246)"
