greenpeace/planet4-plugin-gutenberg-blocks

- planet4-gutenberg-blocks.php
This fixes a bug reported by Andrada in the blocks selector, all blocks disappeared: 
This is how it should look: 
The problem was that the callback for `allowed_block_types` must return explicitly which blocks should be included, including the default WP ones explicitly. The `my_plugin_allowed_block_types` function was returning just our blocks.
I used a list Stefan curated for the GPCH Gutenberg blocks and copied his comments too, which helps in knowing why a block has been disabled.
> [NO TICKET]: Fix allowed blocks list.

- classes/blocks/class-articles.php
Ref: https://jira.greenpeace.org/browse/PLANET-4009
The current post was not being excluded from the Articles list when the block is rendered inside posts. 
Note: this change fixes the issue, however the Articles block is rendered inside Posts using a shortcode in the master theme, we may want to revisit that in the near future.
> PLANET-4009: Articles: showing the current post too

- classes/blocks/class-articles.php
Use default articles title and read more button text values for articles block if their values are empty.
Removed also setting the default values in register_block_type, because they add no value if wp_block_type is not used.
https://developer.wordpress.org/reference/classes/wp_block_type/
> PLANET-4013 Use default articles title and read more button text values

- .gitignore
- p4-webpack-config.js
- package-lock.json
- package.json
- react-blocks/build/editorIndex.deps.json
- react-blocks/build/frontendIndex.deps.json
Note: I had to use both the [fix style-only entries](https://github.com/fqborges/webpack-fix-style-only-entries) and this [simple file remover](https://www.npmjs.com/package/remove-files-webpack-plugin) because the first one only removes the `.js` and `.js.map` files generated for style entry points.
As for the `.deps.json` files, I think they are generated by this plugin: 
https://www.npmjs.com/package/@wordpress/dependency-extraction-webpack-plugin
Which is a dependency of `@wordpress/scripts`, so, to remove those two extra assets, I had to use the file remover plugin.
> [NO TICKET]: Add plugins to remove unneeded files and add them to gitignore.

- classes/blocks/class-columns.php
- classes/blocks/class-gallery.php
- classes/blocks/class-happypoint.php
- classes/blocks/class-media.php
- classes/blocks/class-splittwocolumns.php
- classes/blocks/class-submenu.php
The `add_shortcode()` function was missing in below blocks,
- Columns block
- Gallery block
- Happy point block
- Media block
- Split_two_columns block
- Submenu block
> [No Ticket] Add missing 'add_shortcode()' function in blocks

- classes/class-loader.php
When adding a new post and clicking on + icon to add blocks
> Fix typo error and move Planet4 Blocks menu entry into 3rd row.

- planet4-gutenberg-blocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-4217
There is a related (yet non-blocking) child theme PR to add a second filter for NROs to whitelist/blacklist blocks:
https://github.com/greenpeace/planet4-child-theme/pull/7
> PLANET-4217: Add second filter for whitelist of Gutenberg blocks

- planet4-gutenberg-blocks.php
- removed below blocks from whitelist:
Animoto
Cloudup
CollegeHumor
Cover
Hulu
ReverbNation
Screencast
SmugMug
WordPress.tv
Tumblr
Won't work until this [PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/58/files) has been merged in.
> PLANET-4263 Remove specific embed blocks from Gutenberg whitelist

- classes/blocks/class-articles.php
Wp query expects an array of tag ids here:
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/fix-articles-exclude-id/classes/blocks/class-articles.php#L418-L421
> [No ticket] Fix articles block for exclude post id

- classes/blocks/class-carouselheader.php
Carousel header - Set full-width-classic as the default style to match old blocks behavior
> PLANET-4304 Carousel header - fix default style

- templates/blocks/campaign_thumbnail.twig
- templates/blocks/old_covers.twig
Fix covers view attribute in campaign thumbnail and old covers templates
based on this mapping
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/develop/classes/command/converters/class-conversion-functions.php#L146-L152
> PLANET-4290 Fix covers view attribute in covers templates

- classes/blocks/class-articles.php
[JIRA 4298](https://jira.greenpeace.org/browse/PLANET-4298)
This issue is not related to transforms script. If tags does not exists the Gutenberg  articles block was showing empty block. To fix this issue I added a check on tag id.
> PLANET-4298 Articles block - Add check on tag exist

- classes/blocks/class-covers.php
- public/js/pubslider.js
This script was present in the old plugin but missing in the new one. Refer to the comments in the ticket for background.
Ref: https://jira.greenpeace.org/browse/PLANET-4301
> PLANET-4301: Covers - content block: wrong column width when less than 4 columns

- assets/src/styles/blocks/ColumnsEditor.scss
- classes/blocks/class-counter.php
(119:20) - /home/circleci/project/classes/blocks/class-counter.php
`Equals sign not aligned with surrounding assignments; expected 11 spaces but found 1 space`
```
stylelint $HOME/project/assets/src/styles/**/*.scss
assets/src/styles/blocks/ColumnsEditor.scss
6:1   ✖  Expected empty line before rule   rule-empty-line-before
11:21  ✖  Expected "#FFF" to be "#fff"      color-hex-case        
22:1   ✖  Expected empty line before rule   rule-empty-line-before
Exited with code 2
```
ref. https://circleci.com/gh/greenpeace/planet4-plugin-gutenberg-blocks/1242?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> PLANET-4182 Fix PHPCS errors

- classes/controller/menu/class-blocks-usage-controller.php
- classes/controller/menu/class-controller.php
- classes/controller/menu/class-reusable-blocks-controller.php
- classes/controller/menu/class-settings-controller.php
- planet4-gutenberg-blocks.php
I initially started for a broader reworking of the report page, so I started with a cleanup commit to remove some boilerplate code. The scope of the ticket then narrowed to only include making the report also include NRO developed blocks. However it makes sense to already include the cleanup commits as it only removes things (+ small change to use ::class instead of string class names). I kept both commits separate as they do different things.
> Planet 4438 Add NRO custom blocks

- planet4-gutenberg-blocks.php
This is opened against master, so we can quickly get it to production. I'll cherry-pick it on develop afterwards.
> Restrict Social Share block to Campaigns

- assets/src/styles/blocks/Gallery_carousel.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4516
Note: This simple fix addresses the main issues. You can run into scenarios that produce zoomed images, if you combine bad image sizes with weird aspect ratios, but those would be edge cases.
> PLANET-4516: Gallery+Carousel Header block: Images get massively zoomed in for no reason

- classes/blocks/class-socialmediacards.php
- public/js/social_media_cards.js
- templates/blocks/social_media_cards.twig
* Add a title on all buttons (not in ticket but discussed with Will and can be included here)
https://jira.greenpeace.org/browse/PLANET-4538
* Force SocialMediaCards image download button to always download instead of showing in browser
https://jira.greenpeace.org/browse/PLANET-4539
* Make tweet open in popup instead of new tab
* keep the original href as fallback, though it's not used by js
* Url encode to make hashtags work
> PLANET-4538 Force SocialMediaCards images to download and PLANET-4539 improve twitter

- templates/blocks/columns.twig
This fixes the Homepage errors for these reports: 
https://4774-150238919-gh.circle-artifacts.com/0/app/backstop_data/html_report/index.html
Ref: https://jira.greenpeace.org/browse/PLANET-4399
> PLANET-4399: CPP - Investigate primary and secondary button usage across blocks

- .circleci/config.yml
- .gitignore
- classes/blocks/class-base-block.php
- classes/controller/menu/class-controller.php
- composer.json
- composer.lock
- phpcs.xml
- tests/p4-unittestcase.php
Fix unit tests docker to point to docker hub.
Clean up .gititnore and removed OS and IDE specific files. These should live in local exclusion config.
Update composer dependencies. WP Coding Standards 2.2 are throwing an error for Short Syntax Arrays, but since we use everywhere added a phpcs config to exclude it and instead raise an error for Long Syntax.
> Add CI configuration for running tests

- assets/src/blocks/SocialMediaCards/SocialMediaCards.js
- assets/src/blocks/SocialMediaCards/SocialMediaCardsBlock.js
- classes/blocks/class-socialmediacards.php
- planet4-gutenberg-blocks.php
- public/js/social_media_cards.js
- templates/blocks/social_media_cards.twig
* Facebook share now opens in new tab, providing the
social_media_message as quoted text
* All SocialMediaCards code was initially copied from the Gallery
block as a starting point, however this was never cleaned up. This
removes some of it, except for the focal points, which don't work but it
is not clear whether it should be removed or the functionality should be
implemented.
* Remove the conversion from shortcode.
* Prevent notices for the link_new_tab fix
> PLANET-4540 Fix facebook share and remove unused code

- assets/src/styles/blocks/Gallery_carousel.scss
This was being affected by this rule: 
https://github.com/greenpeace/planet4-master-theme/blob/develop/assets/src/scss/pages/post/_article-content.scss#L49
I increased the specificity of the selectors for the Gallery and set the padding to 0.
Ref: https://jira.greenpeace.org/browse/PLANET-4567
> PLANET-4567: #408845: Gallery block: navigation indicators are elongated

- classes/blocks/class-articles.php
- classes/blocks/class-happypoint.php
- classes/blocks/class-media.php
- classes/blocks/class-splittwocolumns.php
[JIRA 4510](https://jira.greenpeace.org/browse/PLANET-4510)
Fixed PHP Notices -
`Warning: array_filter() expects parameter 1 to be array, string given in /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks/classes/blocks/class-articles.php on line 388`
`Notice: Undefined index: background in /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks/classes/blocks/class-happypoint.php on line 36`
`Notice: Undefined index: video_title in /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks/classes/blocks/class-media.php on line 128`
`Notice: Trying to get property 'name' of non-object in /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks/classes/blocks/class-splittwocolumns.php on line 152`
> PLANET-4510 Fix PHP notices

- assets/src/styles/blocks/core-overrides/Spacer.scss
- assets/src/styles/style.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4602
This is a patch to fix the above issue, I'll create a follow-up ticket to restore the `clear: both` rule added by WP 5.3.2 (I guess it makes sense on a spacer...), so we can remove this override, and maybe find a different way of positioning the boxout.
> PLANET-4602: Spacer element in blogs doesn't work correctly

- assets/src/styles/blocks/SubmenuEditor.scss
- assets/src/styles/blocks/core-overrides/Image.scss
Some of the customizations for the image captions broke image
alignment options.
* Remove the table display on figure, this should be on the outer
element.
* Use `position: relative` on figure so that figcaption has right width.
* Clear the submenu block in the editor.
> PLANET-4441 Fix broken image alignment

- assets/src/blocks/Gallery/GalleryBlock.js
This was happening because of a focal point missing in one of the images (the focal points array and the image ids array didn't match), which I couldn't reproduce by clicking, only using the code editor. It looks like it's an edge case, but I guess it makes sense to prepare for it.
Ref: https://jira.greenpeace.org/browse/PLANET-4650
> PLANET-4650: JS Error on Gallery - Slider renders block unusable

- assets/src/styles/blocks/core-overrides/Image.scss
This fixes an inconsistency we found, `figure` may have a wrapper `div` or not.
Ref: https://jira.greenpeace.org/browse/PLANET-4441
> PLANET-4441: Image caption alignment fixes

- public/js/submenu.js
When an external icon was on the link then the text of the heading would
have whitespace at the end, so trimming is needed to make the script
match it up with the submenu link text.
ref: https://jira.greenpeace.org/browse/PLANET-4658
> PLANET-4658 trim heading text so it matches menu item

- assets/src/blocks/Articles/Articles.js
- assets/src/blocks/Articles/ArticlesBlock.js
- classes/rest/class-rest-api.php
- planet4-gutenberg-blocks.php
* Add an endpoint that just returns all published posts and their ids.
If wpml is active this endpoint requires the language of the posts.
* Use that endpoint instead of the `/wp/v2/posts`, which was a huge
overkill in response time and payload size for this use case.
* Fetch the suggestions once when the override field is focused for the
first time, instead of on every input. There is absolutely no need to
perform an API request as this behavior is already handled by the
FormToken component if you provide it with all the options.
> PLANET-4439 Populate Articles override suggestions with all posts

- assets/src/styles/editorOverrides.scss
The clear button cannot be shown without giving the ability to enter any
color. Luckily the button is only hidden and still works, so unhiding is
sufficient. This is done globally as all of our color pickers should be
clearable.
> PLANET-4666 Force show clear button on cmb color picker.

- assets/src/blocks/Carouselheader/FullWidthCarouselHeader.js
- classes/blocks/class-carouselheader.php
- templates/blocks/carousel_header_full-width-classic.twig
- templates/blocks/gallery.twig
- templates/blocks/tease-articles.twig
- templates/teasers/tease-articles.twig
Ref: https://jira.greenpeace.org/browse/PLANET-4532
Notes: 
- I included a vanilla JS lazy-loading lib, from a CDN, here and in the `master-theme`. This is what we currently do with things like jQuery. This same lib could be installed using `npm install`, but I couldn't find a way to install it only on the `master-theme`, and get the plugin's JS to load after the `master-theme`'s JS. We can address that separately in the future.
- These changes basically seem to improve some critical path metrics: DOM Content Loaded, First Paint, First meaningful paint..., running on my local instance, these are the results on `develop`:
Same audit in this branch:
These results can vary a little, as the total number of milliseconds shown below (which are bigger in this branch), but it looks like the FMP …
> PLANET-4532: Perf: Investigate lazy-loading solution across P4 (incl. all browsers)

- assets/src/components/ColorPaletteControl/ColorPaletteControl.js
- assets/src/components/PostMeta/withPostMeta.js
- assets/src/components/Sidebar/CampaignSidebar.js
- assets/src/components/fromThemeOptions/fromThemeOptions.js
- assets/src/connectCssVariables.js
- assets/src/editorIndex.js
- assets/src/setupCustomSidebar.js
- assets/src/styles/editorOverrides.scss
- assets/src/styles/editorStyle.scss
- classes/class-loader.php
This requires the following changes in master-theme: https://github.com/greenpeace/planet4-master-theme/pull/984
* Register a sidebar with campaign settings.
* Add HOC function for creating post-meta controls.
* Use new meta field without underscore for campaign_page_template, as
the underscore prevents API usage. In usages fall back to old field if
the new doesn't exist yet.
* Add ColorPaletteControl that wraps around ColorPalette and functions
similarly to other input controls. This is currently missing in
wordpress, but should it be added there then this can go.
> PLANET-4603 Introduce campaign sidebar

- assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
- classes/class-loader.php
- planet4-gutenberg-blocks.php
Adding block to BETA section required changing the category in the '*Block.js' file. So if we want to move it back to the non-beta section we have to change it there.
Ref: https://jira.greenpeace.org/browse/PLANET-4698
and also: https://jira.greenpeace.org/browse/PLANET-4699
> PLANET-4698 Add spreadsheet to BETA section in pages and posts

- assets/src/blocks/Gallery/GalleryBlock.js
- classes/blocks/class-gallery.php
There was a bug when editing a page via the Code Editor, reported by Poland and Netherlands on Skype, causing the Carousel Gallery to show only one image, the rest is blank (see: https://www.greenpeace.org/poland/aktualnosci/27595/prezydencie-trzaskowski-pila-nie-ochronisz-klimatu/).
Steps to reproduce:
- Create a new page
- Add a Gallery Block with 3 images
- Switch to the Code Editor
- Hit "Publish" or "Update" to save the page without leaving the Code Editor
- Refresh
---> You'll see the "image_data" attributes are lost
Please test! I think this solves the issue.
> [No issue]: Fix image_data datatype in Gallery blocks

- classes/class-loader.php
* The categories were put first by replacing an index in the incoming
`$categories` array, however that is not needed as we can put
our categories first just by passing them as the first array to
`array_merge`.
> PLANET-4698 Don't overwrite core category

- assets/src/styles/blocks/Articles.scss
The opacity declaration removed was vestigial from an old lazy loading feature in the Articles block.
Ref: https://jira.greenpeace.org/browse/PLANET-4753
> PLANET-4753: [Philippines] Featured image not showing in Latest Updates

- assets/src/styles/blocks/Columns.scss
Fix for an issue in GPI:
I can't actually test it because the Gutenberg editor just crashed environment, it's timing out.
> Hotfix: Apply color only on primary button, not secondary

- assets/src/styles/editorOverrides.scss
Our radio labels in the sidebar are being affected by some generic styles (e.g.: Bootstrap's reboot, and some styles from WP that look a bit unbalanced). So I added an override to fix their alignment.
Before:
After:
> [No issue]: Fix radio label alignment

- assets/src/components/Sidebar/CampaignSidebar.js
- assets/src/components/withDefaultLabel/withDefaultLabel.js
UAT Passed.
This adds another element to the `compose` chain for `Select`'s to add a "(default)" label to the default option.
Ref: https://jira.greenpeace.org/browse/PLANET-4750
Master Theme part: https://github.com/greenpeace/planet4-master-theme/pull/1030
> PLANET-4750: Campaigns customiser - Adjust Header primary font options

- assets/src/components/PostMeta/withPostMeta.js
- assets/src/editorIndex.js
- assets/src/saveMetaToPreview.js
- assets/src/setupCustomSidebar.js
- classes/rest/class-rest-api.php
* Add custom endpoint that saves meta for the autosave revision of the current
post and user.
* On change of a withPostMeta component send a request to that endpoint.
> PLANET-3427 Save any changes to post meta to the autosave.

- assets/src/styles/blocks/Spreadsheet.scss
Adjusting vertical space for the Spreadsheet as shown in the ticket.
Note: this is based in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/204
Ref: https://jira.greenpeace.org/browse/PLANET-4767
> PLANET-4767: Spreadsheet block: Adjust vertical spacing

- assets/src/styles/blocks/core-overrides/Image.scss
We already have some typographic rules in place for the blue overlay caption style. This fix the same rules to the medium styles that comes with WP.
Ref: https://jira.greenpeace.org/browse/PLANET-4680
> PLANET-4680 Apply Image block typographic rules to all caption styles

- assets/src/styles/blocks/Columns.scss
- templates/blocks/columns.twig
Flex display and justify-content:space-between on the column wrapper,
combined with flex-grow: 1 on only the p tag results in only the p tag
growing to provide the additional spacing and the buttons lining up
neatly at the bottom of the wrapper.
This might need some additional css changes elsewhere, though until now I haven't seen anything breaking because of it.
> PLANET-4710 Use flexbox to align column CTAs

- assets/src/styles/blocks/core-overrides/BlockSpacing.scss
- assets/src/styles/editorStyle.scss
- assets/src/styles/style.scss
UAT Passed.
Ref: https://jira.greenpeace.org/browse/PLANET-4325
> PLANET-4325: Apply P4 Standard vertical spacing to all native Gutenberg blocks across content types

- assets/src/styles/editorOverrides.scss
There is already a place for this config in the settings and there is
little value in having it at the bottom of each post edit page.
Furthermore these settings don't get saved by saving the post, instead
they have their own button which is small and not very noticeable in the
bottom right corner.
> PLANET-4838 Hide confusing WPML global settings on post edit page.

- planet4-gutenberg-blocks.php
Added check to see if second argument of array_merge is not empty, only then will the merge be called, otherwise return only the wordpress blocks.
Ref: https://jira.greenpeace.org/browse/PLANET-4895
> PLANET-4895 fix argument not array waring

- assets/src/blocks/Carouselheader/CarouselHeader.js
- assets/src/blocks/Carouselheader/CarouselHeaderImage.js
- assets/src/blocks/Carouselheader/CarouselHeaderSlide.js
- assets/src/styles/blocks/CarouselHeaderEditor.scss
- assets/src/styles/components/CharacterCounter.scss
- assets/src/styles/editorOverrides.scss
After tinkering a bit with the block, I realized this editing experience is totally different from the Gallery block. I restored the Delete Image button, made it more prominent in the UI and did a few CSS changes to make the editing experience look more polished. 
There were also some React warnings to control (details in the commit), and even an error preventing to create a new CarouselHeader (attempting to mutate `this.refs` directly). This could probably use a few refactors, but I guess that should be part of the WYSIWYG epic. 
As for this ticket, the issue is addressed and the editing experience looks much better now. 
Ref: https://jira.greenpeace.org/browse/PLANET-4705
> PLANET-4705: Header Carousel: icon to delete image is not shown

- admin/js/editor.js
- assets/src/BlockFilters.js
- assets/src/components/p4_button/edit.js
- classes/class-loader.php
- planet4-gutenberg-blocks.php
The button block is updated in WP-5.4 release with "buttons" block. The new buttons block offers additional options to editors -
- Allow to set custom button border radius (finding a way to disable this option...)
- New button style options(we disabled it and allow P4 buttons styles only)
- Color gradient option for button background
- Toggle option to "Open in new tab" (this options seems useful)
Task -
- Disable border radius option
- Allow only the colours mentioned in Will's comment for colour palette( [JIRA 4924](https://jira.greenpeace.org/browse/PLANET-4924) )
- Ensure that it still follows our custom styles
- Whitelist buttons block
- Disable the gradient presets & custom gradients
The WP core buttons block,wont have a build in setting to disable the  border radius option and …
> PLANET-4924 Re-enable the native buttons block

- classes/blocks/class-articles.php
- public/js/load_more.js
- templates/blocks/articles.twig
https://jira.greenpeace.org/browse/PLANET-4862
* The nonce-verification offers no additional security, as a new nonce
can be fetched from any page with an articles block without
authentication. Possibly it could also cause the load more button to
stop working.
* Remove some event handlers in search.js that are attached to classes
which don't occur in the code anymore.
> PLANET-4862 Remove nonce for Articles load more

- assets/src/blocks/Gallery/Gallery.js
The deleted line was removing the "Select Gallery Images" placeholder from the Gallery after the user selected a few images.
Ref: https://jira.greenpeace.org/browse/PLANET-4946
> PLANET-4946: Edit selection in Gallery Block

- assets/src/styles/blocks.scss
- assets/src/styles/blocks/Spreadsheet.scss
- assets/src/styles/editorStyle.scss
- assets/src/styles/style.scss
- classes/blocks/class-spreadsheet.php
- public/js/spreadsheet.js
- templates/blocks/spreadsheet.twig
* Apply sticky positioning to the header.
* Apply a max height for different screen sizes.
* Cache the sheet response for 5 minutes.
* Use `<thead>` and `<tbody>`. For now this assumes the first row is
always a header, we might want to make that configurable.
* Remove the default sort button.
* Fix alternating colors when the rows are filtered by using a different
technique. Instead of hiding the elements, remove them and add them back
when needed.
* Fix sorting not applied after filtering.
> PLANET-4913 Fix spreadsheet block size and scrolling

- planet4-gutenberg-blocks.php
Not sure how this got removed, but it should be whitelisted for all post types.
This also had some other wrong blocks whitelisted there (split-two-columns and submenu), one wrong name (socialshare instead of social-media-cards) and one missing sub-pages.
Not sure how this happened. It seems like something got wrong in a rebase.
> PLANET-5018 Re-enable spreadsheet block on Campaigns

- assets/src/components/ColorPaletteControl/ColorPaletteControl.js
- assets/src/components/PostMeta/withPostMeta.js
- assets/src/components/Sidebar/CampaignSidebar.js
- assets/src/components/fromThemeOptions/fromThemeOptions.js
- assets/src/components/withDefaultLabel/withDefaultLabel.js
- assets/src/editorIndex.js
- assets/src/saveMetaToPreview.js
- assets/src/styles/blocks/Articles.scss
- assets/src/styles/blocks/CarouselHeader.scss
- assets/src/styles/blocks/CarouselHeader_full_width_classic.scss
- assets/src/styles/blocks/Columns.scss
- assets/src/styles/blocks/Covers/ContentCovers.scss
- assets/src/styles/blocks/Gallery_carousel.scss
- assets/src/styles/blocks/Happypoint.scss
- assets/src/styles/blocks/SocialMediaCards.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4919
This check was not working for Palette options, because the value is stored as `color`, and not as `value` in the `options` array (check the comment a few lines above):
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/develop/assets/src/components/PostMeta/withPostMeta.js#L56
Master theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1053
> PLANET-4919: Ensure automatically selected options are correctly shown in the Preview when switching themes

- assets/src/BlockEditorValidation.js
- assets/src/editorIndex.js
- assets/src/styles/editorOverrides.scss
- classes/class-loader.php
[JIRA 4878](https://jira.greenpeace.org/browse/PLANET-4878)
Added a [PluginPrePublishPanel](https://developer.wordpress.org/block-editor/developers/slotfills/plugin-pre-publish-panel/) panel with validation message of mandatory fields.
> PLANET-4878 Add 'pre-publish-checklist' panel on click of publish button

- assets/src/styles/blocks/Covers/ContentCovers.scss
- applied rule to only show two content covers small screens.
- adjusted sizing of covers to match the new rule
Ref: https://jira.greenpeace.org/browse/PLANET-4853
> PLANET-4853 Planet 4 Bug Report: Covers block: Rows displayed shows all on mobile

- assets/src/blocks/CssVariablesAttribute.js
- assets/src/blocks/Spreadsheet/Spreadsheet.js
- assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
- classes/blocks/class-base-block.php
- classes/blocks/class-spreadsheet.php
- templates/blocks/css_variables.twig
- templates/blocks/spreadsheet.twig
Adds the backend support for using css variables inside blocks. Also setup the Spreadsheet block edit component to put the color into the attribute that is used to store the variables.
> Planet 5037 add css variables attribute

- classes/command/class-controller.php
- classes/command/class-duplicated-postmeta.php
- classes/controller/menu/class-postmeta-check-controller.php
- planet4-gutenberg-blocks.php
- templates/duplicate-postmeta-report.twig
[JIRA 4774](https://jira.greenpeace.org/browse/PLANET-4774)
- Add duplicate postmeta report in WP admin under "Blocks" menu
- The admin menu is visible only to 'administrator' user
- Add "Duplicate Postmeta" button on top of report to delete all duplicate postmeta records
- Add WP CLI command  to clean duplicate postmeta (`wp p4-gblocks remove_duplicate_postmeta`)
eg. https://k8s.p4.greenpeace.org/sagardev/wp-admin/admin.php?page=postmeta_report
> PLANET-4774 Add Duplicate postmeta report & WP CLI command to clean duplicate postmeta

- classes/command/class-controller.php
- classes/command/class-duplicated-postmeta.php
- classes/controller/menu/class-postmeta-check-controller.php
- templates/duplicate-postmeta-report.twig
- Add new CLI cmd to print duplicate postmeta key counts (`wp p4-gblocks print_duplicate_postmeta`)
- On execution of `wp p4-gblocks remove_duplicate_postmeta` cmd print duplicate postmeta keys before delete. 
- Update Admin duplicate postmeta report with `meta_key` and counts
> PLANET-5078 Print duplicate metakey counts in CLI cmd before deleting

- assets/src/BlockFilters.js
- assets/src/components/p4_table/edit.js
- assets/src/components/p4_table/state.js
- assets/src/styles/blocks.scss
- assets/src/styles/blocks/Spreadsheet.scss
- assets/src/styles/blocks/core-overrides/Table.scss
- package-lock.json
See https://jira.greenpeace.org/browse/PLANET-5058
We want to offer the same color options for the Table block as we do for the Spreadsheet block. The only difference is that tables also have a footer, which requires an additional color. This PR takes care of several things:
- Move table background colors to an override file, also add white border to table rows when no stripes ("regular" style)
- Create a custom `edit.js` file for the table block, based on a copy of [the original](https://github.com/WordPress/gutenberg/blob/7dd6c58c3c6e17c85423fff7a666eab29d749689/packages/block-library/src/table/edit.js)
- Add a copy of [the original](https://github.com/WordPress/gutenberg/blob/7dd6c58c3c6e17c85423fff7a666eab29d749689/packages/block-library/src/table/state.js) `state.js` file for table …
> Planet 5058 - Table background colors

- assets/src/blocks/Takeactionboxout/TakeactionboxoutBlock.js
[JIRA 5062](https://jira.greenpeace.org/browse/PLANET-5062)
- The issue was the `take_action_page` passed as string ({"take_action_page":"23439"} ) where as the field is defined as integer in backend and Gutenberg.
> PLANET-5062 Fix TAB 'take_action_page' datatype

- assets/src/styles/blocks/Covers/TakeActionCovers.scss
- templates/blocks/old_covers.twig
- templates/blocks/take_action_boxout.twig
This PR is to try to use a link overlay to make the whole Take Action card clickable using this trick: https://codepen.io/pwkip/pen/oGMZjb (see the last comment by @comzeradd on [this PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/293) for more details).
One side effect of this method is that clickable elements in the card that need UI effects (background change, underline, etc) need to be`<a>` tags, otherwise the interaction is gone. Those elements are the tags, the title and the CTA.
> Planet 5060 - Use overlay to make whole Take Action card clickable

- assets/src/styles/blocks/Covers/TakeActionCovers.scss
- templates/blocks/old_covers.twig
- templates/blocks/take_action_boxout.twig
This PR takes care of the changes for both the Take Action card (https://jira.greenpeace.org/browse/PLANET-5060) and the Take Action boxout (https://jira.greenpeace.org/browse/PLANET-5126):
- Hide CTA in passive state, show it only on rollover
- Make whole card clickable (instead of just the CTA), adjust cursor to pointer
- Underline heading on rollover
> Planet 5060 - Simplify passive state of Take Action cards

- assets/src/blocks/HighlightMatches.js
- assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
I inadvertently committed these lines while rebasing the branch, I was testing a suggestion from the PR review, but using `trim()` in the `setState()` call actually prevents you from typing any spaces in the controlled search input, so this is to restore the lines to the way they originally were.
Please merge asap!
> PLANET-5017 Fix: Restore trim() on HighlightMatches and remove it from setState

- classes/blocks/class-articles.php
- classes/blocks/class-carouselheader.php
- classes/blocks/class-columns.php
- classes/blocks/class-cookies.php
- classes/blocks/class-counter.php
- classes/blocks/class-covers.php
- classes/blocks/class-happypoint.php
- classes/blocks/class-media.php
- classes/blocks/class-socialmediacards.php
- classes/blocks/class-submenu.php
- classes/class-loader.php
Ref: https://jira.greenpeace.org/browse/PLANET-5186
Script version is not automatically updated when we make changes, which leads to cache problems if we forget it.
Switch from hardcoded version to `filectime`.
Versions were found with regex `[0-9]{1,2}\.[0-9]{1,2}`, and by looking at `wp_enqueue_style` and `wp_enqueue_script` usage.
I took the liberty to regroup those calls in a static function, to limit the number of parameters used. If you feel like it's too big of a change and I went too far, I can roll this back :)
On the editor side while editing a page, in the network calls or in html source, we should see a call to `planet4-plugin-gutenberg-blocks/assets/build/editorIndex.js?ver=1591791157` with a timestamp as version number. You can filter by `ver=159` to see those calls.  
No …
> PLANET-5186: Switch script version to filectime

- assets/src/styles/blocks/Articles.scss
- assets/src/styles/blocks/Covers/CampaignCovers.scss
- assets/src/styles/blocks/Covers/TakeActionCovers.scss
- assets/src/styles/campaigns/components/_campaign_covers.scss
- assets/src/styles/editorOverrides.scss
This is a non-exhaustive list of added variables that child-themes could use for easier customisation of Planet4 (see [PLANET-5114](https://jira.greenpeace.org/browse/PLANET-5114) for more details). The ones listed below are already in the code and could be used right away, but maybe they need to be renamed?
- Navigation bar background color: [--campaign_nav_color](https://github.com/greenpeace/planet4-styleguide/blob/master/src/layout/_navbar.scss#L83)
- Footer background color: [--footer_color](https://github.com/greenpeace/planet4-styleguide/blob/master/src/layout/_footer.scss#L47)
- Footer links color: [--footer_links_color](https://github.com/greenpeace/planet4-styleguide/blob/master/src/layout/_footer.scss#L68)
- Spreadsheet header background color: …
> PLANET-5114 Add css variables for easier child-theme customisation

- templates/blocks/columns.twig
- templates/blocks/columns_tasks.twig
Related to [JIRA 5199](https://jira.greenpeace.org/browse/PLANET-5199)
Task -
- Add data attributes on columns block title, image and CTA link/buttons as per the JIRA ticket.
Testing -
- Create a [new page](https://k8s.p4.greenpeace.org/test-pluto/wp-admin/post-new.php?post_type=page) with all columns styles and check the data attributes by inspecting the column title, image and CTA html tags.
- The attributes and their values should be as per JIRA ticket details
Note: On Task column block please  check for mobile screen view. also test column block on campaign page, the column title has no anchor tag on campaign page.
> PLANET-5199 Add data attributes on Columns Block

- assets/src/components/PostMeta/withPostMeta.js
- assets/src/components/fromThemeOptions/fromThemeOptions.js
- assets/src/components/withDefaultLabel/withDefaultLabel.js
This is just to reduce the number of anonymous classes in the React Devtools Component debugger.
It's following this recommendation from Facebook: 
https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging
It turns this:
Into this:
> [No ticket]: Add descriptive names for the React Component debugger

- assets/src/blocks/ENForm/ENForm.js
- Add `<Br>` tag before the select goal field (it will help to highlight goal as a separate field)
- Add `--- Select Goal ---` as a Default option in goals dropdown
- Add `"Select Goal" field is required!` validation
> PLANET-5293 EN Form Block: Make "Goal" field mandatory

- templates/blocks/columns.twig
Ref: https://jira.greenpeace.org/browse/PLANET-5305
Following https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/313 , a missing opening tag `h3` causes Column titles without links to display as regular text.  
The fix adds an opening tag in the default case (no link, no campaign)
Add a column block to a page, one of the column title has to be without link (field `Button/CtA Link` empty).
Before fix:
After fix:
> PLANET-5305: Column block: non-linked Header styles broken

- templates/blocks/carousel_header_full-width-classic.twig
Ref. 
[JIRA 5142](https://jira.greenpeace.org/browse/PLANET-5142)
https://developers.cloudflare.com/images/responsive
~- Add a twig filter which returns cloudflare ready(cloudflare optimized) image url~
Note: The twig filter code moved to [master theme](https://github.com/greenpeace/planet4-master-theme/pull/1139).
> PLANET-5142 Add twig filter(cf_img_url) on carousal header image urls

- assets/src/blocks/frontendRendered.js
After chatting with Dirk about the implementation of the frontend rendering, it seemed like a good idea to make this change. Some shortcuts in JS syntax can be confusing (in this case, chaining two arrow functions).
So maybe using a function block and return is clearer to a newcomer.
> [No issue] Make the frontendRendered definition a bit more verbose.

- assets/src/styles/campaigns/themes/_theme_plastic.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5187
> The rounded buttons in the column blocks need white text not blue in the icon columns block in the https://www.greenpeace.org/international/campaign/single-use-ban-in-your-community/
Links in primary buttons have a rule for white color text (`plastics-button($background: $plastics-peach-darker, $foreground: white)` I guess ?), but a more precise one `.page-template a` (coming from https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/265) overrides it.  
The fix adds a new rule for `a.btn-primary` specifically. 
I feel like I should parameterize text color to use the same variable for text and link, but not sure if this is possible in a simple way <sub>my god when did frontend become so convoluted let me out 🔨 </sub>
- …
> PLANET-5187: Fix button link color in plastic theme

- classes/blocks/class-takeactionboxout.php
Related to [JIRA #5296](https://jira.greenpeace.org/browse/PLANET-5296) 
Fix -
- Add  'post_status' = 'publish' condition on selected TAB page
- Return empty array if no TAB page is active
- Fix `PHP Notice:  Undefined variable: tags`
Test -
- Add a new TA page
- add/edit post and select newly added TA page from "Take Action Page Selector" dropdown at bottom of post or add a "Take Action Boxout" block from P4 blocks with new TA page
- Check the new post on frontend, the TAB is visible as intended
- Now change the status of TA page to draft
- The TAB should no longer visible on post page
e.g. https://k8s.p4.greenpeace.org/test-venus/story/28509/fukushima-and-the-2020-olympics/
> PLANET-5296 Fix empty TA Card on Posts

- templates/blocks/enform/country_select.twig
- templates/blocks/enform/position_select.twig
Related to [PLANET-5276](https://jira.greenpeace.org/browse/PLANET-5276)
- Change the textdomain to `planet4-engagingnetworks` from `planet4-engagingnetworks-backend`
**Next step -**
- Once this PR merged, update the handbook Loco translate template for `Plugins >>  Planet4 - Gutenberg Blocks  >> Planet4 Engaging Networks plugin frontend (planet4-engagingnetworks)`
- Sync the updated new strings in `Arabic` language translation 
- Check with Fadi and add the translation of missing EN form frontend strings
- Wait for the next P4 release to check updated translation
> PLANET-5276 Update the proper textdomain value in EN form

- assets/src/styles/campaigns/themes/_theme_plastic.scss
The ticket requested these to be bold, although the previous style was font-weight 900 (extra bold). That extra bold came from the campaign sidebar settings, but somehow this rule got removed. I didn't add it back because it affects all headers.
> PLANET-5161 Make columns headers bold in platics

- classes/blocks/class-articles.php
* Otherwise older blocks that weren't saved with the block node in the
block content would not display until they are saved in the wywiwyg
version.
> PLANET-4801 Render block node in backend

- assets/src/blocks/Articles/ArticlesFrontend.js
- assets/src/blocks/Articles/useArticlesFetch.js
- classes/blocks/class-articles.php
* Using ApiFetch doesn't pass any language parameter to the endpoint.
However if you prefix the wp-json API path with the language code it
does pick this up.
* Check if the attributes are not empty instead of extracting them as
array keys. That was not working anymore since it's now getting a
request object instead in $fields.
> PLANET-4801 Use fetch with base url for wpml

- assets/src/blocks/Articles/ArticlesBlock.js
- assets/src/blocks/Articles/ArticlesFrontend.js
- classes/blocks/class-articles.php
* For translations to work on the frontend we need to setup some things
first, so this workaround restores what was previously translated on the
backend until we have set up the frontend translations.
Ref: https://jira.greenpeace.org/browse/PLANET-5371
Deployed on https://k8s.p4.greenpeace.org/test-pandora/wp-admin/
> PLANET-5371 Translate defaults on the backend

- assets/src/blocks/Submenu/SubmenuBlock.js
- classes/blocks/class-submenu.php
This should prevent breaking the existing Submenu blocks when merging the new WYSIWYG version.
> PLANET-4811 Fix Submenu rendering

- assets/src/blocks/Articles/ArticlesFrontend.js
* The block isn't available to be added in the post content, however it
is added automatically so we still need to exclude the current post id
if we're on a post.
> Exclude current post id on frontend

- assets/src/blocks/Carouselheader/CarouselHeaderSlide.js
Changed the limit indicator for the carousel header to match the actual limit of 32.
> PLANET-5235 Header Carousel: Header text cuts off at 32 characters

- assets/src/styles/editorOverrides.scss
- planet4-gutenberg-blocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-5344
> The video block displays over other blocks in the back end making it imposible to edit anything below it.
The iframe seems to ignore the max-(height|width) properties of its parents.
- ~Added an `height` property to the figure so that the inner frame can base its own size on it.  
The height value is arbitrary, but it helps the video to keep a proper size. I couldn't find another solution that would try to keep video ratio, fix overflow on other blocks and follow viewport width.~
- @mleray to the rescue; removing the `::before` content from the wrapper is enough and works a lot better.
- Activated P4 Media block in Campaigns, the block name in the allow-list was incomplete.
_Pic: before fix / after fix_
- Insert a Youtube block in a …
> PLANET-5344: Video block is displayed on top of other blocks in the editor

- assets/src/styles/blocks/ArticlesEditor.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5400
> A rule in the ArticlesEditor.scss file is not specific enough and applies to all `a` elements in the editor, causing various problems in other blocks.
Used a more specific selector `.wp-block[data-type="planet4-blocks/articles"]` based on block name, so that it never applies outside of its block.
The usage of Articles block in the editor should not change 🤷  
More specifically, clicking on a link inside this block in the editor should not lead to the linked page, but just put you into edit mode.
> PLANET-5400: Articles block editor CSS rule scope is not specific enough

- assets/src/BlockEditorValidation.js
Ref: https://jira.greenpeace.org/browse/PLANET-5384
* jQuery caused issues locally for new campaigns. Also nothing in the
script couldn't be done with native JS.
* Some readability improvements.
> PLANET-5384 Use native JS instead of jQuery

- tests/js/__snapshots__/cookies.spec.js.snap
- tests/js/cookies.spec.js
- tests/js/e2e-tests-helpers.js
Ref. [PLANET-5347](https://jira.greenpeace.org/browse/PLANET-5347)
To test, run npm install and npm run test.
Use npm run test:watch to run the tests in slow motion and watch execution in browser.
(Note: in case of timeout error try - `npm run env JEST_TIMEOUT=30000 WP_USERNAME=admin WP_PASSWORD=admin WP_BASE_URL=https://www.planet4.test wp-scripts test-e2e`)
> PLANET-5347 Added JS acceptance tests for Cookies block

- assets/src/styles/blocks/core-overrides/BlockSpacing.scss
Restricted .page-template styling in BlockSpacing.css to div.page-template
> PLANET-5014 Prevent the skip-links class from pushing page-content down

- assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
set url value to attributes.url as opposed to state.url
> PLANET-5424 Spreadsheet block: URL vanishes after page being published

- tests/js/__snapshots__/submenu.spec.js.snap
- tests/js/e2e-tests-helpers.js
- tests/js/submenu.frontend.spec.js
- tests/js/submenu.spec.js
Ref. [PLANET 5353](https://jira.greenpeace.org/browse/PLANET-5323)
To test, run `npm install` and `npm run test`.
Use `npm run test:watch` to run the tests in slow motion and watch execution in browser.
> PLANET-5323 Added JS acceptance tests for Submenu block

- classes/controller/menu/class-blocks-usage-controller.php
Ref: https://jira.greenpeace.org/browse/PLANET-5439
Blocked by https://github.com/greenpeace/planet4-master-theme/pull/1175 as it uses a function introduced there.
Especially since we added archived posts as a post type, this extra condition is needed because we're regex matching each post's content.
~~Maybe we should double check whether any NRO has custom post types that can contain blocks. If so maybe we can invert the where to exclude certain post types instead (would mainly be archive posts, but there may be others).~~ Actually we can figure out which posts types are registered that support the block editor, so we don't need to have a fixed list.
Before (GPI staging): https://release.k8s.p4.greenpeace.org/international/wp-admin/admin.php?page=plugin_blocks_report
After (Test instance …
> PLANET-5439 Search only in post types that could have blocks

- classes/controller/menu/class-classic-blocks-usage.php
- planet4-gutenberg-blocks.php
Since this block can be hard to support, it would be nice to know where it's still being used. (EDIT: I said "still" but actually new ones can be created using the code editor, which probably happens.)
We can't add this to the block report with the other core block types, as a classic block is not a real block as it's not inside a block comment, but is created on the fly when wordpress finds html that is not inside a block in a post.
https://k8s.p4.greenpeace.org/test-deimos/wp-admin/admin.php?page=classic_block_usages
> PLANET-5479 Add page showing posts with "classic blocks"

- assets/src/blocks/Counter/CounterBlock.js
- assets/src/blocks/ENForm/ENFormBlock.js
- classes/class-loader.php
- classes/controller/menu/class-en-settings-controller.php
- planet4-gutenberg-blocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-5292
Needs to be merged after https://github.com/greenpeace/planet4-master-theme/pull/1160 ! It uses classes introduced in that PR. The acceptance tests for this PR will fail until that is merged anyway.
Check the feature toggle of the EN block for the following cases:
* Whether the block can be used in the editor
* Whether the Engaging Networks admin menu item is displayed.
* Whether you can use the "Progress Bar inside EN Form" style on the counter block.
Because CMB2 interprets a falsy value on a boolean setting as "it should not store a record", it's not possible to set the default value to true, as that would make the field always true. So we need to run a script to turn the feature on everywhere instead. This is done in a post-deploy …
> PLANET-5292 Check EN feature toggle

- assets/src/styles/campaigns/themes/_theme_antarctic.scss
- assets/src/styles/campaigns/themes/_theme_arctic.scss
- assets/src/styles/campaigns/themes/_theme_climate.scss
- assets/src/styles/campaigns/themes/_theme_forest.scss
- assets/src/styles/campaigns/themes/_theme_oceans.scss
- assets/src/styles/campaigns/themes/_theme_oil.scss
- assets/src/styles/campaigns/themes/_theme_plastic.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5263
> This screen shot looks like H1 is not resizing for Mobile. This is the non campaign rules (...) So either apply H1 or H2 rules to it. H1 looks the closest.
Removing `page-header-(title|subtitle)` typography declarations to follow our styleguide rules.  `.page-header-title` is always associated with `h1`, `.page-header-subtitle` with `h2`, so no additional rule is needed.  
An exception was made for theme Arctic, as the font is really big and would break layout if treated as `h1/h2`. It takes `h2/h3` rules.   
Title can take a larger space on large screens, so it doesn't look like a column with large font-size.
> PLANET-5263: Follow header typography rules for campaigns

- tests/js/__snapshots__/articles.editor.spec.js.snap
- tests/js/articles.editor.spec.js
- tests/js/articles.frontend.spec.js
- tests/js/e2e-tests-helpers.js
Ref. [JIRA 5301](https://jira.greenpeace.org/browse/PLANET-5301)
To test, run `npm install` and `npm run test`.
Use `npm run test:watch` to run the tests in slow motion and watch execution in browser.
> PLANET-5301 Added JS acceptance tests for Articles block

- classes/blocks/class-articles.php
Ref: https://jira.greenpeace.org/browse/PLANET-5472
This is (almost) the same issue as [this one](https://github.com/greenpeace/planet4-master-theme/pull/1075/files), so I went ahead and applied the same fix. Now it uses the correct image size (https://github.com/greenpeace/planet4-master-theme/blob/ef1e3f3de1d65b672877febcb0d53b7088a15bde/src/MasterSite.php#L387-L387)  @pablocubico We can still keep the ticket if we want to look into srcset, but I guess this simple fix can make it into next deploy?
> PLANET-5472 Use existing thumbnail format

- assets/src/blocks/Articles/ArticlePreview.js
- classes/class-loader.php
Related to [JIRA 5398](https://jira.greenpeace.org/browse/PLANET-5398)
- Use [dateI18n()](https://developer.wordpress.org/block-editor/packages/packages-date/) function to translate date on articles block
eg. https://k8s.p4.greenpeace.org/test-titan/story/28934/test-image-block-with-blue-captionpost/
> PLANET-5398 Articles block translate date

- .circleci/config.yml
Ref: https://jira.greenpeace.org/browse/PLANET-5275
Ref: https://jira.greenpeace.org/browse/PLANET-5490
> pa11y is a tool that parses html documents in specific urls and discovers accessibility issues.
New accessibility test added to this repository, parallel to acceptance tests.  
Follows the same method as https://github.com/greenpeace/planet4-master-theme/pull/1165:
- Factorization of instance conf, install and test run
- New a11y job with report in artifacts
Result is there:
- https://app.circleci.com/pipelines/github/greenpeace/planet4-plugin-gutenberg-blocks/2533/workflows/01e681c0-e7f8-426a-a90e-bc6fc06ea415
- https://6788-196357997-gh.circle-artifacts.com/0/planet4-docker-compose/artifacts/pa11y/index.html
> PLANET-5490: Running accessibility report with pa11y

- assets/src/styles/editorOverrides.scss
See https://jira.greenpeace.org/browse/PLANET-5270
I first tried using the `defaultStylePicker` setting available in Gutenberg according to the [docs](https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#supports-optional), but that wasn't working... After a bit of research, this feature is still marked as "unreleased" in their [changelog](https://github.com/WordPress/gutenberg/blob/master/packages/blocks/CHANGELOG.md) (but that doesn't seem up to date, since it stops at version `6.13.0` and latest release is `9.0.0`) The entry in the docs was added at version `7.8.0`, so it's very strange that it's not working 🤔 
Anyway, I went instead for this CSS approach, which actually has the advantage of applying directly to all blocks (instead of having to update …
> PLANET-5270 Hide default style picker

- classes/class-loader.php
The articles block date translation was failing in block editor because of `window.p4bk_vars.dateFormat` var not found in backend.
> PLANET-5506 Fix articles block date translation in backend

- assets/src/styles/blocks/Columns.scss
Also removed text-decoration, because buttons already inherit that from the styleguide.
Ref: https://jira.greenpeace.org/browse/PLANET-5500
> PLANET-5500 Columns Block: Use full width on buttons

- assets/src/ImageBlockExtension.js
See https://jira.greenpeace.org/browse/PLANET-5497
The ticket specified to use CSS to hide the picker, but I think that this JS solution makes more sense 🙂 (CSS selector would be quite complicated, or we would need to add a new class just for this purpose)
> PLANET-5497 Remove Image block caption style picker

- assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
Ref: https://jira.greenpeace.org/browse/PLANET-5562
> An & sign is displayed as its htmlentities on the frontend version of the Split 2 Columns block, for the title (left column) and the tag (right column) of the block.
The `&` sign is automatically escaped by the RichText component on input, and saved as an html entity. To display it properly, we have to allow some html entities to be displayed as is.
Allows titles to display html characters, the same way it is allowed in text blocks.  
Input is still limited by `allowedFormats`, this fix is only here to compensate for the automatic escaping of `&`.
- Add a new page with a Split Two Columns block.
- Add a title to this block with an `&` (ie `Foo & Bar`)
- Clicking outside the block should trigger the frontend view, 
- On the current …
> PLANET-5562: Fix htmlentity character on split two columns titles

- assets/src/blocks/Articles/ArticlePreview.js
Rel. to [JIRA # 5373](https://jira.greenpeace.org/browse/PLANET-5373)
> PLANET-5373 Remove the "by" string in Articles block author names

- .circleci/config.yml
* Due to an issue the assets are not building for the tag. This is a
quick fix to allow tests to pass again while we further check the issue.
> Manually specify master for other repo

- assets/src/styles/blocks/Columns.scss
Added word break for columns description so long words don't cause the column to go oversize.
> PLANET-5468 Columns block: Huge image on the 4th column

- assets/src/blocks/Counter/CounterFrontend.js
For now this adds an eventListener to the counter which in turn executes the calculateRemaining.
This way GPNL (and other NRO's with devs) can use instantly updating counters.
Which might serve as a Proof of Concept for adding in more interactivity.
I will follow up on this PR with another which separates the functions for calling the API and calculating remaining. This improves the code a bit on single responsibility and make sure the instantly updating counter don't hit API's unneeded.
> Add option for updating the counters in the client

- assets/src/ImageBlockExtension.js
- assets/src/styles/blocks/core-overrides/Image.scss
- assets/src/styles/editorOverrides.scss
Ref. [JIRA 5426](https://jira.greenpeace.org/browse/PLANET-5426)
- Removed the "Blue Caption" style option from Image block backend(block Editor option)
- Removed blue caption styles code
- Added fallback solution for existing Image blocks with "blue-caption" style
**e.g.**
Page: https://k8s.p4.greenpeace.org/test-titan/test-image-block-with-blue-captionpage/
Post: https://k8s.p4.greenpeace.org/test-titan/story/28934/test-image-block-with-blue-captionpost/
Campaign:  https://k8s.p4.greenpeace.org/test-titan/campaign/image-block-with-blue-captioncampaign/
**Proposed solution:** Add a migration script which check all page, post, campaigns for Image blocks with blue caption style and update them with medium caption style value. 
**The fallback solution:** make alias of “caption-style-medium” …
> PLANET-5426 Image block - Removed the blue caption style

- assets/src/blocks/Articles/ArticlesFrontend.js
- assets/src/blocks/Articles/useArticlesFetch.js
- classes/blocks/class-articles.php
- tests/js/articles.frontend.spec.js
[JIRA 5388](https://jira.greenpeace.org/browse/PLANET-5388)
Issue -
- The articles block on Post page not showing the current page tags and categories related articles
Before fix - https://www.greenpeace.org/international/story/44543/fading-memories-of-atomic-bombing-hiroshima-75-years-later/
After fix    - https://k8s.p4.greenpeace.org/test-jupiter/story/44543/fading-memories-of-atomic-bombing-hiroshima-75-years-later/
(Please check the articles block at the bottom of page, The articles display in block should belongs to current post tags and categories)
> PLANET-5388 Fix related articles issue on Post

- assets/src/blocks/Articles/useArticlesFetch.js
- assets/src/blocks/Gallery/GalleryFrontend.js
- assets/src/blocks/Gallery/useGalleryImages.js
- assets/src/blocks/Happypoint/useHappypointImageData.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
- assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
- assets/src/functions/fetchJson.js
- classes/class-loader.php
Ref: https://jira.greenpeace.org/browse/PLANET-5607
`apiFetch` fails if the page is cached with an expired nonce, then it fails to fetch a new nonce. The fix is to not use `apiFetch` on the frontend but a regular `fetch` instead. This probably also prevents an issue with wpml, as we applied the same solution for such an issue in the Articles block previously, and now that block is not experiencing the nonce issue.
> PLANET-5607 No apiFetch on frontend, it breaks wpml and nonces

- .circleci/config.yml
* Apply same changes like in master theme https://github.com/greenpeace/planet4-master-theme/pull/1208
* Remove `sleep 10`
Tested with another user than mine, with a PR where the tests should fail, done with a change that should only make it fail if it correctly builds the right assets (by redirecting to a non-existent page in `frontendIndex.js`): https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/415
Ref: https://jira.greenpeace.org/browse/PLANET-5221
> PLANET-5221 Check out code for acceptance on fork PRs

- assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsInPlaceEdit.js
- assets/src/styles/blocks/CarouselHeader.scss
- assets/src/styles/blocks/CarouselHeader_full_width_classic.scss
- assets/src/styles/blocks/Columns.scss
- assets/src/styles/campaigns/base/_mixins.scss
- assets/src/styles/campaigns/themes/_theme_antarctic.scss
- assets/src/styles/campaigns/themes/_theme_arctic.scss
- assets/src/styles/campaigns/themes/_theme_climate.scss
- assets/src/styles/campaigns/themes/_theme_forest.scss
- assets/src/styles/campaigns/themes/_theme_oceans.scss
- assets/src/styles/campaigns/themes/_theme_oil.scss
- assets/src/styles/campaigns/themes/_theme_plastic.scss
- assets/src/styles/editorOverrides.scss
- templates/blocks/carousel_header_full-width-classic.twig
- templates/blocks/columns_tasks.twig
See https://jira.greenpeace.org/browse/PLANET-5501
- Remove any custom button properties in campaign themes
- Update button styles in the editor (WYSIWYG)
- Remove `btn-medium` class as it just duplicates the "regular" button styles
- Remove CarouselHeader button style overrides
- Remove Splittwocolumns button style overrides
- Remove some of the RTL-related overrides
- [styleguide](https://github.com/greenpeace/planet4-styleguide/pull/80)
- [master-theme](https://github.com/greenpeace/planet4-master-theme/pull/1205)
> Planet 5501 - Consistent styles for buttons

- assets/src/styles/blocks/ENForm/components/_enform.scss
When updating the button styles for [PLANET-5501](https://jira.greenpeace.org/browse/PLANET-5501) we forgot some overrides in the EN forms 😬
> PLANET-5501 Update EN form button styles

- assets/src/styles/components/HTMLSidebarHelp.scss
- assets/src/styles/editorOverrides.scss
See https://jira.greenpeace.org/browse/PLANET-5349
- Override editor sidebar help texts (`components-base-control__help`, `components-form-token-field__help`, `FieldHelp`  classes) font size with WP standards (otherwise it applies [our generic rule for paragraphs](https://github.com/greenpeace/planet4-styleguide/blob/master/src/base/_typography.scss#L18) from `_typography.scss`)
- Override `sidebar-blocks-help ul li` font size with WP standards (otherwise it applies [our generic rule for lists](https://github.com/greenpeace/planet4-styleguide/blob/master/src/base/_typography.scss#L19) from `_typography.scss`)
- The Timeline block uses a custom `HTMLSidebarHelp.scss` file that was setting the font size too small compared to the WP standards, so this override was updated
- Broken version: …
> PLANET-5349 Fix sidebar help texts font size

- assets/src/blocks/Media/MediaBlock.js
- assets/src/blocks/Media/MediaEditor.js
- assets/src/blocks/Media/MediaFrontend.js
- assets/src/blocks/Media/deprecated/mediaV1.js
This makes the component set the embed html in the input change listener so that we don't need to set the attributes in an intermediary invalid state until the effect runs, but instead sets both at the same time. This ensures that no render can unintentionally trigger a change to the post content.
Since the backend will still render any block that has no content**, we can make the block return `null` in save whenever it's missing either (or both) `embed_html` or `poster_url`, but does have the corresponding "identifier" prop (`media_url` or `video_poster_img`). Then it uses [`useSelect` in the edit component](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/423/files#diff-c6c91408622162ae2bd090b6d50b303d1de0a3ebff4e385997189643c4a18ce1R124) to get the missing html or …
> Media change listener

- assets/src/blocks/Timeline/Timeline.js
Ref: https://jira.greenpeace.org/browse/PLANET-5640
> The timeline block in GPSEA 20th Anniversary campaign page suddenly doesn't show
The timeline block seems to be broken for some sheets urls.
The version 3.6.6 (introduced in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/368) calls a different url than 3.6.3 for the same document, and that url gets a 403 instead of the document itself.
For the same spreadsheet url given:
```
3.6.3: https://spreadsheets.google.com/feeds/list/1tYlLd_Fx0T_7ZEaf2y9dLfRnr5HzEOW_s0wELp5-j4s/1/public/values?alt=json
3.6.6: https://sheets.googleapis.com/v4/spreadsheets/1tYlLd_Fx0T_7ZEaf2y9dLfRnr5HzEOW_s0wELp5-j4s/values/A1:R1000?key=AIzaSyCInR0kjJJ2Co6aQAXjLBQ14CEHam3K0xg
```
Updating Timeline version to 3.8.10 solves this issue, and …
> PLANET-5640: Update Timeline lib to resolve google api version problems

- assets/src/styles/blocks/Gallery_content_three_column.scss
- classes/blocks/class-gallery.php
Ref: https://jira.greenpeace.org/browse/PLANET-5633
> On both the front and back ends the 3-column style of the gallery block is not working as expected. 
> The images are overly zoomed and the centre function in the wysiwyg is not functioning.
- Switching object-fit property from none to cover, to give each image more visibility and more moving space with focus.
- Fixing a small notice `Undefined index` on dev env that would break the ajax request when gallery_block_style is not specified.
Before:
After:
- Insert a Gallery block in a page, add at least 3 images
- Select the style "3 columns"
- You should see more parts of the image, and the focus point should have an effect on the part of the image visible.
> PLANET-5633: Gallery block 3 Columns style overly zoom on images

- assets/src/blocks/Articles/ArticlePreview.js
Ref: https://jira.greenpeace.org/browse/PLANET-5652
> In the Articles block, tags listed on top of each article are escaped and will display an ampersand as &amp;
Using `unescape()` function to fix tag names
Before fix:
After fix:
- Find an Articles block (Related articles) listing some articles with tags
- Edit one of those tags to add a character `&` in its title
- It should appear as `&` in the tag list of the related articles
> PLANET-5652: Articles block: Tags containing an ampersand are displayed escaped

- assets/src/styles/editorOverrides.scss
We can already deploy this part so people can see in the editor which buttons need to have capitalization fixed.
> Remove text transform on buttons in editor

- classes/blocks/class-covers.php
- classes/class-loader.php
* Slick was added as a dependency of the plugin's styles, even though
it's not needed.
* It turns out the pubslider.js script is currently not doing anything
as it uses a wrong selector, so doesn't match anything. It's also the
only usage of slick slider. I'll keep the script itself in as we might
fix it in a follow up ticket.
> PLANET-5503 Remove slick dep and pubslider

- assets/src/blocks/Gallery/GalleryFrontend.js
- assets/src/blocks/Gallery/GalleryGrid.js
- classes/blocks/class-gallery.php
That way it doesn't require an endpoint call to render.
I also noticed that a lot of our pages were getting the "properly size images" warning in pagespeed tests. Turns out that for the Gallery Grid view, which is the smallest way to show the image, it wasn't specifying srcset, even though it's available at that point. 
As a result it was using an image that is 1200px wide while only 222px is displayed (the actual display size is a bit bigger as we cut off a part with the focal point, but not that much).
> Include gallery data in page, add missing srcset

- .stylelintrc
- assets/src/styles/blocks/Columns.scss
- assets/src/styles/blocks/Covers/TakeActionCovers.scss
- assets/src/styles/blocks/Spreadsheet.scss
- assets/src/styles/editorOverrides.scss
- package-lock.json
- package.json
- webpack.config.js
Relevant ADR: https://docs.google.com/document/d/10r5RM1h8tN6Dw8APCJCM7GeRYOaRIOc8QMm2t13AwT8/edit# (advised to read the "Challenges" section, it describes the limitations of SCSS for this use case).
Add webpack plugin that runs after SCSS is transformed to CSS, to transform the shorthand syntax into the corresponding declarations that include variables.
So it should transform any sub-selector that in SCSS starts and ends with 2 dashes into variable declarations that are added to the parent selector. So
```scss
#some .parent[selector] {
border: 2px;
--some-meaningful-name-- {
color: red;
background-color: green;
}
}
```
into
```css
#some .parent[selector] {
border: 2px;
color: var(--some-meaningful-name--color, red);
background-color: var(--some-meaningful-name--background-color, green); …
```
> Add plugin for shorthand css variable syntax

- assets/src/blocks/Articles/ArticlePreview.js
Ref: https://jira.greenpeace.org/browse/PLANET-5706
> Escaped html entities are displayed in the articles text (here, `&nbsp;`).
> The template currently only replaces the entity `&hellip;`
As for some other fields, the post excerpt has to be filtered (unescaped) so that the html entities appear as expected (`&hellip;` as `…`, `&nbsp;` as a non-breakable space, etc.).
Same fix used for similar cases, by unescaping the content of `post_excerpt` on the frontend.
- Find or create  a page with an Articles block
- Edit the excerpt of one of those articles, add a `&` sign
- The Articles block on the frontend should show a `&` sign, not a `&amp;`
> PLANET-5706: Escaped html entities are displayed in the post excerpt in Articles block

- assets/src/blocks/Gallery/GalleryCarousel.js
Ref: https://jira.greenpeace.org/browse/PLANET-5728
Alright, so apparently this was caused by the removal of the `useGalleryImages` effect here: 
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/commit/735d0d10f7bab6a745cec6df0d684638258094b1
As that was causing aditional renders, `idRef.current` was available on subsequent renders, now that the endpoint is gone, the ref is initialized as `null` and that's what goes into the markup, so `document.getElementById` can't find it:
So the change was to avoid relying on an ID ref and DOM methods and use a collection of refs instead.
> PLANET-5728: Carousel Gallery: Slider not working

- assets/src/styles/editorOverrides.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5442
> In the editor the unordered list font size is bigger than paragraphs (at least on large screens, smaller screens seem fine), see screenshot. It should be the same font size for both. Ordered lists seem fine too but it's worth double checking. In the frontend however it's all good!
_Some work was done on lists in editor in https://github.com/greenpeace/planet4-styleguide/pull/72, so the difference left was less than reported at the time._
Lists were a little bit bigger on large screen, and smaller on small screens.
| before | after |
| --- | --- |
| ![Screenshot from 2020-11-25 17-40-46](https://user-images.githubusercontent.com/617346/100256713-62b1cb00-2f45-11eb-80fa-81865077860f.png) | ![Screenshot from 2020-11-25 …
> PLANET-5442: Unordered list font size bigger than paragraph in the editor

- classes/blocks/class-happypoint.php
Ref: https://jira.greenpeace.org/browse/PLANET-5732
> At the upper left corner it shows "happy point planting" probably the alt information of the image.
> But the image is missing from the background.
HappyPoint uses a malformed URL for background image src. The issue doesn't appear on most websites because the `srcset` attribute is usually properly filled, here it has no alternative set.
```html
<picture>
loading="lazy" 
src="https://www.greenpeace.org/static/planet4-greece-stateless/2018/02/0-Planting-2048x1365.jpg,2048,1366,true"
alt="HAPPY-Point-Planting" 
srcset="false" 
sizes="false">
</picture>
```
Endpoint is returning an array as `background_src`, which is then used concatenated as a URL
```
GET https://www.greenpeace.org/greece/wp-json/planet4/v1/get-happypoint-data?id=4098
{ …
```
> PLANET-5732: Happy Point background image missing

- templates/blocks/carousel_header_full-width-classic.twig
This reverts commit 143a2c31d7b458ca4bbac4bbf64000117e7cf5df.
Since [PLANET-5584](https://jira.greenpeace.org/browse/PLANET-5584) we no longer need that. Need to revert the code before disabling it on Cloudflare, in case some re-enabled the feature.
> Revert "PLANET-5142 Add twig filter(cf_img_url) on carousal header

- classes/blocks/class-covers.php
Ref: https://jira.greenpeace.org/browse/PLANET-5775
> On some older Covers blocks, a _doing_it_wrong is raised from rest_validate_value_from_schema, because of an invalid attribute type declared in class-covers.php
> Notice: rest_validate_value_from_schema was called incorrectly. The "type" schema keyword for can only be one of the built-in types: array, object, string, number, integer, boolean, and null.
- Set description type as string.
> PLANET-5775: Covers block: invalid attribute type breaks editor

- assets/src/styles/campaigns/themes/_theme_antarctic.scss
- assets/src/styles/campaigns/themes/_theme_arctic.scss
- assets/src/styles/campaigns/themes/_theme_climate.scss
- assets/src/styles/campaigns/themes/_theme_forest.scss
- assets/src/styles/campaigns/themes/_theme_oil.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4660
We agreed in the ticket to follow the generic rule of our typography for h2 titles, `line-height: 1.38`.
While testing, I also found a color issue for social icons.
_blue icons issue_
Fixes for EN Form Thank you message:
- Fix line-height of Thank you message title
- Fix social icons color
- On a campaign page with theme "climate emergency", display an EN Form block
- The _Thank you_ message can be revealed by editing the div with class `thankyou ` in the browser inspector, it's `display: none;` by default.
- Social icons should be visible, message title should fit the requirements (on a regular width)
```
font: Jost Bold
font-size: 2.5rem
line_height: 1.38
```
> PLANET-4660: EN Form block - Adjust Thank you message font

- assets/src/blocks/Articles/ArticlesEditor.js
Ref: [JIRA 4732](https://jira.greenpeace.org/browse/PLANET-4732)
---
**Task:**
- Allow editor to choose articles counts option for manual override post setting.
**Testing:**
- Add articles block on page/post with manual override posts option
- Add articles count value, test on frontend
> PLANET-4732 Articles Block: Show articles count option for Manual override post setting

- classes/controller/menu/class-blocks-usage-controller.php
Ref: https://jira.greenpeace.org/browse/PLANET-5616
---
- For Posts with no title it will just display `(no title)`, similar to what the native post list does.
- Links reversed. ID links to editing the Post. Title links to the frontend.
- Removed the custom query for Carousel Header, since we only have one style now.
> Planet 5616 - Fix block reports for Post with no title

- assets/src/styles/blocks/Covers/ContentCovers.scss
Ref: https://github.com/greenpeace/planet4/issues/128
This change is to show a bit of the third card in a row of content covers as shown here:
The trick is to set the width to something under 50%, like 45%, so the first two cards would take 90% of the screen width.
Note:
The content covers styles are affecting some Bootstrap styles, this is something I would like to change in the Grid System issues, for now I'll leave it as it is. 
Also, this block still needs to be converted to WYSIWYG so we could revisit the layout there.
> Use a percentile width to show a bit of the third card

- assets/src/styles/blocks/Covers/ContentCovers.scss
- templates/blocks/content_covers.twig
See https://jira.greenpeace.org/browse/PLANET-5642
I've also removed the custom color that we had in this block for links, as content links should all follow the color defined in the styleguide.
> PLANET-5642 Update ContentCovers heading and links

- classes/blocks/class-enform.php
Ref: [JIRA 5774](https://jira.greenpeace.org/browse/PLANET-5774)
---
**Issue:**
- If the OG description (open graph) field of post have a html tag in it, it will breaks the EN form's Thank you page "Share on mail" button functionality.
Before fixing the issue the mail to is -
```
mailto:?subject=Ikke%20mere%20beskidt%20palmeolie%21%20-%20Greenpeace%20Danmark&body=&lt;p&gt;VIS DIN STØTTE FOR REGNSKOVEN. Værdifulde skovområder bliver ødelagt, lokale indbyggere mister deres hjem og orangutang risikerer at uddø. Skriv under og vær med via @greenpeacedk&lt;/p&gt; https://www.greenpeace.org/denmark/campaign/beskidt-palmeolie-truer-regnskoven/
```
After fix -
```
mailto:?subject=Ikke%20mere%20beskidt%20palmeolie%21%20-%20Greenpeace%20Danmark&body=VIS DIN STØTTE FOR REGNSKOVEN. Værdifulde …
```
> PLANET-5774 EN Form(Thank you page): Strip share on mail button body text

- assets/src/styles/blocks/Covers/TakeActionBoxoutBottom.scss
- assets/src/styles/blocks/Covers/TakeActionBoxoutScroll.scss
- classes/blocks/class-takeactionboxout.php
- templates/blocks/take_action_boxout.twig
See https://jira.greenpeace.org/browse/PLANET-5791
- Move `cover-card-more` element outside of `cover-card-content` to fix the absolute positioning
- Use `bottom` instead of `top` positioning to adapt to potential longer translation strings for "Want to do more?"
- Add alt text to the image
> PLANET-5791 Fix last issues for Take Action boxout A/B test

- assets/src/styles/campaigns/base/_mixins.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5731
---
Fixed campaign styles forcing cookie button to be too narrow
> PLAENT-5731 Cookie notice button on campaigns is too narrow

- classes/blocks/class-carouselheader.php
Ref: https://jira.greenpeace.org/browse/PLANET-5779
---
added is_numeric check to carousel header focus point setter to avoid non-numeric error
> PLANET-5779 fix non-numeric error in carousel header

- assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsSettings.js
- assets/src/blocks/Splittwocolumns/imageSizes.js
- assets/src/components/ImageOrButton/ImageOrButton.js
- classes/blocks/class-base-block.php
- classes/blocks/class-splittwocolumns.php
- classes/exception/class-notimplemented.php
- classes/rest/class-rest-api.php
Ref: https://jira.greenpeace.org/browse/PLANET-5733
Deployed on https://www-dev.greenpeace.org/test-deimos/vaer-med/verdenshavene/
**Some context on srcset and sizes** can be found in the description of https://jira.greenpeace.org/browse/PLANET-5810. We'll probably do something similar like is done in this PR for all other images, though most will probably not be as straightforward as this PR. I used https://github.com/ausi/respimagelint for diagnosing the images, which seems to work reliably in most cases.
Before we made Split Two Columns wysiwyg, it was using an srcset in the twig template. In the newer version it doesn't use the srcset when saving in JS, though the backend does set it if an older version of the block is handled.
After investigating the sizes attribute, I found that it …
> PLANET-5733 Provide srcset for split two columns

- .circleci/config.yml
Ref: https://jira.greenpeace.org/browse/PLANET-5434
php-8 job is not added yet, but since we already switched to 7.3 no need to test for a previous version.
Counterpart of greenpeace/planet4-master-theme#1270
> PLANET-5434 Remove php-7.2

- .circleci/config.yml
Ref: https://jira.greenpeace.org/browse/PLANET-5883
Forgot to add this to the `create-zip` job. It's a bit weird that it happens in that job, but otherwise `request-instance` would need to check out the code too, which would add some time to the job.
> PLANET-5883 Add missing commit message extract

- assets/src/blocks/Gallery/GalleryCarousel.js
- assets/src/blocks/Gallery/GalleryGrid.js
- assets/src/blocks/Gallery/GalleryThreeColumns.js
Ref: https://jira.greenpeace.org/browse/PLANET-5901
This ensures a lot less images are loaded if this block is present below the fold.
> PLANET-5901: Lazy load gallery images

- assets/src/styles/blocks/Columns.scss
Ref: [JIRA 5849](https://jira.greenpeace.org/browse/PLANET-5849)
---
- In columns block twig template, the `btn-primary` button class is only use for campaign, so removing it from Columns.scss will not cause any side effects 
eg.
https://www-dev.greenpeace.org/test-venus/campaign/toolkit-plastic-free-future/
https://www-dev.greenpeace.org/test-venus/campaign/test-default-theme/
https://www-dev.greenpeace.org/test-venus/campaign/test-climate-emergency-theme/
https://www-dev.greenpeace.org/test-venus/campaign/test-oil/
> PLANET-5849 Campaign page: fix columns block button width

- assets/src/blocks/Gallery/GalleryFrontend.js
Ref: https://jira.greenpeace.org/browse/PLANET-5945
> Image credits are not visible in the Gallery block.
The current code displays credits only if there's no caption.
- Compile image title with credits if it exists
- Insert a Gallery block in a page
- Add images that have the `Credit` field filled, or fill it
- Credits should appear on the frontend, after the caption
> PLANET-5945: Add credits to gallery caption

- assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
Ref: [JIRA 5812](https://jira.greenpeace.org/browse/PLANET-5812)
---
- Update cssvar names in spreadsheet block
- It works fine for newly added blocks. For existing spreadsheet blocks, I was thinking to add a migration script but as per the [P4 block usage report](https://docs.google.com/spreadsheets/d/1uAmZLIWYsxrBByqbhoF_vVtSM7WGebYWIc0xftPRPwE/edit?pli=1#gid=359432436), the spreadsheet block is used by only 4 NRO's (7 times), So in my opinion it would be much simple to just login and update cssvar names from block editor instead of adding a migration script.
> PLANET-5812 Fix spreadsheet block colors issue

- assets/src/styles/blocks/CarouselHeader.scss
- assets/src/styles/blocks/CarouselHeader_full_width_classic.scss
- assets/src/styles/blocks/Columns.scss
- assets/src/styles/blocks/Covers/TakeActionCovers.scss
- assets/src/styles/blocks/Happypoint.scss
- classes/class-loader.php
See https://jira.greenpeace.org/browse/PLANET-5842
- ~~#63bbfd = $blue-60~~
- ~~($grey-60) = $shadow-color~~
- ~~#f6f4e7 = $single-bg~~
- ~~#aed4c7 = $active~~
- ~~#b0d4c8 = $body-bg~~
- ~~#a7e021 = $inch-worm~~
- ~~#e51538 = $crimson~~
- ~~#5c1f10 = $brown-header~~
- ~~#003300 = $green~~
- ~~#264042 = $darkb-blue-text~~
- ~~#004d53 = $heading~~
- ~~#115247 = $search-text-color~~
- ~~#186a70 = $genoa~~
- ~~#017e7a = $percentage-text~~
- #418482 = $faded-jade => actually used in search page for search bar border, will be replaced in https://jira.greenpeace.org/browse/PLANET-5843
- ~~#22938d = $blue-elm~~
- ~~#67b2af = $light-blue~~
- ~~#1bb6d6 = $java~~
- ~~#007799 = $allports~~
- ~~#152340 = (none)~~
- ~~#152431 = $article-heading-color~~
- ~~#1b4a1b = $green-80~~
- ~~#a7a7a7 = …
> PLANET-5842 Remove unused colors

- assets/src/blocks/Articles/ArticlePreview.js
- assets/src/blocks/Articles/imageSizes.js
- assets/src/blocks/Gallery/GalleryCarousel.js
- assets/src/blocks/Gallery/GalleryGrid.js
- assets/src/blocks/Gallery/GalleryThreeColumns.js
- assets/src/blocks/Gallery/imageSizes.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
- assets/src/blocks/Splittwocolumns/imageSizes.js
- classes/blocks/class-articles.php
Ref: https://jira.greenpeace.org/browse/PLANET-5666
Misnamed the branch, has nothing to do with lazy loading :facepalm: 
Add image sizes to some of our blocks. There's more to do but let's evaluate the impact of these already.
The attributes were generated using this bookmarklet https://github.com/ausi/respimagelint
Also adds missing `srcset` to Articles, that could help a lot too :grin:
> PLANET-5666: Add image sizes

- assets/src/styles/blocks/Gallery_content_three_column.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5950
> Remove the yellow color between the images (diagonal stripes), from the 3 columns gallery block by either:
>   - ideally, replacing it by a transparent background color
>   - or, replacing it by a white color, so it fits the white background color
Color is applied to middle image borders; making it transparent just makes the images look stuck to each other.
Changing background color to an existing (used by body in styleguide) variable --body-background-color (fallback to white) to look transparent.
- Add an image Gallery to a page
- Check the middle image border colors, it should be #fff
> PLANET-5950: Remove yellow separator between gallery 3 cols images

- .circleci/config.yml
Next-gen circleci image has python3
---
Same as greenpeace/planet4-master-theme#1302
> Switch to pip3

- assets/src/styles/campaigns/base/_mixins.scss
- assets/src/styles/campaigns/themes/_theme_climate.scss
- assets/src/styles/campaigns/themes/_theme_oil.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5939
Goes with: https://github.com/greenpeace/planet4-master-theme/pull/1301
Since https://github.com/greenpeace/planet4-master-theme/pull/1293 , Campaign templates implementing an override to margin of page-header are pushing content too low.
_Expected layout:_
_Layout after https://github.com/greenpeace/planet4-master-theme/pull/1293_
This comes from fixed margins applied to `.page-header`, even when this div is `.page-header-hidden`.
Reapplying regular margin and padding of `.page-header-hidden` to campaigns.
> PLANET-5939: Header is too low on campaign templates with no title

- assets/src/blocks/Submenu/getHeadingsFromDom.js
- classes/blocks/class-submenu.php
Ref: https://jira.greenpeace.org/browse/PLANET-5865
Submenu block crashes when it doesn't get any heading level.
A new submenu saved without adding any level doesn't have a `levels` attribute on the frontend, which leads to `getHeadingsFromDom()` throwing errors.  
- add default `levels` value to attributes, matching the editor behavior on this
- value check in `getHeadingsFromDom()` so that this error can't happen
- Add a `Submenu` block on an empty page, adding no option to the block
- on `master` branch, viewing/previewing this page on frontend will throw an error
- on this branch, no error is thrown and the submenu is displayed if it has a title
> PLANET-5865: Submenu block breaks when it has no heading level

- .circleci/config.yml
Removing the python call, since the script is executable and already configured to use python3
> Use python3 for book-instance

- assets/src/blocks/Timeline/Timeline.js
- assets/src/components/useScript/useScript.js
Ref: https://jira.greenpeace.org/browse/PLANET-5960
TimelineJS seems to include lodash in the global `_` variable.
It replaces the Underscore `_` used by Wordpress for media interactions in the editor.
Any block that calls a Wordpress media function (here in `wp-includes/js/media-views.js`) might try to use the `_` object, and if the function has a different API in Underscore and Lodash, it will fail, and put the block (or even the editor in some situations) in a broken state (block/editor has encoutered an error).
```
Uncaught TypeError: this.activateMode is not a function
_createModes media-views.js:2815
```
Running a [`_.noConflict()`](https://docs-lodash.com/v4/no-conflict/) function (also available in [Underscore](https://underscorejs.org/#noConflict)) after including TimelineJS …
> PLANET-5960: Timeline block breaks the editing of media blocks

- classes/class-loader.php
Ref: https://jira.greenpeace.org/browse/PLANET-5964
We can merge this already since the dependency is not needed. Needs further changes in master-theme to actually load before jQuery: https://github.com/greenpeace/planet4-master-theme/pull/1300
> PLANET-5964: make load earlier by removing main dep

- .stylelintrc
- assets/src/styles/blocks/Media.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5970
---
The CSS packaged with the player sets a max-width on the element, whereas previously our iframe had a 100% width and no max-width. I added a new rule for this element specifically.
> PLANET-5970 Restore previous youtube embed width

- .circleci/config.yml
Since we renamed repo name and default branch, this currently breaks tests.
> Fix base branch and name

- .circleci/config.yml
a11y tests are currently failing because of some changes in our docker-compose configuration.
We are planning to run those tests on live test instances, and this job is consuming resources while failing systematically. It's better to comment this out for now and work next on moving it to run on the test instance.
Related: https://github.com/greenpeace/planet4-master-theme/pull/1318
> Comment a11y test out until we make them run on test instances

- planet4-gutenberg-blocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-5990
---
Since native embed block doesn't support latest Facebook API changes anymore,
we need this in order to enable people to be able to embed FB/IG content
in Posts.
> _[Test post](https://www-dev.greenpeace.org/test-proteus/story/1007/social-media-test/)_
> PLANET-5990 Enable Social Media block on Posts

- assets/src/styles/blocks/Media.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5985
The bottom padding was set following this technique for responsive iframe-based videos:
https://css-tricks.com/fluid-width-video/
For the technique to work, `height` has to be `0`.
---
> PLANET-5985: Too much padding bottom for new YouTube embed

- assets/src/BlockFilters.js
- assets/src/components/Image/ImageBlockEdit.js
Ref: https://jira.greenpeace.org/browse/PLANET-4590
Linked to: https://github.com/greenpeace/planet4-master-theme/pull/1259
> In the editor, when an Image is added to post, the caption is there but the credit/copyright text is missing.
> It's visible though in the frontend. That can be confusing for editors.
- Adding a hook to BlockEdit allows to append the image caption with the credits.
- Another PR on master-theme adds the `credit_text` in the response of the rest API.
...like [`blocks.getBlockAttributes` or `blocks.getSaveElement`](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/filters/block-filters.md#filters) ? 
This fix uses `useSelect` to fetch image details and get the credits. 
Hooks in those filters gives an error `Error: Invalid hook …
> PLANET-4590: Image block: Photo credit/copyright is not visible in the editor

- assets/src/components/p4_table/edit.js
See https://jira.greenpeace.org/browse/PLANET-5875
I've updated the `edit` file with the new version for WP5.6 and modified it to fit our needs. This PR should also solve the Table block part of [PLANET-5871](https://jira.greenpeace.org/browse/PLANET-5871) (it adds back the top controls for moving/deleting/etc the block).
You can test it on the [test-titan instance](https://www-dev.greenpeace.org/test-titan/).
There is another way to solve these issues, explored in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/515.
> PLANET-5875 Update Table  block edit file for WP5.6

- assets/src/blocks/Gallery/GalleryCarousel.js
- assets/src/styles/blocks/Gallery_carousel.scss
Partial fix for:
Ref: https://github.com/greenpeace/planet4/issues/125
Accessibility fix: convert anchors into buttons on the carousels.
> A11y: Convert carousel anchors to buttons

- .stylelintrc
- assets/src/styles/blocks/Accordion.scss
- assets/src/styles/blocks/Covers/TakeActionBoxoutBottom.scss
- assets/src/styles/blocks/Covers/TakeActionBoxoutScroll.scss
- assets/src/styles/blocks/Gallery_carousel.scss
- assets/src/styles/blocks/SplitTwoColumns.scss
- assets/src/styles/blocks/Submenu.scss
- assets/src/styles/campaigns/base/_mixins.scss
- assets/src/styles/campaigns/themes/_theme_climate.scss
- assets/src/styles/campaigns/themes/_theme_oil.scss
- assets/src/styles/components/VarPicker.scss
- assets/src/styles/vendors/photoswipe/main.scss
- assets/src/styles/vendors/photoswipe/p4-skin.scss
Ref: no ticket yet
---
Since we use autoprefixer, we can use a stylelintrule to detect any prefixes in our source that would be added during build anyway. This adds the rule and fixes violations, except `-webkit-box-orient` which is buggy.
> Prevent unneeded prefixes, we autoprefix

- admin/js/editor.js
- assets/src/BlockFilters.js
- assets/src/components/p4_button/color-edit.js
- assets/src/components/p4_button/color-props.js
- assets/src/components/p4_button/edit.js
Ref: [JIRA 5871](https://jira.greenpeace.org/browse/PLANET-5871)
---
- Updated the native button block files with the new version for WP5.6.
- Make the default button style selected by default
- Move P4 button styles override from [editor.js](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/edf475f0c227657b91a32a31b7b43e4b880c9d9d/admin/js/editor.js#L4) to [BlockFilter.js](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/BlockFilters.js)
> PLANET-5871 Update button block files with custom colors, remove BorderPanel & WidthPanel

- classes/class-loader.php
- planet4-gutenberg-blocks.php
---
I need to make some changes in this file, but first it really needs a clean up. The code currently is hard to make sense of. The naming is not accurate, it's deeply nested and does a lot of unnecessary things.
I moved the error output to the respective functions that check them, so they don't need to return a boolean and can just die inside if requirements are not satisfied.
The goal is to make it possible to have a high level overview of what's happening in this file.
This relates to the ticket in the following way: we're moving parts of the styleguide into master theme to more easily change them. First we need to move parts of `editorStyle` into master theme to remove the dependency for the plugin. For that I need to replicate the …
> PLANET-5983: Enable high level overview of loading code

- assets/src/blocks/Articles/ArticlesFrontend.js
- assets/src/blocks/Carouselheader/FullWidthCarouselHeader.js
- assets/src/blocks/Gallery/GalleryCarousel.js
- assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
- assets/src/styles/blocks/Covers/ContentCovers.scss
- assets/src/styles/blocks/ENForm/components/_enform.scss
- assets/src/styles/blocks/Gallery_content_three_column.scss
- assets/src/styles/blocks/Happypoint.scss
- assets/src/styles/blocks/Media.scss
- templates/blocks/carousel_header_full-width-classic.twig
- templates/blocks/columns_tasks.twig
- templates/blocks/enform/country_select.twig
- templates/blocks/enform/position_select.twig
See https://jira.greenpeace.org/browse/PLANET-5981
Changes made to comply with the [migration doc](https://getbootstrap.com/docs/5.0/migration/):
- Rename all Bootstrap attributes' prefixes from `data-` to `data-bs-`
- Remove `form-inline` and `custom-select` classes (removed from Bootstrap 5)
- Add `form-select` to select components instead of `form-control` (which now has the `appearance: none;` hiding the select's arrow)
- Remove `mr-auto` class (it should have been renamed `me-auto`, but wasn't doing anything except causing issues in RTL sites so better remove it 🤷‍♀️)
- Update ContentCovers width overrides
- Add `position: relative;` to `col` class for GalleryThreeColumns since it was removed from Bootstrap
- Rename `carousel-item-left` and `carousel-item-right` to …
> PLANET-5981 Updates for Bootstrap 5

- assets/src/styles/blocks/File.scss
- assets/src/styles/blocks/core-overrides/Image.scss
See [PLANET-5980](https://jira.greenpeace.org/browse/PLANET-5980)
- Header alignment choice (left/right/center) not reflected in the frontend
- Image alignment breaks text and creates gaps
- Button manually chosen text color not applied properly in the frontend
Should also solve [PLANET-5857](https://jira.greenpeace.org/browse/PLANET-5857)
- Weird breaks in paragraphs and lists with HTML tags (bold, anchor links, etc)
- [styleguide](https://github.com/greenpeace/planet4-styleguide/pull/100)
> PLANET-5980 Fix inconsistencies between editor and frontend

- assets/src/blocks/Carouselheader/FullWidthCarouselHeader.js
- assets/src/styles/blocks/CarouselHeader_full_width_classic.scss
Small extra fix for Bootstrap5, the indicators were no longer working properly in the CarouselHeader due to the missing new `bs-` prefix.
Also added a small fix for the "next" arrow, which had the background image slightly off!
> PLANET-5981 Fix CarouselHeader indicators

- assets/src/BlockEditorValidation.js
- assets/src/blocks/Carouselheader/CarouselHeaderBlock.js
* This was handled in a component's render method. So the post was only
accurately locked/unlocked when something triggered this component to
render. Somehow in WP 5.6 this was not working for us anymore, probably
because the component doesn't render as frequently anymore.
* Instead a subscriber is added here to update this on changes to the
post. HOWEVER...
* The subscriber runs very often, since Gutenberg stores everything in
one store. This might affect performance if we have heavy validation
logic.
* To make things worse, the editor API allows access to post meta. But
this is not updated (sigh) when the CMB2 boxes are changed. Even now it
still relies on grabbing the metabox's value when you press the save
button, and doesn't update earlier like other things such as post
content or …
> PLANET-6015: Handle post locking in subscriber

- assets/src/styles/campaigns.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6027
---
* These are already loaded in the master theme's CSS. Furthermore
the paths of the icons only work when the styleguide is included through
the master theme.
What happened was that the CSS rule were included a second time, but then from the styleguide in blocks. From there the svg paths don't work, causing the icons to not display. Compare the links to other countries at the end of this page with the test instance https://www.greenpeace.org/international/campaign/climate-emergency/
Deployed on https://www-dev.greenpeace.org/test-sinope/campaign/climate-emergency/ (the missing image there is due to the data sync not using the stateless URL, so unrelated to these changes but maybe something we want to look at)
> PLANET-6027 Don't load icons twice

- assets/src/styles/blocks/CarouselHeaderEditorOverrides.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6030
---
This was increasing the editor width, pushing the sidebar off the right side of the screen.
Probably in WP 5.6 the editor overflow CSS changed. Or maybe one of ouroverrides stopped working, hard to tell what's going on.
**caveat** Does make it display not as nicely as before, but the block is converted to wysiwyg soon anyway. Removing the `100vw` width results in the text sticking to the left side of the carousel, whereas before it was centered.
Fixing it seems non trivial since a lot of factors changed. But if you know how it can be fixed we can include that.
> PLANET-6030 Unset 100vw width of Carousel Header in editor

- .gitmodules
- assets/src/styles/blocks/ENForm/style.scss
- assets/src/styles/campaigns.scss
- assets/src/styles/editorStyle.scss
- assets/src/styles/style.scss
---
Same story as the other styleguide move PRs here, but more files to adjust.
We should probably check for steps so that everyone can easily ignore these folders in their IDE. For me (PHPStorm) it involved marking the entire `master-theme` directory as excluded, then marking the styleguide folder separately as non excluded. You could exclude the whole thing if you only want to see the styleguide files in the master theme itself. Probably works the same way in VSCode.
> PLANET-5983 Theme as submodule

- assets/src/styles/campaigns/themes/_theme_antarctic.scss
- assets/src/styles/campaigns/themes/_theme_arctic.scss
- assets/src/styles/campaigns/themes/_theme_climate.scss
- assets/src/styles/campaigns/themes/_theme_forest.scss
- assets/src/styles/campaigns/themes/_theme_oceans.scss
- assets/src/styles/campaigns/themes/_theme_oil.scss
See https://jira.greenpeace.org/browse/PLANET-6004
This PR fixes the icons in campaigns, in particular their (hover) colors in the different themes.
You can see the fixed links & buttons on [this page](https://www-dev.greenpeace.org/test-leda/links-and-buttons-with-icons/) for example. You can also test the links with the different campaign themes (I added the links all the way at the bottom of the pages):
- [Antartic](https://www-dev.greenpeace.org/test-leda/campaign/antarctic/)
- [Arctic](https://www-dev.greenpeace.org/test-leda/campaign/arctic/)
- [Climate](https://www-dev.greenpeace.org/test-leda/campaign/climate-emergency-template-demo/)
- [Default](https://www-dev.greenpeace.org/test-leda/campaign/default-template/)
- [Forests](https://www-dev.greenpeace.org/test-leda/campaign/forest …
> PLANET-6004 Fix external and pdf link icons in campaigns

- webpack.config.js
This is just to remove a `null` string in the Webpack build logs.
```
[./assets/src/theme/initializeThemeEditor.js] 6.42 KiB {themeEditor} [built]
+ 504 hidden modules
null    <---- this thingy
```
> [No issue]: Check for a truish value in err before logging it

- assets/src/styles/blocks/ENForm/components/_enform-full-width.scss
- assets/src/styles/blocks/ENForm/components/_enform.scss
- public/js/enform_submit.js
- templates/blocks/enform/enform_post.twig
See https://jira.greenpeace.org/browse/PLANET-5984
- Fix required radio/checkbox validation
- Update radio/checkbox color in EN form full-width style for better readability
- Move input error styles to the styleguide
Changes can be tested on [this page](https://www-dev.greenpeace.org/test-venus/required-inputs/) (password is "password")
- [master-theme](https://github.com/greenpeace/planet4-master-theme/pull/1343)
> PLANET-5984 Checkbox/radio validation issues in EN forms

- classes/blocks/class-happypoint.php
Related to: https://jira.greenpeace.org/browse/PLANET-4535
---
Happypoint block doesn't appear on frontend anymore (no display and no mention in the html source), because of a typo in the block name.
Fixing the block name to match what is registered in posts sources ``.
- Create a new post
- Insert a Happypoint with a background image
- on master branch, the block appears in the editor but not in the frontend preview
- on this branch, the block also appears on the frontend
> PLANET-4535: Happypoint is not displayed on frontend

- assets/src/styles/components/VarPicker.scss
- assets/src/theme/VarPicker.js
- assets/src/theme/VariableControl.js
- assets/src/theme/dragElement.js
- assets/src/theme/getMatchingVars.js
- assets/src/theme/groupVars.js
- assets/src/theme/initializeThemeEditor.js
- assets/src/theme/typedControl.js
- assets/src/theme/useServerThemes.js
- assets/src/theme/useThemeEditor.js
- classes/class-loader.php
- classes/rest/class-rest-api.php
---
Allow saving a created theme on the server. This is a very simple implementation using a WordPress option to store a created theme, so that it doesn't only live in the browser local storage.
Also includes some small improvements:
- Fix spacing issues
- Preserve the filename in local storage so it doesn't disappear on reload
- Make gradients also work in color previews
- Fix crash if last clicked element is an SVG (then `className` is an object)
- Hide ugly wp admin bar once theme editor is opened
- Fix broken font size control
- Ensure when loading a theme that the right properties are removed
- Replace font picker with a text field again, as it crashes when the value is not in the list of fonts.
I started adding these changes to …
> PLANET-5983: Simple way to save themes, some small improvements

- package-lock.json
- package.json
- webpack.config.js
---
The previous version of this plugin didn't account for multiple entrypoints. To resolve this the new version now writes to a separate key per entrypoint.
The plugin to combine these and write the file is now also included. Before this was in both repos using this package.
This also disables extracting the variables from the source SCSS files. Nothing was done with the result yet, and probably the same can be achieved directly in the postcss plugin by ensuring the rules source is properly set.
> PLANET-5983: Properly extract vars from multiple files

- assets/src/theme/VarPicker.js
- assets/src/theme/dragElement.js
- assets/src/theme/groupVars.js
- assets/src/theme/typedControl.js
- assets/src/theme/useLocalStorage.js
- assets/src/theme/useServerThemes.js
---
Some small quality of life improvements:
- Scroll the active theme into view when loading server themes
- Remove excessive `console.log`s
- Allow changing the height of server themes, save it in local storage
- Include the "default" theme by default.
- Simple loading state for server themes
- Fix color previews not working for gradients
> PLANET-5983 Theme editor quick UX wins

- assets/src/blocks/Accordion/AccordionEditorScript.js
- assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
- assets/src/blocks/SubPages/SubPagesBlock.js
Ref: https://jira.greenpeace.org/browse/PLANET-6087
---
All 3 blocks are already used in production so we'll move them to the normal "Planet 4 Blocks" category so they stay usable.
> PLANET-6087 Move SubPages, Spreadsheet and Accordion to stable category

- classes/blocks/class-spreadsheet.php
Ref: [JIRA 6072](https://jira.greenpeace.org/browse/PLANET-6072)
---
Fix Sentry error : [PLANET4-RS](https://sentry.greenpeace.org/greenpeace/planet4/issues/1564/)
`Warning: fopen(https://docs.google.com/spreadsheets/d/e/2PACX-1vR2LTvb__ifqY0ayZzqWyzkJGPyMUyUvili9YotHs_1YymJqjSeECFImhzlJfN3k9xw0CVBwR4HuTOg/pub?output=csv): failed to open stream: HTTP request failed! HTTP/1.0 500 Internal Server Error`
> PLANET-6072 Fix Sentry issue: PLANET4-RS

- assets/src/theme/initializeThemeEditor.js
Ref: 
---
Just a quick fix to make it usable when WPML is installed and `document.body.dataset.nro` contains the language suffix. This removes what looks like a language suffix from the end, except for NL (see comment).
> PLANET-5983 Make CSS variables file work with WPML

- assets/src/theme/getMatchingVars.js
- assets/src/theme/groupVars.js
Ref: 
---
Bootstrap variables mostly have no effect for us, and the selectors match a lot of elements. For now it's better to exclude them.
Sort by property name first instead of last, which makes it easier to find things in the list.
Previous ordering:
New ordering:
> Improve ordering and exclude bootstrap variables

- assets/src/styles/campaigns/base/_fonts.scss
- assets/src/styles/campaigns/base/_google_fonts.scss
- assets/src/styles/editorStyle.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6080
---
* Moved to [HTML head in the theme](https://github.com/greenpeace/planet4-master-theme/pull/1364/files#diff-a40ff5ae673d9e734e86aef984e9588608dee8d8e31ee3da3a1a5b845101ea3cR3-R5), so that Cloudflare can optimize them.
* Preserve in a separate file so the editor can still load them.
> PLANET-6080 Move fonts out of CSS file

- assets/src/styles/blocks/Articles.scss
- assets/src/styles/blocks/Columns.scss
- assets/src/styles/blocks/Covers/TakeActionCovers.scss
- assets/src/styles/blocks/ENForm/components/_enform.scss
- package-lock.json
- package.json
- webpack.config.js
---
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/523/files?diff=split&w=1
There are some more to do, but we can already assess this first batch of blocks. Shouldn't be an issue to merge this in multiple chunks.
~~Master theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1325~~ merged
New master theme PR with variables I needed to add because of blocks CSS: https://github.com/greenpeace/planet4-master-theme/pull/1360
Initially my plan was to replicate the existing themes in code. But while doing that I found it's quite clear cut which variables need to be added in most cases, while trying to make a theme work property by property without having the variables yet is a slow process. With the simple way …
> PLANET-5983: Add variables to blocks CSS, part I

- assets/src/blocks/GuestBook/GuestBookBlock.js
- assets/src/blocks/GuestBook/GuestBookFrontend.js
- assets/src/editorIndex.js
- assets/src/frontendIndex.js
- classes/blocks/class-guestbook.php
- classes/class-loader.php
- planet4-gutenberg-blocks.php
See [PLANET-6125](https://jira.greenpeace.org/browse/PLANET-6125)
The "50 Years GuestBook" block should now be available in Planet 4 blocks, and it should show the iframe properly in both the backend and frontend 🙂
If you want to make the iframe full-width, you can add the `block-wide` class in the sidebar in the additional classes!
**Question**: I'm not sure whether showing the actual iframe in the editor is the best, it makes it a bit difficult to select the block (you need to click right above it), maybe we should just show an image of the map there? 🤔 On the other hand it's nice to see how it will look like in the frontend and test the interactive aspect...
> PLANET-6125 Add 50 Years Guestbook block

- assets/src/blocks/Submenu/SubmenuFrontend.js
- assets/src/styles/blocks/Submenu.scss
See https://jira.greenpeace.org/browse/PLANET-6002
Go to a long page with a Submenu block (for example Copyright or maybe Privacy) and make sure that the button doesn't appear when you scroll down.
- https://github.com/greenpeace/planet4-master-theme/pull/1380
> PLANET-6002 Remove Submenu back to top button

- assets/src/styles/blocks/Gallery_carousel.scss
See https://jira.greenpeace.org/browse/PLANET-6105
I'm not sure why we were changing the z-index value for the arrows 🤔 they seem to work just fine with the original Bootstrap value. Our override was causing the "next" button to show on top of the indicators, and therefore clicking on the indicators was actually clicking on the button, hence the broken behaviour.
Add a Gallery block, carousel style, with 3 or more images and make sure the indicators and the prev/next buttons work as intended.
- [Broken example](https://www.greenpeace.org/international/act/sail-aboard-a-greenpeace-ship/)
- [Fixed example](https://www-dev.greenpeace.org/test-iocaste/story/46720/since-fukushima-disaster-decade/)
> PLANET-6105 Remove GalleryCarousel arrows z-index to fix indicators

- assets/src/components/Sidebar/CampaignSidebar.js
- assets/src/components/Sidebar/LegacyThemeSettings.js
- assets/src/components/Sidebar/PostParentLink.js
- assets/src/components/fromThemeOptions/fromThemeOptions.js
Ref: https://jira.greenpeace.org/browse/PLANET-6136
---
I first wanted to rewrite to hooks in one go, since this is the most confusing class components we have. However it's too complex to do at once.
This PR does a few low hanging fruit improvements that are easy to review without needing to go too much into the more confusing parts.
The most confusing being the 2 tightly coupled HOCs WithPostMeta and FromThemeOptions. I'm not sure yet at this point whether we want to try "save" the logic in them that handles the "theme field dependencies" (see [this added code comment](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/588/files#diff-0a557c7b06bf5a384f50fa0e07bbb3e59ba232e788d9125e74ddad2f20ce013aR7-R11)).
For now the purpose of the Jira ticket is just to have some way …
> PLANET-6136 Make legacy sidebar code manageable

- assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
- assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
- assets/src/blocks/CarouselHeader/CarouselHeaderStaticContent.js
- assets/src/blocks/CarouselHeader/useSlides.js
- assets/src/styles/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss
- assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
See https://jira.greenpeace.org/browse/PLANET-6119
**Frontend** (mobile/tablet)
- On scroll, it blocks the page
- I am not really able to change to the next slide
- The description and title are not visible
- The selectors indicating on which slide we are are very low on the page, there is a big space between the image and those selector
**Backend**
- Not able to see the menu b/c of the block above (only happens if previous block is the "old" carousel header, which should never happen anyway)
- Maybe the arrow from description can be moved so it does not overlap with the field
- The space where the editor needs to click to write the CTA is very small
You can check the fixes on [this page](https://www-dev.greenpeace.org/test-rhea/carousel-header-new-wysiwyg/) for example
> PLANET-6119 Improve CarouselHeader WYSIWYG after UAT feedback

- assets/src/blocks/Articles/ArticlePreview.js
- assets/src/blocks/Articles/ArticlesList.js
Ref: no dedicated ticket
---
These 2 things are causing the same warnings each time the block is rendered, which gets in the way of debugging other console output. The `srcset` should probably be further investigated, since we always want to use it, but for some reason it's `false` sometimes.
> Prevent console flooded by warnings

- assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
- assets/src/blocks/Spreadsheet/SpreadsheetEditorScript.js
- assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
- assets/src/blocks/Spreadsheet/SpreadsheetScript.js
- assets/src/editorIndex.js
- assets/src/frontendIndex.js
- assets/src/styles/blocks.scss
- assets/src/styles/blocks/Spreadsheet/SpreadsheetStyle.scss
- classes/blocks/class-base-block.php
- classes/blocks/class-spreadsheet.php
- webpack.config.js
Ref: https://jira.greenpeace.org/browse/PLANET-6156
Split Spreadsheet scripts to only be loaded when a block is present on the page.
[Spreadsheet block](https://planet4.greenpeace.org/act/block-spreadsheet-table/#spreadsheet-block) should work as expected
- After pulling this PR, rebuild JS and CSS assets
- Add a spreadsheet to a page
- Use this doc for test https://docs.google.com/spreadsheets/d/e/2PACX-1vQz5nftk5gXiehFtdxLokvInQ4au5vAMdslL--x6RMawo8Y4NgXBOlx26PzWy9heM4hytv67FkkKg4T/pubhtml
- Spreadsheet should appear on frontend and in editor as usual, with proper styling
- You can see scripts being loaded independently for Spreadsheet in you console network tab, in the editor and on the frontend
For this split I checked bits webpack imported in the compiled file that are used elsewhere …
> PLANET-6156: Split Spreadsheet block scripts

- assets/src/blocks/Cookies/CookiesFrontend.js
Ref: https://jira.greenpeace.org/browse/PLANET-6155
---
As a preparation step for adding HubSpot support to the cookies block, this converts the block from class components to function components and hooks.
The block currently uses a less known feature of classes (adding a callback function to `this.setState`) to set certain cookies as an "effect" when the state changes. This effect will need to be expanded to also trigger HubSpot cookie consent, which is much easier to achieve with `useEffect`.
I probably will also split the hooks conversion in 2 PRs. Currently on this branch I have a few commits that simplify the class which could already be merged, after which the rest should be easier to review.
> PLANET-6155 Convert cookies block to hooks part I

- assets/src/blocks/Cookies/CookiesFrontend.js
- assets/src/blocks/Cookies/useCookie.js
Ref: https://jira.greenpeace.org/browse/PLANET-6155
---
**Easier to review [with hidden whitespace changes](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/601/files?diff=split&w=1)**
The actual conversion. I added a `useCookie` hook to encapsulate reading and writing the cookie. `no_track` cookie doesn't use it because we only ever need to write it.
Also renamed `setCookie` to `writeCookie`, because of a naming collision. Though after doing so the colliding other function was moved, so it could theoretically stay `setCookie`. But we can keep `writeCookie` to avoid confusion with setter methods returned by `useState`.
> PLANET-6155 Convert cookies block to hooks part II

- assets/src/blocks/Cookies/CookiesFrontend.js
Ref: https://jira.greenpeace.org/browse/PLANET-6155
---
We want to ensure HubSpot consent matches our cookie settings. How exactly that will work I still need to figure out. It's not something that's directly supported by the plugin.
My current guess it we'll have to add a filter to block loading the JS unless the cookie is already present in the back end. Then on the front end we need to load the script when consent is given.
Once the HubSpot code is loaded, we can trigger a consent revoke by pushing a `revokeConsent` event. Still need to find out if this is sufficient or if the current page could continue tracking. The next page load should then not load HubSpot code again.
> PLANET-6155 Wire up HubSpot consent with our cookie consent mechanism

- assets/src/styles/blocks/core-overrides/Table.scss
Ref: 
Fixes https://github.com/greenpeace/planet4/issues/136
The change makes the table caption style same as the image caption style. Please review
> PLANET-5868: Make table caption styles same as image caption

- assets/src/blocks/Accordion/AccordionEditor.js
- assets/src/blocks/Articles/ArticlesEditor.js
- assets/src/blocks/Columns/ColumnsEditor.js
- assets/src/blocks/Columns/EditableColumns.js
- assets/src/blocks/Cookies/CookiesFrontend.js
- assets/src/blocks/Counter/CounterEditor.js
- assets/src/blocks/Covers/CoversEditor.js
- assets/src/blocks/Gallery/GalleryEditor.js
- assets/src/blocks/Media/MediaEditor.js
- assets/src/blocks/Submenu/SubmenuEditor.js
- assets/src/blocks/Timeline/TimelineEditorScript.js
Ref: https://jira.greenpeace.org/browse/PLANET-6172
---
Most of the blocks have a title and a description. This changes removes formatting options from title and adds them on description. For now this is just bold and italic. Links are still [not supported properly from WP](https://github.com/WordPress/gutenberg/issues/11599).
Used `allowedFormats` everywhere, instead of `formattingControls`, for consistency but also because `formattingControls` is [being deprecated](https://github.com/WordPress/gutenberg/blob/641f1c70af8ffd466b4adf20b29e7a4a839fc1e8/packages/block-editor/CHANGELOG.md#new-features-2).
Additionally we add these rules on specific blocks:
**Accordion**
Headline: Disallow
Text: Allow
**Carousel Header**
Disallow everywhere
**Columns**
Column Header: Disallow
Column …
> PLANET-6172 Allow basic rich text formatting on blocks description fields

- assets/src/blocks/Articles/ArticlePreview.js
- assets/src/styles/blocks/Articles.scss
Ref: 2/2 of https://github.com/greenpeace/planet4/issues/114
Sibling PR: https://github.com/greenpeace/planet4-master-theme/pull/1367
1. Add the bullets into the ArticlePreview component so that we can hide them from the screenreader (tested on MacOS VoiceOver) ✅
2. Hide the `#` that appears in the ArticlePreview component from the screenreader ⁉️
- I wanted to push back on this one a little bit. It seems that we are already marking this symbol with the `aria-label="hashtag"` which seems appropriate for the screenreader to read. Not totally against removing it, but wanted to double check that we really _do_ want to remove it first.
None that I can see
---
> add bullets in jsx with aria-hidden to article preview

- assets/src/blocks/Columns/Columns.js
- assets/src/blocks/Covers/CampaignCovers.js
- assets/src/blocks/Covers/ContentCovers.js
- assets/src/blocks/Gallery/GalleryCarousel.js
- assets/src/blocks/Gallery/GalleryGrid.js
- assets/src/blocks/Gallery/GalleryThreeColumns.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsInPlaceEdit.js
- templates/blocks/campaign_covers.twig
- templates/blocks/carousel_header_full-width-classic.twig
- templates/blocks/content_covers.twig
- templates/blocks/social_media_cards.twig
- templates/blocks/take-action-boxout.twig
Previously, the global.js adds the image title attribute with alt text. To remove jQuery from global.js, drop the gobal.js and add img title at source.
Ref: [JIRA 5757](https://jira.greenpeace.org/browse/PLANET-5757)
---
Related PR: https://github.com/greenpeace/planet4-master-theme/pull/1395
> PLANET-5757 Add image title attribute

- assets/src/blocks/OldENForm/ENForm.js
- assets/src/blocks/OldENForm/ENFormBlock.js
- assets/src/editorIndex.js
- assets/src/styles/blocks.scss
- assets/src/styles/blocks/OldENForm/campaigns/_campaign_enform.scss
- assets/src/styles/blocks/OldENForm/campaigns/_mixins.scss
- assets/src/styles/blocks/OldENForm/campaigns/themes/_theme_climate.scss
- assets/src/styles/blocks/OldENForm/components/_enform-full-width-bg.scss
- assets/src/styles/blocks/OldENForm/components/_enform-full-width.scss
- assets/src/styles/blocks/OldENForm/components/_enform-side-style.scss
- assets/src/styles/blocks/OldENForm/components/_enform.scss
- classes/blocks/class-oldenform.php
- classes/class-loader.php
Ref: https://jira.greenpeace.org/browse/PLANET-4814
In preparation for https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/453 to move to beta, moving the current block to "old" name.
ENForm block should work the same
- Check existing blocks in Block usage
- Add a block ENForm to a page, select Goal and Form, check that form displays as expected
> PLANET-4814: Move ENForm to "old"

- assets/src/blocks/Gallery/GalleryCarousel.js
- assets/src/blocks/Gallery/GalleryFrontend.js
- assets/src/blocks/Gallery/getCaptionWithCredits.js
- assets/src/blocks/Gallery/getImageTitle.js
Ref: https://jira.greenpeace.org/browse/PLANET-6196
Image credits are not displayed in the Gallery block for the Slider version. (other versions don't display any text)
Exporting `getImageTitle()` function to use for frontend/backend and Lightbox data.
- Add a gallery to a post/page
- Use images that have a completed `credits` field
- On the Slider version of the gallery, credits should appear at the end of the image caption, on backend and frontend
> PLANET-6196: Add credits to image caption in Slider Gallery

- assets/src/styles/blocks/Media.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6197
Related to https://github.com/greenpeace/planet4-master-theme/pull/1399
Removing fixed min width for embed blocks, to allow them to adapt to smaller width.
Blocks adapt to width, as they usually include their own min-width.
See https://github.com/greenpeace/planet4-master-theme/pull/1399 for full description
> PLANET-6197: Fix width of embed block on mobile

- assets/src/blocks/Accordion/AccordionEditor.js
- assets/src/blocks/Accordion/AccordionFrontend.js
- assets/src/blocks/Articles/ArticlesFrontend.js
- assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
- assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
- assets/src/blocks/CarouselHeader/deprecated/carouselHeaderV1.js
- assets/src/blocks/Columns/ColumnsEditor.js
- assets/src/blocks/Columns/ColumnsFrontend.js
- assets/src/blocks/Cookies/CookiesFrontend.js
- assets/src/blocks/Counter/CounterFrontend.js
- assets/src/blocks/Covers/CoversEditor.js
- assets/src/blocks/Covers/CoversFrontend.js
- assets/src/blocks/Gallery/GalleryEditor.js
- assets/src/blocks/Gallery/GalleryFrontend.js
- assets/src/blocks/Gallery/getGalleryLayout.js
- assets/src/blocks/Happypoint/HappypointFrontend.js
- assets/src/blocks/Media/MediaFrontend.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsInPlaceEdit.js
- assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
- assets/src/blocks/Submenu/SubmenuEditor.js
- assets/src/blocks/Submenu/SubmenuFrontend.js
- assets/src/blocks/Submenu/getSubmenuStyle.js
- assets/src/blocks/Timeline/TimelineEditorScript.js
- assets/src/blocks/Timeline/TimelineFrontend.js
- assets/src/blocks/getStyleFromClassName.js
- classes/blocks/class-splittwocolumns.php
Ref: https://jira.greenpeace.org/browse/PLANET-6147
The style name extraction method generates issues with the "additional classes" field.
Additional classes are also not included in the resulting blocks, except when the current bug extracts a style and if those additional classes are placed after the style class name.
Currently, for a Columns block with style `tasks`, an additional class `is-style-tasks` is included. If we edit the additional class to `foo is-style-tasks bar`, the column will end up with classes `block-style-tasks bar`. This is because the code splits the classname string on `is-style-`, keeps everything that is after it (so `tasks bar`) and concatenate to `block-style-`. 
Other blocks simply don't have these additional CSS classes included on their container section. …
> PLANET-6147: Fix missing and breaking classes on blocks

- assets/src/styles/blocks/core-overrides/BlockSpacing.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5003
> When using lists `<ul><ol>` in Pages, for both Default and Evergreen templates, there appears to be additional spacing below the list. Additionally, there is no spacing within the list itself. The expected behaviour would be what appears on Posts.
Margins between paragraphs collapse, but not between paragraph and list, so it looks larger.
List items only have a padding in posts, and no margin. 
Diff is a bit confusing, but:
- I removed duplicated rules (on margins) between the first 2 declarations
- Removed margin associated to `ul` tag, so we can use margin collapse of `li` instead and not conflict with other blocks margins
- Removed list specific margin/padding for articles in …
> PLANET-5003: Fix spacing inconsistencies in lists

- public/js/enform_submit.js
See https://jira.greenpeace.org/browse/PLANET-6212
Sometimes the following statement: `$(this).attr('required') && !formValue && 'radio' !== $(this).attr('type')` would still be true despite the mandatory checkbox being checked as intended, which caused the error to show and blocked the form submission. So the fix was to check there that the field was not only not a radio but also not a checkbox, by using `!['checkbox', 'radio'].includes($(this).attr('type'))` instead.
I've also added parenthesis around the different `&&` statements to make sure they are interpreted correctly and not mixed up with the `||` ones.
You can create an EN form and with a mandatory checkbox opt-in field (on my local I used the first available opt-in in the list with id 3887, might be different for you depending …
> PLANET-6212 Fix mandatory checkboxes in EN forms

- assets/src/styles/blocks/Socialmedia.scss
- templates/blocks/social-media.twig
**Description**
PLANET-4460: Set Social media block min and max width to Facebook Page
Ref: https://jira.greenpeace.org/browse/PLANET-4460
If you think this issue as an easy fix, my answer is yes! I completely agree with you. 
However, I was leading a lot to this issue finding the best solution but I'm sure that what I've done is not the best approach, but honestly, I don't think we could do more than this.
**Why?**
- Because the plugin neither allow resizing the `iframe` and nor div's width. [Check it out this](https://developers.facebook.com/support/bugs/2203165469736837/)
- Because it's a SSR Component and you cannot change it's render logic at runtime and its fully logic comes from the server. It doesn't have any lifecycle methods (to re-render). 
- Using this plugin as a SSR disallow …
> PLANET-4460 Set Social media block min and max width to Facebook Page

- assets/src/blocks/Articles/ArticlesBlock.js
Ref: [JIRA 6040](https://jira.greenpeace.org/browse/PLANET-6040)
---
**Issue:**
- While editing the articles block in block editor, it throws a "Block validation failed" error.
**How to reproduce?**
- Add a new articles block on page/campaign, insert “articles description” save/publish page.
- Here on page refresh, error reproduces.
The console error log shows a difference in “Content generated by `save` function” and “Content retrieved from post body”
**Fix :**
~~- Added a fix which sort attributes in `FrontendRenderOrdered.js` file.~~
- Added migration script in [other PR](https://github.com/greenpeace/planet4-master-theme/pull/1402), and as per discussion in current PR comment updated the [ArticlesBlock.js](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/546/files#dif …
> PLANET-6040 Fix articles block, Block validation error

- package-lock.json
- package.json
- webpack.config.js
Ref: https://jira.greenpeace.org/browse/PLANET-5662
We can merge this before https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/603, then we should be able to remove the webpack changes from that PR and rebase. After that it should be mergeable :crossed_fingers: But before we proceed with that PR, we need to sync with @oekeur to see if this requires changes from their part. Probably they will have to mimic our alias config in both webpack and imports.
* This is needed because we want to have separate aliases for public and
admin JS, so that we can use Preact for the former and WP's bundled
React for the latter.
* Also split off the CSS config, because we can. All config in the
previous mixed object was either applying to JS or to CSS, never to
both.
* Include blocks' …
> PLANET-5662 Split webpack into multiple configs

- assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
- assets/src/styles/blocks/Spreadsheet/SpreadsheetStyle.scss
- Ensure column sorting is tab-accessible by enclosing the header text
and sort icon in a button. Note that I am keeping the rest of the
table header clickable, since this will ensure a larger click area.
- Use the table header text as the title
- Add a scope attribute
Ref: Fixes https://github.com/greenpeace/planet4/issues/120
---
> A11y: Address accessibility of spreadsheet block

- assets/src/blocks/Columns/Columns.js
- assets/src/blocks/Columns/ColumnsEditor.js
Fix the "open in a new tab" functionality for external domains on <a> selectors.
Also fixed this functionality on `headings` and `images`
Issue found [here](https://www-dev.greenpeace.org/test-sinope/columns-with-links/)
Issue replicated and solved [here](https://www-dev.greenpeace.org/test-titan/columns-with-links/)
Issue replicated and solved (with images) [here](https://www-dev.greenpeace.org/test-titan/29060-2/)
Linked PR https://github.com/greenpeace/planet4-master-theme/pull/1411
Ref: https://jira.greenpeace.org/browse/PLANET-6124
> PLANET-6124: Fix the "open in a new tab" functionality through from settings

- .circleci/config.yml
To make the CI config more readable, moving the PR check into its own script in the circleci container.
Same for the `requests_oauthlib`. It's now already installed.
Has to be merged after https://github.com/greenpeace/planet4-circleci/pull/53
> Move PR check in a script

- .circleci/config.yml
* Provide easier to read job output by splitting steps.
* Set environment variables in job definition.
Ref: 
---
> Split steps and unify shared env definition

- assets/src/components/Sidebar/CampaignSidebar.js
- assets/src/components/Sidebar/LegacyThemeSettings.js
- assets/src/components/Sidebar/NewThemeSettings.js
- classes/class-loader.php
- package-lock.json
- package.json
- templates/blocks/css_variables.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6136
---
This PR makes it possible to use a theme that was created with the experimental theme editor on a campaign. The theme name is still stored in the same meta field.
To make it possible to use the same options as one of the legacy themes, you can create a theme with the same name but `-new` appended, in which case those sidebar options are loaded. This is not intended to be used by end users, just an easy way for us to ensure the same options still work on the newer version.
As a bonus, it also includes the code needed to apply the theme's variables in the post editor. I didn't intend to do that, but it didn't require a lot of changes. It doesn't work 100% of the time, since not all front end CSS is used in the editor. But most things …
> PLANET-6136 Add select for new themes

- assets/src/styles/blocks/Articles.scss
- assets/src/styles/blocks/Columns.scss
- assets/src/styles/blocks/Covers/ContentCovers.scss
---
Some variables that are needed to reproduce the themes. CSS structure is still the same, so these changes should be safe. Except for a redundant color rule on ContentCovers which was removed.
It would be better if we clean up the block styles, currently they're very nested. But I added the variables to this structure anyway, since it's the only thing blocking us from removing the legacy.
Somewhat easier [without whitespace changes](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/628/files?diff=split&w=1)
> Add CSS variables to Articles, Columns and Covers

- assets/src/styles/blocks/Columns.scss
* As the markup is always matching this query. At smaller sizes the whole thing is hidden and other markup is shown.
* This in turn allows to substitute any declaration that was overridden by the large-and-up media query.
* Also remove some things that didn't do anything.
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/640/files?diff=split&w=1
For now I didn't add any new variables. However because the media query was removed, and some variables were in it, it changes the names (to not include the media query).
Example page on test instance with Columns tasks style: https://www-dev.greenpeace.org/test-uranus/act/plastic-free-nz-2/plastic-free-nz/isthisyours/
Ref:
> Remove large-and-up media query of Columns tasks

- assets/src/styles/blocks/Counter.scss
- assets/src/styles/blocks/OldENForm/components/_enform.scss
- package-lock.json
- package.json
---
This is the last batch of variables needed for themes. I also bumped the theme editor package to a newer version that fixes bugs and adds custom controls for many CSS properties.
All CSS changes are only adding variables and not changing the structure, so these changes should be safe. I changed one variable name (to use the shorthand), which I will update in the single theme (and page) that uses it.
> Some more blocks variables (ENForm and Counter), bump theme editor

- assets/src/blocks/Covers/TakeActionCovers.js
- assets/src/styles/blocks/Covers/layouts/TakeActionCovers.scss
- assets/src/styles/blocks/OldCovers/TakeActionCovers.scss
I've implemented the new designs only for the WYSIWYG version of the block, by adding `-new` to its classes which we'll be able to remove once we remove it from from beta blocks. That way existing blocks should not be affected, and we can merge these changes despite not being ready to merge the related changes for the post page designs.
See https://jira.greenpeace.org/browse/PLANET-5608
I've set up a [page](https://www-dev.greenpeace.org/test-iocaste/new-take-action-covers/) for UAT, but you can also test it on local by creating a new "Covers (beta)" block and selecting the "Take Action covers" style. You can also check the non-WYSIWYG Covers block to make sure that it isn't affected by the changes!
> PLANET-5608 Implement new Take Action cover designs

- assets/src/components/Sidebar/LegacyThemeSettings.js
- assets/src/components/Sidebar/NewThemeSettings.js
Ref: https://jira.greenpeace.org/browse/PLANET-6362
This PR does the following:
- Add refactored versions of themes as options of the existing dropdown, and suffix the old theme with `(old)` to remove confusion.
- Exclude these themes from the new themes dropdown (only relevant for test instances which might have a theme with the same name in the options).
- Remove some console logs
To test:
You can switch all content using the old theme to the new version and it should look identical, except for minor spacing changes or over-use of capitalization that was not preserved. Needs to be tested together with https://github.com/greenpeace/planet4-master-theme/pull/1435, else the themes won't exist.
I deployed the latest version to GPI, where I'm currently switching all campaign pages (that use …
> PLANET-6362 Add new version of themes

- assets/src/blocks/Accordion/AccordionEditor.js
- assets/src/blocks/Articles/ArticlesEditor.js
- assets/src/blocks/Columns/ColumnsEditor.js
- assets/src/blocks/Columns/EditableColumns.js
- assets/src/blocks/Cookies/CookiesFrontend.js
- assets/src/blocks/Counter/CounterEditor.js
- assets/src/blocks/Covers/CoversEditor.js
- assets/src/blocks/ENForm/ENFormInPlaceEdit.js
- assets/src/blocks/Gallery/GalleryEditor.js
- assets/src/blocks/Media/MediaEditor.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsInPlaceEdit.js
- assets/src/blocks/Submenu/SubmenuEditor.js
* For some reason this was added to many RichText components, even
though they don't have this prop. So the only effect it had was cause a
whole lot of warnings flooding the console.
* This was copied from a component that was using the
`withCharacterCounter` HOC, that adds the counter and warnings around a
component. Don't use that component, HOCs are legacy, but we still need
to rewrite it. If we need to add a character counter in some places, we
should first rewrite the HOC.
Ref: No ticket, it only prevents warnings and removes non-functioning code.
> Remove characterLimit prop that only results in console warnings

- assets/src/blocks/Cookies/CookiesBlock.js
- assets/src/blocks/Cookies/CookiesFrontend.js
- classes/blocks/class-cookies.php
- classes/class-loader.php
Show analytical cookies checkbox option, if Planet4 'enable_analytical_cookies' setting is 'on'
Ref: [JIRA 6253](https://jira.greenpeace.org/browse/PLANET-6253)
---
Related [PR](https://github.com/greenpeace/planet4-master-theme/pull/1438) in master theme repo. 
|Posible cookies selection|Cookies value|Action|
|--------------|--------------|--------------|
|Necessary cookies|1||
|Marketing cookies|2|On checked also select Necessary cookies|
|Necessary & Analytical cookies|3|On checked also select Necessary cookies|
|Necessary & Marketing cookies|2||	 
|Necessary & Analytical & Marketing cookies|4||
**Task:**
- As per the Planet4>>Cookies text>>"Enable Analytical Cookies" setting, display analytical cookies checkbox option on frontend and backend of Cookies block
- Update cookies values on …
> PLANET-6253 Add analytical cookies option in cookies block

- assets/src/blocks/Cookies/CookiesFrontend.js
* This caused the cookie to be set just by going to the privacy page,
without seeing the block (it's below the fold).
Ref: 
---
> Remove cookie that gets set on render

- planet4-gutenberg-blocks.php
This enables Hubspot plugin Gutenberg block that simplifies adding a form.
It doesn't seem to create any issue when the plugin is missing.
> Enable Hubspot form block

- assets/src/styles/blocks/Counter.scss
- assets/src/styles/blocks/ENForm/components/_enform-side-style.scss
- assets/src/styles/blocks/OldENForm/components/_enform-side-style.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6362
Add a few variables needed to style the counter block in ENForm style. These are used in https://github.com/greenpeace/planet4-master-theme/pull/1441/files for the "climate" theme.
> Allow theming counter block spacing and display

- assets/src/components/Sidebar/CampaignSidebar.js
- assets/src/components/Sidebar/NewThemeSettings.js
- assets/src/styles/editorFonts.scss
- assets/src/styles/editorStyle.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6363
---
Previously the logic to set the theme variables was only triggered when the sidebar is open. With this change it's always run on page load because the `CampaignSidebar` component is always created when loading the editor.
Unfortunately the sidebar code still needs cleaning up, so I had to squeeze it into some already complex code. The sidebar needs to be entirely rewritten anyway, because it still uses class components and does some weird stuff, so I guess this can be improved at that point.
To test: With this change you should see the theme applied in the editor when you open a page, regardless of which sidebar is open. There could be a small delay before you see the styles applied.
> Set theme variables on page load

- tests/acceptance/ENFormCest.php
To fix an error with the latest version of wp-browser, this argument needs to be escaped.
[`Error: Too many positional arguments: 11119999}`](https://app.circleci.com/pipelines/github/greenpeace/planet4-base/1105/workflows/ab53d2cf-9111-407e-beda-d8eac7cee690/jobs/6561/steps)
This PR comes to fix an issue following https://github.com/greenpeace/planet4-base/pull/145, and has to be merged before the planet4-base one.
This issue appears because we have to update our version of `wp-browser`, to use the one that fixes the dependency issue. This new version has changed its wp-cli dependency https://github.com/lucatume/wp-browser/releases/tag/3.0.0 , which might explain the necessity to escape arguments now.
Acceptance tests, of course, can't pass, because of the wp-browser issue :grimacing:
> Fix cli command in test for wp-browser update

- assets/src/components/Sidebar/CampaignSidebar.js
- assets/src/components/fromThemeOptions/fromThemeOptions.js
Ref: 
---
I started a PR to rewrite the `LegacyThemeSettings` component to hooks. These changes can be merged before that to reduce the footprint of that PR (it will already touch many lines :sweat_smile: ).
All I did was extract complex logic from the `handleThemeSwitch` function, so that it's clear what it does. I preserved the weird parameters for now because they are coupled with the HOCs that will be replaced in the next PR.
This function detects which theme settings are not available anymore after switching to another theme, and switches them to `null` or their default value.
> Extract complex theme switching logic to separate functions (preparation before converting to hooks)

- assets/src/blocks/CarouselHeader/deprecated/carouselHeaderV1.js
Before this fix, adding an empty CarouselHeader block to a page would cause it to crash on reload because the slides attribute was undefined in `carouselHeaderV1`
> Fix empty CarouselHeader page crash

- assets/src/styles/blocks/Submenu.scss
- assets/src/styles/blocks/SubmenuEditor.scss
The sidebar style of the Submenu block should be on the left instead of the right for RTL sites. This commit also updates the margin values to 16px instead of 15px, to be consistent with our new 8px spacing system.
Add a Submenu block with the "Short sidebar" style on a relatively long page with headers for it to be displayed (usually Privacy or Copyright pages work fine 👌). Then add dir="rtl" to the `html` element of the page and make sure the block behaves as expected both in the editor and in the frontend.
> Add RTL css to Submenu block

- assets/src/styles/blocks/SocialMedia/SocialMediaEditorStyle.scss
- webpack.config.js
See https://jira.greenpeace.org/browse/PLANET-6239
Sometimes blocks with alignment overlap in the editor, making it difficult for editors to update them. I've tested all blocks (including the Image one which also has alignment options) and this actually only seems to occur with the SocialMedia block, hence why this PR only fixes this one.
On local you can add several SocialMedia blocks in a row on a page, with different alignment values, and make sure that they never overlap in the editor. Otherwise you can check the broken/fixed versions on the test instances:
- [Broken](https://www-dev.greenpeace.org/test-sinope/social-media-wysiwyg-tests/)
- [Fixed](https://www-dev.greenpeace.org/test-rhea/social-media-block-alignment-tests/)
> PLANET-6239 Fix block alignment issues in the editor

- assets/src/components/Sidebar/CampaignSidebar.js
- assets/src/components/Sidebar/LocalThemeSettings.js
- assets/src/components/Sidebar/ThemeSettings.js
Ref: 
---
Following name corrections:
- `LegacyThemeSettings` => `ThemeSettings`: These are now not legacy themes anymore, so the previous distinction between both dropdowns does not make sense anymore.
- `NewThemeSettings` => `LocalThemeSettings`: "local" because these themes only exist "locally" on the site in the database.
- More accurate title of "Theme Settings" for the sidebar.
> Use accurates names for different types of theme settings in UI and code

- package-lock.json
- package.json
Contains various UI improvements:
* Put property name first.
* Remove "collapse" toggle.
* Allow manual input. For example for non-clickable elements like `.skewed-overlay`.
* More compact controls.
* Fix stored position of editor not being applied on page load,
Changes: https://github.com/Inwerpsel/use-theme-editor/compare/1a2cce6da66958d3962ee9db2d74814626c9dc03..5e84c35dc84c41115dbd680996bbbeae3b6f43ec
> Bump use-theme-editor package

- assets/src/BlockEditorValidation.js
* The editor crashed on this code for me because it received `null` for
the block. It happened on WordPress 5.8, but that could be coincidence.
* I was undoing multiple edits involving a Query Loop block and can't
remember which particular one triggered the crash. Haven't managed to
reproduce the issue.
Ref: No ticket
> Prevent rare crash where block is null

- classes/class-loader.php
- planet4-gutenberg-blocks.php
WordPress was so nice to deprecate a function and only introduce the alternative within the same version. To be able to fix the notice in advance, the code needs to be written to check the WP version and add the appropriate filter.
> Check version and conditionally use new filter introduced in 5.8

- planet4-gutenberg-blocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-6307
---
- `block_categories` replaced by `block_categories_all`
- `allowed_block_types` replaced by `allowed_block_types_all`
- `allowed_block_types_all` passes the context, so a minor code change was needed.
- Removed commented blocks, since this outdated anyway. Linked to the upstream codebase.
> PLANET-6307 Replace WP 5.8 deprecations

- package-lock.json
- package.json
This was fixed in the package previously, but still needed to be bumped here.
To test, inspect an element that uses variables on any page of the test instance, and control + click on a CSS rule that has a generated variable (in Chrome). This should open the sources panel with the right line for the variable selected.
relevant changes: https://github.com/greenpeace/planet4-dashdash/commit/a265f9d64eaea6e1acbf10c7a0e0fec379e796e3#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R72 
Ref: 
---
> PLANET-6225 Fix source maps for generated CSS variables

- assets/src/styles/blocks/Accordion/AccordionStyle.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6456
---
- Replacing `angle-right` icon with the new `chevron`.
- Unified `mask-image` attributes, same as the other icons code.
> PLANET-6456 Replace Accordion arrow icon

- public/js/post_action.js
* Remove direct descendant selector as there's just one item with that
ID.
* Remove extra classes check which was only needed for an AB test.
Ref: https://jira.greenpeace.org/browse/PLANET-6455
> PLANET-6455 Ensure boxout always scrolls

- public/js/load_more.js
* The previous mouseup and touchend events do not fire when enter or
space is pressed on the focused button.
* Click still works for the previous, and also for keyboard.
I found this while working on the focus states for buttons. Technically it's not needed to fulfill that ticket, however it makes little sense to be able to focus a non working button.
Ref: https://jira.greenpeace.org/browse/PLANET-6460
> PLANET-6460 Use click to ensure keyboard accessibility on Covers load more

- assets/src/blocks/Articles/ArticlePreview.js
- assets/src/styles/blocks/Articles.scss
ATTENTION: The focus state on the [test instance](https://www-dev.greenpeace.org/test-pandora/) still causes layout jumps, which is being addressed in https://github.com/greenpeace/planet4-master-theme/pull/1500/files
* `d-flex` is not needed and broke the display of the link around it.
* Ensure focus around image nicely uses the borders. Without block there
was a protrusion caused by the link being wider but narrower than the
image it contains.
> Fix display and focus of Articles image link

- assets/src/styles/blocks/Covers/layouts/TakeActionCovers.scss
- assets/src/styles/blocks/OldCovers/TakeActionCovers.scss
* This caused a regression on GPNL, where it started overriding their
child theme rule.
Ref: https://jira.greenpeace.org/browse/PLANET-6464
> PLANET-6464 Remove highly specific text color rule on boxout that caused regression in GPNL child theme

- assets/src/styles/blocks/Gallery_carousel.scss
* This was first in master theme, and removed there but the PR was
merged too early, which breaks stuff in master. Instead we can add it
back in its only usage and we won't need another master theme PR.
see https://github.com/greenpeace/planet4-master-theme/pull/1506
> Add Carousel indicator color variable in repo where it's used

- .circleci/config.yml
- bin/install-wp-tests.sh
- composer.json
- composer.lock
We can fetch the WP version from the base repo. It's a bit hackish but it allows us to avoid hardcoding a WP version here (which we'll probably forget to ever update).
Added also `yoast/phpunit-polyfills`, required by `5.8.2`.
- [Job running on this PR](https://app.circleci.com/pipelines/github/greenpeace/planet4-plugin-gutenberg-blocks/5333/workflows/1bf54da5-91aa-4e08-aeaf-99d4641c4b56/jobs/23176) (expand `phpunit` job): Wordpress version is `5.8.1` (despite having `latest` on the script)
- [Job running with 5.8.2](https://app.circleci.com/pipelines/github/greenpeace/planet4-plugin-gutenberg-blocks/5330/workflows/0ec56ef0-1cfa-4c72-b3a8-21666fabda78/jobs/23165) (expand `phpunit` job): Tests are now passing, since we install the polyfills.
> Make sure unit tests run on the right WP version

- assets/src/blocks/CarouselHeader/Caption.js
- assets/src/styles/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss
- assets/src/styles/blocks/SplitTwoColumnsEditor.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6430
> Seems like for the folks on macs the button label on the carousel block is not editable in Safari
Change editable button to a div so that Safari issues on links related to pointer events and user selection can't happen.
Change overflow strategy to limit the ellipsis effect in the editor.
You need __Safari on MacOS__ to test this issue.
Has to be tested with https://github.com/greenpeace/planet4-master-theme/pull/1510
- Edit a page, add a Carousel header, try to edit the CTA button text:
- On main branch, clicking on the CTA button doesn't have any effect,
- With this branch, a click makes a caret appear and text is editable.
> PLANET-6430: Carousel Header - CTA button is not editable in Safari

- assets/src/blocks/CarouselHeader/CarouselControls.js
- assets/src/blocks/Columns/ColumnsFrontend.js
- assets/src/blocks/Gallery/GalleryEditor.js
- assets/src/blocks/Gallery/GalleryFrontend.js
- assets/src/blocks/Gallery/GalleryGrid.js
- assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
- assets/src/styles/blocks/Gallery/styles/GalleryCarousel.scss
See [PLANET-6091](https://jira.greenpeace.org/browse/PLANET-6091)
- There used to be a small width difference between the CarouselHeader slides content and the rest of the page content.
- The Columns block also used to be slightly different because its content was put outside of the `container` div.
- The Gallery block was missing the `container` block.
We also need to update the donation pages, there is another [PR](https://github.com/greenpeace/planet4-en-petitions/pull/8) for that.
Main PR: [master-theme](https://github.com/greenpeace/planet4-master-theme/pull/1508)
You can test the changes on this [test instance](https://www-dev.greenpeace.org/test-jupiter/) or on local.
> PLANET-6091 Align blocks with page width

- assets/src/blocks/CarouselHeader/ImagePlaceholder.js
- assets/src/blocks/Columns/ColumnsImagePlaceholder.js
- assets/src/blocks/Columns/EditableColumns.js
- assets/src/components/ImageHoverControls/index.js
- assets/src/components/ImagePlaceholderIcon.js
Ref: https://jira.greenpeace.org/browse/PLANET-6471
Since the image buttons will be used for the Take Action Boxout block as well, we should first extract them from the columns block.
This also simplifies some of the surrounding code.
- Extract SVG which was duplicated in Columns and Carousel Header. Will be used for Boxout too.
- Create a separate component for the hover buttons.
I might do a follow up with more decoupling, but this seems like already a sufficient amount to review.
TESTING:
This should produce the same result as before, so if you see any difference with how it behaves in master it's probably not intended.
Columns: https://www-dev.greenpeace.org/test-pandora/wp-admin/post.php?post=24037&action=edit
Carousel Header: …
> Decouple image hover controls from Columns block

- assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
On RTL the icons are reversed, the previous icon is on the right.
So it's already pointing at the proper direction.
- Look at the "broken" version on [production site](https://www.greenpeace.org/mena/ar).
- Locally you can use even the inspector to add `dir="rtl"` in the `<html>` tag. Otherwise you can use [nro-enable](https://support.greenpeace.org/planet4/development/installation#nro-sites) to have MENA site locally.
- Also deployed this on [MENA dev site](https://www-dev.greenpeace.org/mena/ar/).
> Carousel Header: Remove redundant transform on previous icon

- assets/src/components/fromThemeOptions/fromThemeOptions.js
* This way we can show a single option in the sidebar, but have it
result in multiple variables changing.
I made this to allow a [POC for master theme](https://github.com/greenpeace/planet4-master-theme/pull/1518), but it can be merged since it doesn't conflict with anything. Before this change the code would just crash if there are no options.
> Update to default if dependency has no options

- assets/src/blocks/TakeActionBoxout/ImagePlaceholder.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
- assets/src/components/ImageHoverControls/index.js
- assets/src/styles/blocks/ColumnsEditor.scss
- assets/src/styles/blocks/TakeActionBoxout/edit.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6471
* Move buttons-overlay class outside of the columns-specific class so it can be reused.
* Put styles on wrapper div instead of on img in editor only.
* Convert earlier added unintentional double quotes to single.
The image controls should work the same as for the columns block. The alignment issue is resolved, but only for the Boxout block. I'll address that in a follow up because it needs more changes in the Columns block's editor code.
Example on test instance: https://www-dev.greenpeace.org/test-venus/wp-admin/post.php?post=50288&action=edit
> PLANET-6471 Use same image controls as Columns block

- assets/src/blocks/Articles/ArticlesFrontend.js
- assets/src/blocks/CarouselHeader/Caption.js
- assets/src/blocks/Columns/ColumnsEditor.js
- assets/src/blocks/Columns/ColumnsFrontend.js
- assets/src/blocks/Counter/CounterFrontend.js
- assets/src/blocks/Covers/CampaignCovers.js
- assets/src/blocks/Covers/ContentCovers.js
- assets/src/blocks/Covers/TakeActionCovers.js
- assets/src/blocks/Gallery/GalleryEditor.js
- assets/src/blocks/Gallery/GalleryFrontend.js
- assets/src/blocks/Media/MediaFrontend.js
- assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
- assets/src/styles/blocks/ENForm/components/_enform-full-width.scss
- assets/src/styles/blocks/ENForm/components/_enform.scss
- assets/src/styles/blocks/Media.scss
- assets/src/styles/blocks/OldENForm/components/_enform-full-width.scss
- assets/src/styles/blocks/OldENForm/components/_enform.scss
- tests/acceptance/ColumnsImagesCept.php
We have some content width/padding issues in pages on mobile, which are due to our blocks having the `container` class but not the "non-blocks" items (paragraphs for example). Also because of this we had to manually add the page width to the `page-template` element, which doesn't make sense since we use the same ones as Bootstrap anyway so we might as well use that directly 🙂 So a solution would be to remove the `container` class from the blocks (except full-width ones) and add it to the `page-template` div instead (done in [this PR](https://github.com/greenpeace/planet4-master-theme/pull/1524))
You can see the new layout in this [test instance](https://www-dev.greenpeace.org/test-uranus), everything should look pretty much the same except with a bit less padding than before on mobile. In …
> Remove blocks container classes

- planet4-gutenberg-blocks.php
This will allow editors to add a form from a dropdown as a block instead of using shortcode.
> Enable GravityForms Gutenberg block

- assets/src/blocks/CarouselHeader/Sidebar.js
- assets/src/blocks/CarouselHeader/SidebarSlide.js
- assets/src/styles/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss
- assets/src/styles/blocks/CarouselHeader/SidebarSlidesEditor.scss
:point_right: [Demo page](https://www-dev.greenpeace.org/test-atlas/demo-page-fine-tune-carousel-header-slide-re-ordering-design-and-ux/)
[Figma](https://www.figma.com/file/IqISN3iLC17g2B2xxy0Clt/Carousel?node-id=301%3A2)
Ref: https://jira.greenpeace.org/browse/PLANET-6376
The current implementation is not working as expected. Not only when user editor wants to drag and drop any slide but also when he wants to edit any other value whenever the Slide is opened.
**What is included**
- Implement the ability to re order the list clicking on the up and down arrow button (**new feature**)
- Modify and fix the drag and drop logic since It has not been working correctly. In addition, someone has reported this issue through this [Slack message](https://greenpeace.slack.com/archives/C0151L0KKNX/p163 …
> Fine tune Carousel Header slide re-ordering design and UX

- assets/src/styles/blocks/Gallery/styles/GalleryThreeColumns.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6500
---
Expanding the images in the 3-column style to align with the wider XXL container. Also did some adjustments in mobile, where similar issues are visible.
- Current probably can be seen in live sites on XXL screens.
- After switching to this branch images should split properly with no gaps and no overlaps on all breakpoints.
> PLANET-6500 Gallery: Adjust image widths for XXL container

- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
- templates/blocks/take-action-boxout.twig
* Block now is inline so multiple should work.
[This master theme PR](https://github.com/greenpeace/planet4-master-theme/pull/1538) needs to be merged first.
Example on test instance: https://www-dev.greenpeace.org/test-iocaste/story/30102/the-story-of-plastic-is-an-eye-opener-on-the-global-plastic-pollution-crisis/
> Allow multiple boxouts, remove id attribute

- assets/src/blocks/HubspotForm/HubspotFormBlock.js
- assets/src/blocks/HubspotForm/HubspotFormEditor.js
- assets/src/blocks/HubspotForm/HubspotFormEditorScript.js
- assets/src/blocks/HubspotForm/HubspotFormFrontend.js
- assets/src/blocks/HubspotForm/HubspotFormScript.js
- assets/src/blocks/HubspotForm/HubspotFormSidebar.js
- assets/src/blocks/HubspotForm/hooks/useBackgroundImage.js
- assets/src/blocks/HubspotForm/hooks/useHubspotForm.js
- assets/src/blocks/HubspotForm/hooks/useToAttribute.js
- assets/src/styles/blocks/HubspotForm/HubspotFormEditorStyles.scss
- assets/src/styles/blocks/HubspotForm/HubspotFormSidebarStyles.scss
- assets/src/styles/blocks/HubspotForm/HubspotFormStyles.scss
- assets/src/styles/blocks/HubspotForm/layouts/ImageFullWidthStyles.scss
- classes/blocks/class-hubspotform.php
- classes/class-loader.php
- planet4-gutenberg-blocks.php
- webpack.config.js
**Description**
---
It's about the new custom [Hubspot Form Block](https://jira.greenpeace.org/browse/PLANET-6190).
For now is only implemented as the default the [Image Full Width](https://p4-designsystem.greenpeace.org/05f6e9516/p/213df0-hubspot-forms/b/99e047) form, but easy to be scalable. 
The rest of the forms will be added once the base implementation is approved. 
-> [Demo page](https://www-dev.greenpeace.org/test-deimos/hubspot-form-block)
-> [Design](https://p4-designsystem.greenpeace.org/05f6e9516/p/213df0-hubspot-forms/b/99e047)
Ref: [Ticket](https://jira.greenpeace.org/browse/PLANET-6190)
If you want to create a new **Hubspot Form** please go [here](https://www-dev.greenpeace.org/dmptest/wp-admin/admin.php?page=leadin_forms&leadin_route%5B0%5D=type&leadin_search=businessUnitId …
> Hubspot Form block base implementation

- assets/src/blocks/CarouselHeader/EditableBackground.js
- classes/class-loader.php
* We were not able to reproduce the issue yet, but it keeps on occurring
that a local image is used for the largest size of an image. Local means
it's on the PHP server, and doesn't use the CDN URL. This source is
removed when we deploy, resulting in an empty image.
While this doesn't fully address [the issue](https://jira.greenpeace.org/browse/PLANET-6372), it does prevent the worst effect (browser using 404 image).
I also added a blocking alert message, so that the editor in question knows it happens, and can contact the Planet 4 team with reproduction steps.
> Workaround to prevent local images CarouselHeader

- assets/src/blocks/Accordion/AccordionEditor.js
- assets/src/blocks/Articles/ArticlesEditor.js
- assets/src/blocks/CarouselHeader/Sidebar.js
- assets/src/blocks/Columns/ColumnsEditor.js
- assets/src/blocks/Counter/CounterEditor.js
- assets/src/blocks/Covers/CoversEditor.js
- assets/src/blocks/Gallery/GalleryEditor.js
- assets/src/blocks/Happypoint/HappypointEditor.js
- assets/src/blocks/Media/MediaEditor.js
- assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsSettings.js
- assets/src/blocks/Spreadsheet/SpreadsheetEditorScript.js
- assets/src/blocks/Submenu/SubmenuEditor.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
- assets/src/blocks/Timeline/TimelineEditorScript.js
- tests/js/articles.editor.spec.js
- tests/js/articles.frontend.spec.js
- tests/js/counter.spec.js
- tests/js/spreadsheet.spec.js
- tests/js/submenu.spec.js
For WYSIWYG blocks, in the sidebar the panel was called `Setting` instead of `Settings` which is more accurate as there's usually several settings 🙃
> Fix small typo in Settings panel title

- assets/src/styles/blocks/Accordion/AccordionEditorStyle.scss
See https://jira.greenpeace.org/browse/PLANET-6482
Because the CSS code was not specific enough, the width attribute for the button was overridden, resulting in a really ugly input 😬 
Create an Accordion block in the editor, before the fix you should see the button as shown on the ticket (in one long vertical line) and after the fix it should look as expected 🙂 I've tested it on both Chrome, FF and Safari and it seems to work fine in all of these!
> PLANET-6482 Fix Accordion block button width in the editor

- assets/src/styles/blocks/Columns.scss
Bump to changes introduced in https://github.com/greenpeace/planet4-master-theme/pull/1550
Also simplify a rule to not use `calc`.
> Bump theme submodule for spacing variables

- package-lock.json
- package.json
* Better editor UI positioning.
* Allows linking to your IDE per variable.
* Various fixes.
You can only use the links to open stuff in your IDE after doing the following:
1) Install this protocol handler https://github.com/sanduhrs/phpstorm-url-handler. You can technically also use another IDE by changing the [handler file included in that repo](https://github.com/sanduhrs/phpstorm-url-handler/blob/master/phpstorm-url-handler#L20-L23) to use a command to open in your IDE instead. But for now the protocol name is hard coded to `phpstorm`.
2) Add the path mappings for each repo to the local storage.
* The key is `repo-paths`. If you're on a test instance, you need to prefix it with the instance name + `/`.
* The key of this object will be searched for in a stylesheet name, and if it …
> Bump theme editor

- assets/src/blocks/Covers/deprecated/coversV1.js
In the frontend existing blocks do show the grid layout by default as expected, but in the backend they still didn't have a layout attribute which caused some design issues. Setting the new layout attribute to grid by default in the coversV1 file fixed that problem.
On your local, you can go to a page that had a Covers block before releasing the new layout attribute (for example `/act`) and edit it, to see that in the backend no layout setting is selected and the preview looks weird 😬 If you then switch to this branch, the issue should be solved.
> PLANET-5609 Fix existing Covers blocks in the backend

- assets/src/blocks/Covers/CampaignCovers.js
- assets/src/blocks/Covers/ContentCovers.js
- assets/src/blocks/Covers/CoversEditor.js
- assets/src/blocks/Covers/CoversEditorScript.js
- assets/src/blocks/Covers/CoversImagePlaceholder.js
- assets/src/blocks/Covers/TakeActionCovers.js
- assets/src/blocks/Covers/example.js
- assets/src/styles/blocks/Covers/CoversEditorStyle.scss
- classes/blocks/class-covers.php
- webpack.config.js
See [PLANET-6106](https://jira.greenpeace.org/browse/PLANET-6106)
This is to give a better idea of the block styles when the block is empty. This PR also solves the missing keys console warnings that showed up when switching styles, by adding an id to all covers instead of using a different attribute per style such as `name` or `post_title`. This new id also makes sure that there are no duplicates, whereas before the fix there could have been some edge cases with the same post title for example.
On your local, you can add a Covers block to a page and check the new styles in the editor, in the sidebar. Otherwise you can check it out on the test instance, for instance on the [Act page](https://www-dev.greenpeace.org/test-nix/act) that already has a Covers block 🙂
> PLANET-6106 Use block examples for Covers styles

- assets/src/blocks/Covers/CampaignCovers.js
- assets/src/blocks/Covers/ContentCovers.js
- assets/src/blocks/Covers/TakeActionCovers.js
- assets/src/blocks/Covers/example.js
- classes/blocks/class-covers.php
We can use the URLs of the results as a key instead of adding an ID.
This avoids complicating the front end code even further to support the editor. We should really keep front end and editor separate so that we don't have "Swiss army knife" style files that do everything and are very hard to change.
This should again result in console warnings, but those are harmless and just noisy.
The root cause is that the data for each cover type is different. The URL is called `href`, `link` and `button_link` in the 3 styles.
The styles in the sidebar are using WP's `registerBlockStyle` API, which is only intended to affect which class is used for CSS.
The current code [adds an effect to the class name](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/d77070ac49a5116e3b8d3139cb9226a …
> Remove covers ids

- assets/src/blocks/CarouselHeader/EditableBackground.js
- classes/class-loader.php
This reverts commit a85abc9ac317d8fb0bc34b9fc64a023533279132.
It was not the block after all, the post content was being modified directly by a WPML plugin.
> Revert "PLANET-6503 Workaround to prevent local images CarouselHeader"

- assets/src/blocks/Covers/CampaignCovers.js
- assets/src/blocks/Covers/ContentCovers.js
- assets/src/blocks/Covers/TakeActionCovers.js
- assets/src/blocks/Covers/example.js
- classes/blocks/class-covers.php
This was causing console warnings for missing keys issues. It also makes more sense to use the same names everywhere as the style of Covers should only impact the CSS and not the data used.
> Use consistent attribute names for all Covers styles 

- assets/src/blocks/Covers/CoversEditor.js
Ref: https://jira.greenpeace.org/browse/PLANET-6487
The previous code has 2 issues:
* 1: It needlessly discards user input. If our other styles shouldn't
use these attributes, they can simply ignore them.
* 2: An effect here is not the right tool for the job. Effects always
run when the component renders + when deps are updated. If we would want
to unset data (which we don't), it should happen in an event listener.
The solution is to remove `post_types` and `posts` from the effect so they're preserved. See comments for caveat.
New behavior when switching styles:
https://user-images.githubusercontent.com/7604138/148570601-b93e914c-d2de-41bd-b437-48b77c553410.mp4
The previous code didn't have this flashing bug because it unsets the user input immediately which makes the block empty. The new …
> PLANET-6487 Avoid discarding data in an effect

- assets/src/components/Lightbox/setupLightboxForImages.js
See [PLANET-6000](https://jira.greenpeace.org/browse/PLANET-6000)
Adding the lightbox to these images causes a glitch when clicking on the image, where the lightbox is briefly shown before opening the link. Therefore images that are links should not have the lightbox functionality.
You can test the changes on [this page](https://www-dev.greenpeace.org/test-rhea/lightbox-tests/) I created, the first image should not have the lightbox and open the link directly whereas the second one that doesn't have a link should have the lightbox. You can compare it to [this broken version](https://www-dev.greenpeace.org/test-mars/lightbox-tests/) where both images show the lightbox despite the potential link.
> PLANET-6000 Remove Lightbox from images with links

- assets/src/components/ShareButtons/ShareButtons.js
`dataLayer` currently is declared as `const`, and doesn't use the proper global `window.dataLayer` object.
> Fix dataLayer declaration in ShareButtons

- classes/class-loader.php
Just a follow up from https://github.com/greenpeace/planet4-master-theme/pull/1589
Simplifying this since we now rely on `WP_APP_ENV` for this feature flag.
> Remove obsolete config option

- assets/src/blocks/Covers/useCovers.js
[Ticket](https://jira.greenpeace.org/browse/PLANET-6599)
[Demo page](https://www-dev.greenpeace.org/test-proteus/carousel-layout/)
**Problem**
The arrows are not visible when the Covers has set just 4 cards.
**What is fixed**
Set to 3 rows to Carousel layout the same as it's set to `grid`.
> PLANET-6599: Fix arrow issue from Carousel Take Action block

- assets/src/blocks/Cookies/CookiesBlock.js
- assets/src/blocks/Cookies/CookiesFieldResetButton.js
- assets/src/blocks/Cookies/CookiesFrontend.js
- assets/src/styles/blocks/CookiesEditor.scss
- assets/src/styles/editorStyle.scss
- classes/blocks/class-cookies.php
- classes/class-loader.php
See https://jira.greenpeace.org/browse/PLANET-6603
Related master-theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1586
**Note**: the code is very repetitive, we could create some components to improve that, but maybe in a separate PR for simplicity's sake 🙂 
You can check the new settings on local (`Planet 4 > Cookies`), or on the [neptune test instance](https://www-dev.greenpeace.org/test-neptune/wp-admin/admin.php?page=planet4_settings_cookies_text). Then once you set some values there, you can add a Cookies block to a page and see those values appear as default in the various fields. I've also added some reset buttons for the fields, so that editors can easily revert custom values to the default ones defined in the settings.
> PLANET-6603 Use default Cookies copy in Cookies block

- assets/src/blocks/Happypoint/HappypointFrontend.js
Current version doesn't show any Happy Point content when no toggle is checked, which is the default state of most Happy Points we have.
Restore mailing iframe as default mode when no toggle is checked
- Add a Happy Point to a page
- Don't check any toggle "mailing list iframe" or "hubspot embed"
- The Happy Point should use the "Happy point Subscribe Form URL" configuration from Planet4 > Default content and display its iframe
- Existing Happy points should still work properly
> PLANET-6496: Fix Happy Point default mode

- assets/src/styles/blocks/Covers/styles/ContentCovers.scss
- assets/src/styles/blocks/Covers/styles/TakeActionCovers.scss
[Ticket](https://jira.greenpeace.org/browse/PLANET-6598)
[Demo page](https://www-dev.greenpeace.org/test-proteus/carousel-layout-excessive-width-on-two-cards/)
**Reported issue**
> PLANET-6598: Fix carousel Layout excessive width of cards from Covers

- assets/src/blocks/Columns/ColumnsBlock.js
- planet4-gutenberg-blocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-6502
Title says it all. It didn't require additional code changes yet.
Only found 1 minor issue so far:
* If you choose a background color then it looks off because the column doesn't add padding. Can be worked around using a group block, but maybe something we can improve in a follow up. ([example](https://www-dev.greenpeace.org/test-rhea/columns-core-and-planet-4/))
> PLANET-6502 Rename "Columns" to "Planet 4 Columns" and add core Columns block

- planet4-gutenberg-blocks.php
I also cleaned up some obsolete fallback code and simplified the logic a bit.
The fallback code in case the type is none of the specified was throwing warnings. Also the logic made it use only core blocks for those cases. One of them is reusable blocks, which can be created with p4 blocks but then when edited individually would not allow to place them.
To improve this I made it fallback to the page blocks.
> Dev toggle for all blocks

- assets/src/BlockEditorValidation.js
Ref: https://jira.greenpeace.org/browse/PLANET-6615
Make the Global project field non mandatory to be able to save campaign pages despite issues with the global sheet.
- Create a campaign
- Save it without configuring the `Analytics & Tracking > Global project` field
> PLANET-6615: Make Global project field non mandatory

- classes/search/block/sql/class-sqlquery.php
A basic use of the block search fails when these parameters are not provided
Cf. https://app.circleci.com/pipelines/github/greenpeace/planet4-master-theme/4971/workflows/b8fc56ee-5057-4f85-90fa-9fd2df98f3e2/jobs/29904/parallel-runs/0/steps/0-104
Required for https://github.com/greenpeace/planet4-master-theme/pull/1624
> Fix block search query default parameters

- classes/controller/menu/class-blocks-usage-controller.php
This is to keep track of how much this newly allowed block is used in all P4 sites, in this [sheet](https://docs.google.com/spreadsheets/d/1uAmZLIWYsxrBByqbhoF_vVtSM7WGebYWIc0xftPRPwE/edit#gid=359432436).
> Add Media and Text code block to blocks usage report

- assets/src/blocks/Cookies/CookiesFrontend.js
- assets/src/blocks/Cookies/useCookie.js
- assets/src/styles/blocks/Cookies.scss
See [PLANET-6075](https://jira.greenpeace.org/browse/PLANET-6075)
This is to be compliant with our new cookies policy and be consistent with the cookies box behaviour with the settings built-in. I still need to double check when to show/hide the box depending on the cookies that are selected, for that I'm waiting for Julia to confirm the expected behaviour.
**Related PR**: [master-theme](https://github.com/greenpeace/planet4-master-theme/pull/1580)
There's already a Cookies block on the [privacy page](https://www-dev.greenpeace.org/test-jupiter/privacy/) of the jupiter test instance, you can check there that the checkbox is gone for first-party cookies and the `Always enabled` label has been added. It's also the case in the editor.
> PLANET-6075 Always enable necessary cookies

- assets/src/blocks/ENForm/ENFormSettings.js
- classes/blocks/class-enform.php
- tests/acceptance/ENFormCest.php
Ref: https://jira.greenpeace.org/browse/PLANET-6635
> A field to change the Donate URL for the Donate button in the Thank you message is missing.
Use `custom_donate_url` attribute to define `donatelink`.
Hide field if Donate button is hidden.
- Add an EN Form block to a page
- Check on preview/published page the Donate button links to the _Planet 4 > Donate button_ link configured
- Add a custom Donate URL in the sidebar 
- Check that the Donate button now links to that custom URL
- To easily display the "Thank you" section, using the [React developer tools](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/) you can edit the state of the block on the frontend from `signup` to `thankyou`
> PLANET-6635: Fix missing EN Form custom donate URL

- assets/src/blocks/Happypoint/HappypointEditor.js
- assets/src/blocks/Happypoint/HappypointFrontend.js
- assets/src/blocks/Happypoint/deprecated/HappyPointV1.js
- assets/src/blocks/Happypoint/useHubspotEmbedCode.js
See https://jira.greenpeace.org/browse/PLANET-6650
This is not needed because the block cannot be multiple times on a same page, and it was also sometimes causing loading issues because the container with id was not found. Hopefully this will solve the issue reported in the ticket, it's hard to know for sure because I couldn't reproduce it on local!
You can test the changes on the pluto test instance's [Act page](https://www-dev.greenpeace.org/test-pluto/act/):
- In the backend, make sure that switching between the default content and the override works as expected (you can compare it to the previously broken behaviour on the [mars instance](https://www-dev.greenpeace.org/test-mars/act/) for example).
- In the frontend, make sure that the embed code is showing as expected.
> PLANET-6650 Remove uniqueId from Happypoint instance id

- assets/src/blocks/Cookies/CookiesFrontend.js
This is a more thorough check than just verifying that they are not empty strings. I'm aware that this is an edge case, but I've noticed the issue while checking the Luxembourg [privacy page](https://www.greenpeace.org/luxembourg/fr/conditions-generales-dutilisation/), so it does happen 😬
If you change the name and description of an item in the Cookies block so that it's only spaces, this item should not show at all in the frontend.
> Hide Cookies block checkbox when name and description are spaces

- assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
See [PLANET-6657](https://jira.greenpeace.org/browse/PLANET-6657)
This was due to a -100% margin right set in Bootstrap's CSS to the carousel items, it is fixed by overriding this value.
**Note**: at some point in the future we might want to investigate [Bootstrap's RTL support](https://getbootstrap.com/docs/5.0/getting-started/rtl/), but it's still experimental so maybe not now 🙃 
On your local you can manually set `dir="rtl"` to the html element on a page with a CarouselHeader block (such as the homepage) and then switch slides, on `master` branch you will see it's broken with some "white slides" in between but on this branch it should look fine.
You can also see the previously broken version on the [example page](https://www.greenpeace.org/mena/ar/) from the ticket description, and the …
> PLANET-6657 Fix CarouselHeader RTL slide transitions

- assets/src/blocks/Articles/ArticlesEditor.js
- assets/src/blocks/Covers/CoversEditor.js
- assets/src/components/PostSelector/PostSelector.js
- classes/blocks/class-covers.php
Ref: https://jira.greenpeace.org/browse/PLANET-6624
> Use the same feature flag as [PLANET-6515](https://jira.greenpeace.org/browse/PLANET-6515)
When enabled expand the filter to also show latest Actions
On toggle feature, fetch Action pages with Act pages
[`PostSelector.js`](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/803/files#diff-54849c17e7f32a9780b25839fb6d00ac21666dbe4bc5163ea72655a1e03f06cc) was rewritten as a function component, and converted to use WP hooks.
- Activate Action pages in _Planet 4 > Information architecture :: Enable Action post type_
- Create a new action, add an _Excerpt_ and a _Feature image_
- Create a new Page, add a _Cover_ block, use the _Take action covers_ style
- Your Action page should appear, in the editor and on the frontend
- …
> PLANET-6624: Covers - expand page limitation to Actions

- assets/src/blocks/Submenu/getHeadingsFromBlocks.js
* This resulted in duplicate key errors once two headings are in a
classic block. Also the key was really large.
> Fix entire classic block content used for Anchor

- assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
[Hide white space](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/806/files?diff=split&w=1) recommended.
The branch name is inaccurate. I started the branch thinking the editor code needed fixes for RTL (for [PLANET-6658](https://jira.greenpeace.org/browse/PLANET-6658)), but it's not due to our code in the end.
While doing this I found the code is super unnecessarily nested, which made diagnosing issues very time consuming. So I made the code a bit more manageable first. We can still merge this as it seems to work well.
Still need to confirm if the reduced specificity works in all cases, but no issues seen yet.
These changes make the file size go from `20K` to `15K`, with the exact same end user result.
> Unwrap Carousel Header CSS

- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
Ref: https://jira.greenpeace.org/browse/PLANET-6623
> Adjust the filter so besides the current limitation (Act children) it also fetches Action page types.
Check if we need to rely on the [PLANET-6515](https://jira.greenpeace.org/browse/PLANET-6515) feature flag to make this work.
Include Action pages to available selection in Take action boxout block.
- Create a post
- Check that the block works without _Action_ pages activated
- Activate _Action_ pages in _Planet 4 > Information architecture :: Enable Action post type_
- Create a new action, add an _Excerpt_ and a _Feature image_
- Create a post, add a _Take action boxout_, your Action page should be there
- you can select it and see it in the editor and on the frontend
> PLANET-6623: Take Action Boxout - expand page limitation to Actions

- planet4-gutenberg-blocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-6658
* Remove "rtl_fix" which only makes things worse.
* Remove filter that caused WPML to call `switch_lang` when it's not
supposed to.
Likely WPML added `url_to_postid` assuming it would only be called in a context where it's safe to switch the language.
Maybe this used to be the case for the REST API. However WordPress calls the REST API "internally" to prevent the editor being delayed by an actual HTTP request. As a result WPML's `url_to_postid` filter will run on every revision that contains any embed block.
After some investigation I found `url_to_postid` is a super old part of WordPress and only used in a few leftover edge cases.
The only usage that could "break" if we remove WPML's filter is when you [embed a post from the same …
> PLANET-6658 Fix WPML RTL mayhem

- assets/src/blocks/Columns/example.js
- assets/src/blocks/Covers/example.js
- assets/src/blocks/Submenu/example.js
- assets/src/styles/editorStyle.scss
- classes/blocks/class-base-block.php
- classes/blocks/class-covers.php
Ref: https://jira.greenpeace.org/browse/PLANET-6654
The block editor now puts each block preview into an iframe, which it [provides with the editor stylesheets](https://github.com/WordPress/gutenberg/blob/8536f6f1aa1df9daa98193964aa8e62cc196cb7a/packages/block-editor/src/components/block-preview/auto.js#L73-L74).
WordPress provides these to the editor in PHP, by checking each block type for registered styles/editor styles.
https://github.com/WordPress/gutenberg/blob/8536f6f1aa1df9daa98193964aa8e62cc196cb7a/lib/client-assets.php#L627-L639
(It's not the actual same file in WordPress but similar enough).
Additionally WP now allows you to specify the screen size which it will apply to the preview iframe with scaling so that it takes up the same amount of sidebar space.
**Needs to be merged …
> PLANET-6654 Fix editor previews

- classes/class-loader.php
- classes/controller/menu/class-en-settings-controller.php
- planet4-gutenberg-blocks.php
* In the theme PR the constants are removed. To unblock that PR's tests,
I'm making it use string literals, which we can afterwards update to
thenew classes. All these things we wouldn't have to do in a monorepo.
* Remove "theme editor non logged in" feature check as it's not worth
the complexity.
This depends on https://github.com/greenpeace/planet4-master-theme/pull/1650
> Prepare for features in new classes 

- classes/class-loader.php
- classes/patterns/class-highlightedcta.php
See [PLANET-6668](https://jira.greenpeace.org/browse/PLANET-6668)
- Houssam asked that we remove the lightbox from the Highlighted CTA icon by default, since it doesn't really make sense to have it for such small images with no caption.
- Also, he asked that we replace the previously used dark green color by our existing dark blue, since we'll only start using the dark green in our future new identity. Therefore I've removed it from our color palette for now.
**Related PR**: https://github.com/greenpeace/planet4-master-theme/pull/1655
> PLANET-6668 Remove dark green color from palette and lightbox from icon

- classes/patterns/class-block-pattern.php
- classes/patterns/class-realitycheck.php
See [PLANET-6667](https://jira.greenpeace.org/browse/PLANET-6667), the [example page](https://www-dev.greenpeace.org/gutenberg/block-patterns/) and the [designs](https://www.figma.com/file/leueo1LMrlPabJkZYs2NgW/IA%26nav_Final-mockups?node-id=1%3A1650).
This is basically a Columns block with specific blocks per column (image, title and description). Houssam asked that we initialise the pattern with 3 columns so that is how it's implemented here, but editors can easily remove and/or duplicate columns.
You can either test the new pattern on local, or on [this page](https://www-dev.greenpeace.org/test-titan/reality-check-tests/) I created for UAT. Also make sure to try adding a new one in the backend so that you can see the initial state.
> PLANET-6667 Create Reality Check block pattern

- classes/patterns/class-realitycheck.php
See [PLANET-6667](https://jira.greenpeace.org/browse/PLANET-6667)
This is to add more space between the items on mobile.
> PLANET-6667 Increase Reality Check pattern spacer height

- assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
- assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
- assets/src/blocks/ENForm/ENFormFrontend.js
- assets/src/blocks/ENForm/ENFormInPlaceEdit.js
- assets/src/blocks/Happypoint/HappypointFrontend.js
- assets/src/blocks/HubspotForm/HubspotFormEditor.js
- assets/src/blocks/HubspotForm/HubspotFormFrontend.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
- assets/src/blocks/Splittwocolumns/SplittwocolumnsInPlaceEdit.js
- assets/src/styles/blocks/HubspotForm/HubspotFormStyles.scss
- assets/src/styles/blocks/WideBlocks.scss
- templates/blocks/carousel_header_full-width-classic.twig
- templates/blocks/enform.twig
- templates/blocks/enform/enblock.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6670
Change the `.block-wide` class to `.alignfull` in markup. Perserve the old class because some blocks save markup in the DB.
Needs to be merged after https://github.com/greenpeace/planet4-master-theme/pull/1654, as tests are not in the repo of the code they're testing.
> PLANET-6670 Use core class for full alignment

- planet4-gutenberg-blocks.php
Ref. https://jira.greenpeace.org/browse/PLANET-6627
---
The block templates can be declared in JS or in PHP as an array of blockTypes (block name and optional attributes) -
_PHP example:_
```
/**
* Adds a block template with 2 blocks(paragraph and articles block) on pagetype post.
*/
function p4_register_template() {
$post_type_object           = get_post_type_object( 'post' );
$post_type_object->template = [
[ 'core/paragraph' ],
[ 'planet4-blocks/articles' ],
];
}
add_action( 'init', 'p4_register_template' );
```
The following example in JavaScript creates a new block using [InnerBlocks](https://github.com/WordPress/gutenberg/blob/HEAD/packages/block-editor/src/components/inner-blocks/README.md) and templates, when inserted creates a set of blocks based off the template.
```
const el = …
```
> PLANET-6627 Add block template with 2 blocks(paragraph and articles block) for pagetype post

- assets/src/styles/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss
* Our full width block class doesn't work in this case because it has
wrapper markup.
Test page https://www-dev.greenpeace.org/test-venus/wp-admin/post.php?post=13&action=edit
Related ticket: https://jira.greenpeace.org/browse/PLANET-6670
> Fix slider not full width in editor

- assets/src/styles/blocks/Articles.scss
* The code can just as well target img, which allows to use the same CSS
for the Query Loop block. That block doesn't allow putting a class on
the img it outputs.
For now it's the only modification that was needed.
> Ensure class is not needed to use style

- assets/src/components/Lightbox/setupLightboxForImages.js
- assets/src/styles/blocks/core-overrides/_media-text.scss
See [PLANET-6735](https://jira.greenpeace.org/browse/PLANET-6735)
This is to allow users to enlarge/zoom images, especially on mobile. Editors can still disable this functionality by adding the `force-no-lightbox` class to the block.
You can test the changes on your local or on [this page that I created](https://www-dev.greenpeace.org/test-iocaste/media-text-tests/).
> PLANET-6735 Add Lightbox to Media and Text block images

- classes/rest/class-rest-api.php
Ref: https://jira.greenpeace.org/browse/PLANET-6731
GPLux needs to control the transmission of a `email_ok` field so it doesn't interfere with other petitions.
Adding a hook to allow to modify data before it is sent to EN.
We can then do this kind of operation at a child-theme level to not transmit some fields with specific value.
```php
add_filter(
'planet4_enform_data',
function ( $data ) {
if ( isset( $data['supporter']['questions']['question.3805'] )
&& $data['supporter']['questions']['question.3805'] === 'N'
) {
unset( $data['supporter']['questions']['question.3805'] );
}
return $data;
}
);
```
> PLANET-6731: Add filter hook for enform data

- assets/src/styles/blocks/Articles.scss
- assets/src/styles/blocks/Columns.scss
See [PLANET-6734](https://jira.greenpeace.org/browse/PLANET-6734)
These styles are now defined in master theme for all heading links.
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/1679
You can test the new heading links on [this page](https://www-dev.greenpeace.org/test-venus/heading-links/) for example, and compare it to [the old version](https://www-dev.greenpeace.org/test-titan/51775-2/). Also make sure that our P4 Columns and Articles blocks still behave as expected too (for instance on the [homepage](https://www-dev.greenpeace.org/test-venus/)).
> PLANET-6734 Remove blocks heading links style overrides

- assets/src/styles/blocks/core-overrides/Image.scss
See [PLANET-6740](https://jira.greenpeace.org/browse/PLANET-6740)
If we add the cursor to the whole `wp-block-image` div, if the image is smaller then it looks like you can click in paddings
You can see see the difference by comparing these two pages I created:
- [broken](https://www-dev.greenpeace.org/test-mars/lightbox-tests/)
- [fixed](https://www-dev.greenpeace.org/test-iocaste/lightbox-tests/)
> PLANET-6740 Limit Lightbox pointer cursor to img

- classes/search/block/class-blockusagetable.php
Function get_allowed_block_types can return a bool sometimes, which breaks filters.
Returning all blocks registered instead if that's the case.
> Fix block report when all blocks are allowed

- assets/src/styles/blocks/Covers/styles/CampaignCovers.scss
- assets/src/styles/blocks/Covers/styles/ContentCovers.scss
- assets/src/styles/blocks/Covers/styles/TakeActionCovers.scss
Update the new width from Card's Covers regarding the Design System.
Applied to the carousel layout of the Take Action, Content and Campaign Covers.
[Ticket](https://jira.greenpeace.org/browse/PLANET-6613)  
[Demo page](https://www-dev.greenpeace.org/test-proteus/carousel-layout-new-xxl-cards-width/)
Current layout
New layout
> Update Card's width from Covers for XXL viewports

- planet4-gutenberg-blocks.php
Ref: [PLANET-6742](https://jira.greenpeace.org/browse/PLANET-6742)
We found while checking the Brasil site that image handling in core is pretty terrible, not just on the Query Loop block. With some small fixes we can [reduce the amount of unnecessary data being sent](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/837#issuecomment-1108816046) by a lot.
These 2 blocks are relatively easy to provide the right `sizes` attribute, which helps browsers avoid downloading oversized images. Image handling is [still an open issue in core](https://github.com/WordPress/gutenberg/issues/6177) and doesn't seem to have much progress lately.
Investigating:
* Is the replacement safe to do? Should fail "gracefully" the fix would just not be applied, visual result is identical.
* It gets …
> PLANET-6742 Add right sizes attributes for some core blocks

- admin/js/editor.js
- assets/src/styles/blocks/core-overrides/Image.scss
This is needed for both the [Deep Dive ](https://jira.greenpeace.org/browse/PLANET-6534)and [Quick Links](https://jira.greenpeace.org/browse/PLANET-6520) block patterns.
This is actually a default WP styles that we had manually removed, but it also needs some small CSS tweaks to fit our designs.
You can test the new rounded style on your local or on [this page](https://www-dev.greenpeace.org/test-tavros/image-blocks/) I created on the tavros instance.
> Add Rounded style to Image block

- assets/src/styles/blocks.scss
[PLANET-6771](https://jira.greenpeace.org/browse/PLANET-6771)
It's already [loaded in a separate file](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/4bbce6f0efd3acd64fa967b7ed859a9908bd44d7/assets/src/styles/blocks/ENForm/ENFormStyle.scss#L6-L14).
It's about a quarter the CSS file size of our main file. On this branch the prod build minified CSS is 38KB instead of 49KB. Though it seems a small difference, it's blocking CSS and has a relatively high impact. Even if the file transfer size difference is only a few KB due to compression, the browser still needs to evaluate it too before it can start displaying the page.
I discovered this when on [this page](https://www-dev.greenpeace.org/international/act/protect-the-oceans/) I found the same complex selector twice. I …
> PLANET-6771 Remove duplicate EN Form CSS

- admin/js/editor.js
- assets/src/styles/blocks.scss
- classes/patterns/class-block-pattern.php
- classes/patterns/class-issues.php
Ref: https://jira.greenpeace.org/browse/PLANET-6638
Design: [Figma](https://www.figma.com/file/99X4IXpkQIgNKtKvHEyI1P/IA-%26-nav_MVP-prototype?node-id=31%3A219)
[Demo page](https://www-dev.greenpeace.org/test-sinope/issues-pattern)
**Testing**
Go to the instance > Create new page > Click on "+" > Search Issues pattern
**There are some UI pattern's limitations, ~that is why we add some styles through an external CSS file (see the class deep-dive-topic class)~**
> PLANET-6638: Issues block pattern

- planet4-gutenberg-blocks.php
I got an error when I want to save a media text without setting a media.
> Notice: Undefined index: mediaId in /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks/planet4-gutenberg-blocks.php on line 467
This fix check if the field has been defined previously and prevent to don't execute [this logic](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/planet4-gutenberg-blocks.php#L467-L507) if `mediaId` is `undefined`.
> Fix undefined mediaId value in core/media-text block when the media is not set

- assets/src/styles/blocks/SplitTwoColumns.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6699
> Remove purple visited state from Split Two Columns links
Set visited colors as non-visited colors for issue link and tag link
Check a _Split two columns_ block on the frontend
- Toggle the `:visited` state for the blue issue link and yellow tag link
- Color should not change
> PLANET-6699: Remove purple visited state from Split Two Columns links

- assets/src/blocks/Splittwocolumns/SplittwocolumnsSettings.js
- assets/src/styles/blocks/SplitTwoColumns.scss
- assets/src/styles/blocks/SplitTwoColumnsEditor.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6686
> Reproduce steps:
> - Edit the page. Block requires recovery.
> - Attempt recovering and update the page. It works fine, but issue and tag are missing.
> - Select issue for the left column and tag for the right one. And update the page.
> - Refresh the editor.
> - Block requires recovery again.
Tag and issue ids are declared as numbers, but the select component returns a string
Casting those as int fixes recovery and selectors issues
- Add a SplitTwoColumns block in a new page
- Select an issue and a tag
- Image and text should appear in the block
- Save and reload the editor
- the block should appear without recovery needed
- issue and tag are selected in the block settings
> PLANET-6686: Fix Split two columns issue/tag types

- assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
- assets/src/styles/blocks/Covers/layouts/CoversCarouselLayout.scss
- assets/src/styles/blocks/Gallery/styles/GalleryCarousel.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6700
Ref: https://jira.greenpeace.org/browse/PLANET-6719
Gallery carousel and Take action cover carousel are inheriting their style from the Carousel header.
Its icons declaration are interfering between blocks.
The conflict only shows when related css files are all included, which happens in the editor, on preview, and when these blocks are all on the same page
- Add more specific selectors to fix the multiple arrows issue
- Add specific padding to avoid a movement of the _next_ icon on `:hover`
Test page on Sinope https://www-dev.greenpeace.org/test-sinope/planet-6700/
Locally
- Create a new page
- Add a Carousel header, a Gallery, a Cover with take action covers and carousel layout
- Check that each arrow works properly
- no multiple icons …
> PLANET-6700: Fix broken arrows for Gallery and Cover blocks

- classes/search/block/class-blockusage.php
Inner blocks were previously skipped, WP parser returns inner blocks as properties of root blocks.
- Extract format_block_data method
- Add loop to go through any inner block depth
This allows to search for blocks used in query loop.
- Create a post with a query block
- Add some blocks in this query, save draft
- Search those blocks in the block report
> Block report: Parse inner blocks data

- admin/js/editor.js
- assets/src/styles/blocks.scss
- assets/src/styles/blocks/core-overrides/Heading.scss
- assets/src/styles/blocks/core-overrides/HeadingEditor.scss
- assets/src/styles/editorStyle.scss
This is needed for the [deep dive block pattern](https://www.figma.com/file/2VVSBXQZrPoV3hNiMNGXB6/P4-Blocks_Master?node-id=1721%3A7823)
You can test the new style on this [page](https://www-dev.greenpeace.org/test-deimos/headings-with-chevrons/) with all possible heading sizes. The "extreme" ones (h1, h6) look a bit strange with this size of chevron, but I'm not sure it's worth defining a chevron size per heading level: h2/h3 are probably the most used, and anyway for any heading level editors can manually change the font size... I'm still discussing this with Mag!
> Add chevron style to heading core block

- admin/js/editor.js
- classes/patterns/class-highlightedcta.php
See [PLANET-6712](https://jira.greenpeace.org/browse/PLANET-6712)
This is needed for some block patterns, for now only the Highlighted CTA
**Related PR**: https://github.com/greenpeace/planet4-master-theme/pull/1714
You can test both the Highlighted CTA pattern and regular buttons on this [page](https://www-dev.greenpeace.org/test-titan/transparent-buttons/) I made for UAT, with several background colors from our palette.
> PLANET-6712 Add transparent style to core Button block

- classes/patterns/class-highlightedcta.php
- classes/patterns/class-issues.php
- classes/patterns/class-realitycheck.php
- classes/patterns/class-sideimagewithtextandcta.php
Ref: https://jira.greenpeace.org/browse/PLANET-6704
Insert placeholder images to these block patterns:
- Issues
- Highlighted CTA
- Reality check
- Side image with text and CTA 
**Demo page** _keep in mind that placeholders are wouldn't available till we merge [#1708](https://github.com/greenpeace/planet4-master-theme/pull/1708)_
https://www-dev.greenpeace.org/test-leda/block-patterns-with-placeholder-images/
Blocked by these PRs:
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/846
- https://github.com/greenpeace/planet4-master-theme/pull/1708
> PLANET-6704: Insert placeholder images to patterns

- assets/src/blocks/Covers/CoversEditor.js
- assets/src/blocks/Covers/CoversEditorScript.js
- assets/src/blocks/Covers/CoversFrontend.js
- assets/src/blocks/Covers/CoversGridLoadMoreButton.js
- classes/blocks/class-covers.php
Ref: https://jira.greenpeace.org/browse/PLANET-6748
Demo page: [Mena's dev instance](https://www-dev.greenpeace.org/mena/ar/10072/)
GPBR reported that the `Load more` text is not being translated [see here](https://www-dev.greenpeace.org/brasil/noticias-e-historias/). Thus, I checked it from [LOCO](https://planet4.greenpeace.org/wp-admin/admin.php?bundle=planet4-plugin-gutenberg-blocks%2Fplanet4-gutenberg-blocks.php&domain=planet4-blocks&path=plugins%2Fplanet4-plugin-gutenberg-blocks%2Flanguages%2Fplanet4-blocks-pt_BR.po&page=loco-plugin&action=file-edit) and effectively it was correctly translated. 
In consequence of that, I assumed that it was a Covers's block issue then I decided to replicate the same functionality of the Articles block which I've already known that it has been working …
> PLANET-6748: Fix read more text from Covers block

- classes/rest/class-rest-api.php
Ref: https://jira.greenpeace.org/browse/PLANET-6720
> The "override" function on the articles block doesn't seem to load anything. It can't find any blogs.
> This seems not to affect other sites. The API request returns 400.
Our endpoint required a `post_language` parameter for queries on wpml enabled site.
Current post language can safely be determined by a backend side function call
Locally, install a Belgium instance:
- **Stop** your current instance with `make stop`
- Clone in a **new directory** and install
```shell
> git clone git@github.com:greenpeace/planet4-docker-compose.git pdc-6720 
> cd pdc-6720
> NRO_NAME=belgium NRO_DB_VERSION=latest make nro-from-release
```
To verify this fix:
- Check this branch
```shell
> (cd persistence/app/public/wp-content/plugins/planet4-plugin-guten …
```
> PLANET-6720: Fix all-posts rest call with wpml

- classes/class-loader.php
This is needed for some block patterns, for their background color, for example the [Deep Dive](https://jira.greenpeace.org/browse/PLANET-6534) or the [Quick Links](https://jira.greenpeace.org/browse/PLANET-6520).
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/1718
You can see the new color used in both text color and background color on [this page](https://www-dev.greenpeace.org/test-iocaste/new-grey-5-color/) for example!
> Add Grey 5% to our color palette

- classes/patterns/class-issues.php
See [PLANET-6638](https://jira.greenpeace.org/browse/PLANET-6638)
It should be `grey-05` instead of `grey-10`, it was just added to our palette!
> PLANET-6638 Update Issues block pattern background color

- assets/src/styles/blocks/core-overrides/Image.scss
This is needed for the [Quick Links](https://jira.greenpeace.org/browse/PLANET-6520) and [Deep Dive](https://jira.greenpeace.org/browse/PLANET-6534) block patterns.
Otherwise images look oval instead of rounded like we want, even when fixing the width/height in the backend, because we set the img elements' height to `auto` in several places.
Another option would be to remove the `auto` height for all images, but I think this was added for large images that might be cropped in width in smaller screens and would then look really bad with their original height 😬 
**Note:** this CSS property is still experimental, however [it seems to be supported](https://caniuse.com/?search=aspect-ratio) by most browsers' latest versions!
You can compare the broken version …
> Force rounded images to have an aspect ratio of 1

- classes/class-loader.php
See [PLANET-6788](https://jira.greenpeace.org/browse/PLANET-6788)
This is now defined in the master theme repo, in theme.json
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/1719
Either on local or on the rhea test instance ([example page](https://www-dev.greenpeace.org/test-rhea/color-tests/)), you can test the new palette in both the editor and the frontend. It should look exactly the same as before, be available for all core blocks (except the Table block for which we have custom background colors), and the colors should be the same in the backend and frontend!
> PLANET-6788 Remove color palette

- assets/src/editorIndex.js
- assets/src/styles/blocks.scss
- assets/src/styles/blocks/Editor.scss
- assets/src/styles/editorStyle.scss
- assets/src/variations/stretched-link/edit.scss
- assets/src/variations/stretched-link/index.scss
This should work well on any block that can use `position: relative`, and as long as the link is not within a block with `position: relative` inside the container.
~~A drawback about this method is a block can only have 1 block style at a time. I have another PR that uses [block styles to add padding on the same blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/832). The only way to use styles for more things is to add 1 style for every possible combination. For more than 2 things that would probably get out of hand.~~
A possible alternative is to create a [variation of the core group block](https://github.com/WordPress/gutenberg/blob/29c0c4239c5e16fd3a32bc4ea82aa0135450b344/packages/block-library/src/group/variations.js#L7-L43), similar to the new "row" block, …
> Add group variation for full block link

- assets/src/styles/blocks/core-overrides/Image.scss
This will be useful for block patterns, where we never want to show caption nor credits. It works similarly to our [force-no-lightbox](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/styles/blocks/core-overrides/Image.scss#L20-L22) class, that editors can manually add to the block in case they want to disable the Lightbox for this particular image.
On local, first add an Image block and select any image that has credits and/or caption set up in the library. Then in the sidebar, in the "Advanced" tab, in the "Additional CSS class(es)" you can add the `force-no-caption` class. You should then see the caption disappear in the editor, and it should also be hidden in the frontend.
Alternatively you can check out this …
> Create CSS class to force hiding Image block caption/credits

- admin/js/editor.js
- assets/src/components/Image/ImageBlockEdit.js
- assets/src/styles/blocks/core-overrides/Image.scss
These have specific width and height, to facilitate creating block patterns such as [Deep Dive](https://jira.greenpeace.org/browse/PLANET-6534) and [Quick Links](https://jira.greenpeace.org/browse/PLANET-6520). I can't think of another way to force images to have a specific size and aspect ratio.
You can test the new styles on your local environment or on the oberon test instance ([example page](https://www-dev.greenpeace.org/test-oberon/rounded-images-with-custom-sizes/)). When selecting either the `Rounded 90x90` or `Rounded 180x180` style, you should see the width and height adapt accordingly in the sidebar. Editors can still change these values manually, which might result in some confusion, but as far as I know it's not possible to disable them 😕
> Add Image block rounded styles with specific sizes

- assets/src/styles/blocks/core-overrides/BlockSpacing.scss
- assets/src/styles/editorStyle.scss
See [PLANET-6778](https://jira.greenpeace.org/browse/PLANET-6778)
Since we can use Group blocks within other blocks, this custom spacing should only apply to parent Group blocks.
While checking this I found out that blocks don't all have margins in the editor, so I've pushed a fix for that. Also, I've added a fix for numbered lists to follow the same rules as bullet lists.
You can test the Group block spacing on this [page](https://www-dev.greenpeace.org/test-deimos/group-block-spacing/) for example, or on local. In the editor you can also play around with different blocks to see what the new spacing looks like!
> PLANET-6778 Add spacing to core Group block

- assets/src/styles/blocks/core-overrides/Image.scss
We need to use `!important`, otherwise in the editor the caption will sometimes still show (in cases where the image has an alignement class for example, because the CSS selectors then change).
On local, add an Image block and select an image that has a caption and/or some credits assigned in the library. Then add alignment to the block (such as `Center`) and the `force-no-caption` class in the advanced settings. On this branch the caption should be hidden in both frontend and backend, whereas on master branch the caption will still show in the editor.
> Enforce hiding Image block caption with CSS

- classes/patterns/class-block-pattern.php
- classes/patterns/class-deepdive.php
See [PLANET-6534](https://jira.greenpeace.org/browse/PLANET-6534)
I've yet to figure out how to implement [this transition](https://www-dev.greenpeace.org/gutenberg/deep-dive-topics-links/) requested by the design team, maybe it will be for a second iteration?
On local, you'll need to set master-theme to the `new-pattern-placeholders` branch to see the correct image placeholders both in the editor and in the frontend ([corresponding PR](https://github.com/greenpeace/planet4-master-theme/pull/1717)).
Otherwise you can test the new pattern on [this page](https://www-dev.greenpeace.org/test-nix/deep-dive-block-pattern/) for example 🙂
> PLANET-6534 Create Deep Dive block pattern

- assets/src/blocks/Covers/TakeActionCovers.js
See [PLANET-6340](https://jira.greenpeace.org/browse/PLANET-6340)
Other Covers block styles already have it ([Campaign](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Covers/CampaignCovers.js#L42), [Content](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Covers/ContentCovers.js#L50)) but for some reason this one didn't. This should improve performance.
> PLANET-6340 Add lazy loading to Take Action covers

- assets/src/styles/blocks/core-overrides/_columns.scss
- classes/patterns/class-block-pattern.php
- classes/patterns/class-quicklinks.php
See [PLANET-6520](https://jira.greenpeace.org/browse/PLANET-6520)
I've yet to figure out how to implement [this transition](https://www-dev.greenpeace.org/gutenberg/deep-dive-topics-links/) requested by the design team, maybe it will be for a second iteration?
On local, you'll need to set master-theme to the `new-pattern-placeholders` branch to see the correct image placeholders both in the editor and in the frontend ([corresponding PR](https://github.com/greenpeace/planet4-master-theme/pull/1717)).
Otherwise you can test the new pattern on [this page](https://www-dev.greenpeace.org/test-neptune/quick-links-patterns-block/) for example 🙂
> PLANET-6520: Implement Quick Links block pattern

- assets/src/blocks/Covers/CoversFrontend.js
See [PLANET-6617](https://jira.greenpeace.org/browse/PLANET-6617)
Without this handler, resizing the window sometimes breaks the design because the covers' width changes based on screen width.
You can test the functionality on [this page](https://www-dev.greenpeace.org/test-pandora/covers-with-resize-handler/) for example, the covers should slide back to the start when resizing the window!
> PLANET-6617 Implement resize handler for Covers block carousel

- classes/class-loader.php
This is needed for the new pages templates, such as [PLANET-6529](https://jira.greenpeace.org/browse/PLANET-6529) and [PLANET-6523](https://jira.greenpeace.org/browse/PLANET-6523)
**Note:** it won't appear in the editor yet because it's empty for now, I'm adding it in a separate PR because we might need to make similar changes for the Page Header patterns.
> Add Pages block pattern category

- assets/src/blocks/ENForm/ENFormFrontend.js
See [PLANET-6827](https://jira.greenpeace.org/browse/PLANET-6827)
We don't want the HTML tags to be shown in the frontend, they should be parsed to display the expected formatting.
You can test the changes on [this page](https://www-dev.greenpeace.org/test-titan/en-forms-with-html-tags/) for example. Feel free to change the block style to make sure the tags are correctly parsed in all of them 🙂
> PLANET-6827 Parse HTML tags in EN form fields

- classes/patterns/class-block-pattern.php
- classes/patterns/class-deepdive.php
- classes/patterns/class-highlightedcta.php
- classes/patterns/class-issues.php
- classes/patterns/class-quicklinks.php
- classes/patterns/class-realitycheck.php
- classes/patterns/class-sideimagewithtextandcta.php
This is needed for some of our page templates that need certain patterns variations, such as the [Get Informed one](https://jira.greenpeace.org/browse/PLANET-6523) that needs a variation of the "Side image with text and CTA" pattern where the image is on the right. This new parameter is also included in this PR.
> Add parameters to block patterns get_config function

- assets/src/blocks/Covers/CoversEditor.js
- assets/src/components/PostSelector/PostSelector.js
- classes/blocks/class-covers.php
- classes/rest/class-published.php
- classes/rest/class-rest-api.php
Ref: https://jira.greenpeace.org/browse/PLANET-6816
This modification allows to manually add pages and posts (instead of only posts) to Content Covers block.
I've extracted the endpoint code to a single class and renamed it to a more generic `/published`.
Example page https://www-dev.greenpeace.org/test-tavros/content-covers/
- Create a new page
- Add a Covers block with Content Covers style
- Use the _Manual override_ field by typing the title of some other pages
- The autocomplete should list posts but also pages
- After reloading, posts and pages manually added still appear in the Manual override box
- Manually added content appears on frontend too
- Check that the Articles block only allows for manual addition of posts, not pages
> PLANET-6816: Pull pages for covers manual override

- assets/src/ImageBlockExtension.js
- assets/src/blocks/Counter/CounterEditor.js
Some of these will be removed very soon so we need to stop using them:
```
wp.editor.RichText is deprecated since version 5.3 and will be removed in version 6.2. Please use wp.blockEditor.RichText instead.
```
```
wp.editor.InspectorControls is deprecated since version 5.3 and will be removed in version 6.2. Please use wp.blockEditor.InspectorControls instead.
```
On local, you can add an Image block or a Counter block to any page and on `master` branch you'll see the console warnings, but not on this branch. Both blocks should still work as expected!
> Fix deprecated wp.editor elements console warnings

- planet4-gutenberg-blocks.php
Ticket: https://jira.greenpeace.org/browse/PLANET-6723
The new post page has changed to a new layout ([design](https://www.figma.com/file/tdt8olZ6RS4bTMqbo2cvCU/Post-page-V1?node-id=79%3A7)).
_The oberon's instance is using the `allow_articles_block_in_posts` master's theme branch_ ([see here](https://github.com/greenpeace/planet4-test-oberon/blob/main/composer-local.json#L6)). 
[Related master theme PR](https://github.com/greenpeace/planet4-master-theme/pull/1741). 
[Demo page](https://www-dev.greenpeace.org/test-oberon/story/51096/post-title-goes-here-it-can-be-this-long/)
**Testing**
- Login to the assigned instance and create a new post
- You should be able to add the Articles block into the post
- After it's published, the Articles block should be inside the post content, currently …
> PLANET-6723: Enable articles in posts

- classes/patterns/class-blankpage.php
- classes/patterns/class-block-pattern.php
Ref: https://jira.greenpeace.org/browse/PLANET-6825
Create a new "blank page" pattern as a starting point.
Go to the [sinope's instance](https://www-dev.greenpeace.org/test-sinope/wp-admin/) and create a new page. Then, you'll be able to pick the desired pattern (for now only a the Blank page) when the page is empty.
- https://wptavern.com/wordpress-6-0-might-ship-a-feature-for-picking-a-block-pattern-on-page-creation
- https://github.com/WordPress/gutenberg/pull/40034
> PLANET-6825: Page creation UI integration

- classes/patterns/class-issues.php
- classes/patterns/class-quicklinks.php
- classes/patterns/class-sideimagewithtextandcta.php
This is needed for some page templates, such as the [Action](https://jira.greenpeace.org/browse/PLANET-6529) one or the [Get Informed](https://jira.greenpeace.org/browse/PLANET-6523) one. We want to be able to add some placeholders when creating these patterns. You can see how it would be used for example [here](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/877/files#diff-59777031749d62dcf9c1abe1512e44340868b40c3004277c5357267891d3bfecR37).
> Add title placeholder param to some patterns

- classes/patterns/class-highlightedcta.php
- classes/patterns/class-issues.php
- classes/patterns/class-realitycheck.php
These functionalities don't make sense in our patterns.
On local, you can add these patterns (`Issues`, `Reality Check` or `Highlighted CTA`) or you can go to [this page](https://www-dev.greenpeace.org/test-neptune/various-patterns/) I created, and then test the following:
- Make sure the Lightbox is not added to these patterns in the frontend
- Make sure images' captions (& credits) are never displayed in both the frontend and the backend
Our other patterns already have these disabled.
> Remove lightbox and image captions in patterns

- assets/src/blocks/Covers/CoversEditorScript.js
- assets/src/blocks/Covers/deprecated/coversV2.js
- classes/blocks/class-covers.php
This is to add the sometimes missing `readMoreText` attribute, and fix the block validation errors that appear when using this block in certain patterns such as the Action one.
This is mostly gonna be useful within patterns, but one way to test it would be to add a Take Action Covers block to a page via the code editor, such as 
```
```
and then exit the code editor, on `master` branch it should give validation errors whereas on this branch it should work as expected.
> Add coversV2 deprecated file to Covers block

- classes/controller/menu/class-blocks-usage-controller.php
- classes/patterns/class-block-pattern.php
- classes/patterns/class-deepdive.php
- classes/patterns/class-getinformed.php
- classes/patterns/class-highlightedcta.php
- classes/patterns/class-issues.php
- classes/patterns/class-quicklinks.php
- classes/patterns/class-realitycheck.php
- classes/search/block/class-blockusagetable.php
- classes/search/block/query/class-parameters.php
- classes/search/block/sql/class-sqlquery.php
- classes/search/class-blocksearch.php
- classes/search/class-patternsearch.php
- classes/search/class-rowactions.php
- classes/search/pattern/class-contentstructure.php
- classes/search/pattern/class-patterndata.php
- classes/search/pattern/class-patternusage.php
- classes/search/pattern/class-patternusageapi.php
- classes/search/pattern/class-patternusagetable.php
- classes/search/pattern/query/class-parameters.php
Ref: https://jira.greenpeace.org/browse/PLANET-6782
> Since we keep adding block patterns, it would be a good data point for assessing them at a later point to know how often each pattern is being used.
Pattern report accessible in _Blocks > Pattern report (Beta)_
- List of patterns, with post informations
- Filter by pattern
- Group by pattern, post title, post id
This version uses 2 types of detection:
- by class name
Each pattern has a `is-pattern-{pattern name}` class assigned to it, so that it is easily found in the database.
This allows to see usage _and_ find modifications applied to patterns.
- by structure
We match the blocks and inner blocks of the pattern to a post content, to see if the pattern is in the post.
We generate a "signature" from the structure of blocks (basically a …
> PLANET-6782: Pattern usage report

- assets/src/blocks/Covers/CoversEditorScript.js
This is a revert change of this [change](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/890/files#diff-cb6127d4a739490c5949afeb7be94a62cad0ae08b836460cc20db94f69a5a8f4R113) which is already merged.
> @mleray I've just figured out that the order of this array is wrong since according to the [documentation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/) the newer version must be always at the top of the array. For example [v3, v2, v1]. We might revert it.
> Change the order of the Cover's deprecated versions

- assets/src/variations/stretched-link/index.scss
See the [ticket](https://jira.greenpeace.org/browse/PLANET-6817) and the [example](https://www-dev.greenpeace.org/gutenberg/topics-link-animate-both-image-title-on-hover/) that Houssam implemented.
This is mostly for block patterns such as Deep Dive or Quick Links, but with this implementation it will be applied to all Stretched links that contain a rounded image.
You can check out [this page](https://www-dev.greenpeace.org/test-oberon/patterns-with-image-zoom-on-hover/) that I prepared for UAT! Otherwise on local you can test it in any Quick Links or Deep Dive pattern.
> PLANET-6817 Add hover zoom effect to images in Stretched links

- composer.json
Ref: https://getcomposer.org/doc/06-config.md#allow-plugins
Ref: https://jira.greenpeace.org/browse/PLANET-6850
---
This is required by newer composer versions.
Main PR: https://github.com/greenpeace/planet4-docker/pull/101
> PLANET-6850 Add allow-plugns config to composer

- assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
- assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
These styles are rendered an unnecessary white space to its bottom and fix the reported issue from [here](https://jira.greenpeace.org/browse/PLANET-6524).
From my point of view, we would need to keep the carousel header with its natural height without adding any extra space in its bottom. That space could be added for instance by a `Spacer` block.
Related PR: #884 
[Demo page of the current Homepage implementation](https://www-dev.greenpeace.org/test-phobos/51534-2/)
- [With margin to bottom](https://www-dev.greenpeace.org/test-neptune/)
- [Without margin to bottom](https://www-dev.greenpeace.org/test-neptune/33089-2/)
I'm open for suggestions :) What do you all think?
> Update carousel header styles

- classes/patterns/class-deepdive.php
- classes/patterns/class-highlightedcta.php
This will be needed for some pattern layouts, such as the [High-Level Topic one](https://jira.greenpeace.org/browse/PLANET-6737)
On local, you can try manually adding the `title_placeholder` attribute in the patterns' params and saving. After that, when adding the patterns to a page you should see them with the chosen titles. Of course they should also work as expected when there is no title placeholder specified in the params 🙂
> Add title_placeholder param to Deep Dive and Highlighted CTA patterns

- classes/patterns/class-sideimagewithtextandcta.php
This will be needed for some patterns, such as the [High level topic one](https://jira.greenpeace.org/browse/PLANET-6737)
On local, you can try manually adding the `background_color` attribute in the pattern's params (using a color from our [palette](https://github.com/greenpeace/planet4-master-theme/blob/master/theme.json#L12-L84)) and saving. After that, when adding the pattern to a page you should see it with the chosen background color. Of course it should also work as expected when there is no background color specified in the params 🙂
> Add background_color param to Side Image with Text and CTA

- classes/patterns/class-quicklinks.php
This pattern should have grey 5% as background color by default, but for some pattern layouts such as [Action](https://jira.greenpeace.org/browse/PLANET-6529) or [High-Level Topic](https://jira.greenpeace.org/browse/PLANET-6737), we need it to have white background
On local, you can try manually adding the `background_color` attribute in the pattern's params (using a color from our [palette](https://github.com/greenpeace/planet4-master-theme/blob/master/theme.json#L12-L84)) and saving. After that, when adding the pattern to a page, you should see it with the chosen background color. It should also work as expected when there is no background color specified in the params, meaning it should have `grey-05` background color applied by default 🙂
> Add background color param to Quick Links pattern

- classes/patterns/class-deepdive.php
This pattern should have grey 5% as background color by default, but for some pattern layouts such as [High-Level Topic](https://jira.greenpeace.org/browse/PLANET-6737), we need it to have white background
On local, you can try manually adding the `background_color` attribute in the pattern's params (using a color from our [palette](https://github.com/greenpeace/planet4-master-theme/blob/master/theme.json#L12-L84)) and saving. After that, when adding the pattern to a page, you should see it with the chosen background color. It should also work as expected when there is no background color specified in the params, meaning it should have `grey-05` background color applied by default 🙂
> Add background color param to Deep Dive

- classes/patterns/templates/class-twocolumnsgravityforms.php
We wrongly merged the [gravity forms name](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/classes/patterns/templates/class-twocolumnsgravityforms.php#L54).
> Fix gravity forms wp name

- classes/patterns/class-getinformed.php
According to the [mockups](https://www.figma.com/file/leueo1LMrlPabJkZYs2NgW/IA%26nav_Final-mockups?node-id=1812%3A4965), the Get Informed pattern layout should also have a Gravity Forms with the possibility to add title/description on the side. Since we now have a template for this we need to use it here!
> Use TwoColumnsGravityForms template in Get Informed

- classes/patterns/class-sideimagewithtextandcta.php
This is needed for some pattern layouts such as the [High-Level Topic one](https://jira.greenpeace.org/browse/PLANET-6737).
On local, you can manually set `alignfull` as true in the pattern's params and then save. After that, when adding the pattern to a page, you should see it full width as expected!
> Add alignfull param to Side Image with Text & CTA

- assets/src/styles/blocks/core-overrides/_media-text.scss
Before this fix, the block looks weird when it has a background or when it has full alignment (which will be needed for the [High-Level Topic](https://jira.greenpeace.org/browse/PLANET-6737)), especially with the image on the right:
When the block is full width, the content part should follow our grid.
You can either test the changes on local, or check [this page](https://www-dev.greenpeace.org/test-titan/media-text-improvements/) and compare it with the "broken" version [here](https://www-dev.greenpeace.org/test-leda/1090-2/). Please make sure you check all screen sizes, and also the RTL direction 🙂
> Fix Media & Text block padding

- planet4-gutenberg-blocks.php
Because of the new listing pages, we should override the WP native functionality.
- Change "Previous Page" button text to "Prev"
- Change "Next Page" button text to "Next"
- Show always both buttons despite of being in the first or last page.
Related to [#1759]( https://github.com/greenpeace/planet4-master-theme/pull/1759)
**Demo page**: We'll set the same as [#1759]( https://github.com/greenpeace/planet4-master-theme/pull/1759)
> Override pagination native functionality

- .stylelintrc
- assets/src/blocks/PageHeader/PageHeaderBlock.js
- assets/src/editorIndex.js
- assets/src/styles/blocks.scss
- assets/src/styles/blocks/PageHeader.scss
- classes/class-loader.php
- classes/patterns/class-block-pattern.php
- classes/patterns/class-pageheader.php
- classes/patterns/class-pageheaderimgleft.php
Ref: https://jira.greenpeace.org/browse/PLANET-6680
> Implement the [new page header design](https://zeroheight.com/05f6e9516/v/latest/p/1285c9-page-header/b/88c480).
> Requirments
> - Create new Block Patterns category: Page Headers
> - Create two block patterns:
>   "Page Header with image on the right"
>   "Page Header with image on the left"
>
> Tasks
>   Investigate if we can pull header and paragraph text from the pattern to populate metadata and opengraph.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/617346/170026415-12462333-a590-48a4-8d14-e3a431626485.png" /></td>
<td><img src="https://user-images.githubusercontent.com/617346/170026447-cb192039-b5d7-4677-a5d4-3de36cd57734.png" /></td>
</tr></table>
- Activate _All blocks_ in _Planet 4 > Features_
- Add a …
> PLANET-6680: Page Header block pattern

- assets/src/blocks/ActionPageDummy/ActionPageDummyBlock.js
- assets/src/editorIndex.js
- classes/blocks/class-actionpagedummy.php
- classes/class-loader.php
- classes/patterns/class-action.php
- classes/patterns/class-block-pattern.php
- classes/patterns/class-sideimagewithtextandcta.php
- planet4-gutenberg-blocks.php
See [PLANET-6529](https://jira.greenpeace.org/browse/PLANET-6529)
~There's a [related PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/890) to fix the block validation errors that occur with the Covers block, it's in a separate PR since it's also needed for other templates such as the Homepage one.~ Merged!
In order to hide this pattern in post types other than Action pages, we need to add a dummy block (literally called `ActionDummyBlock`, but that's open to discussion 😁) that will be allowed only in this post type. It's hidden from the block list/inserter too, so the only way to add it is via code like we do here in the pattern.
On local or on the umbriel test instance, you can create a new **Action** page and add the `Action` pattern to it, to see the initial …
> PLANET-6529 Create Action pattern layout

- classes/patterns/class-action.php
- classes/patterns/class-getinformed.php
- classes/patterns/class-homepage.php
- classes/patterns/templates/class-gravityformwithimage.php
- classes/patterns/templates/class-gravityformwithtext.php
This is to avoid duplicates (this will be needed in other pattern layouts too, such as the [Campaign](https://jira.greenpeace.org/browse/PLANET-6528) one) and also to make the code more readable.
To have more consistent naming, I've also renamed the `TwoColumnsGravityForm` template to `GravityFormWithText` (it also describes the template better I think!)
Also while working on this I noticed that the Action pattern layout didn't have a classname set, so I added a small commit to fix this 🙂 Aaaaand I've also added a commit using the theme spacing options rather than spacers in the `GravityFormWithText` template.
All the impacted pattern layouts (Action, Homepage and Get Informed) should still look as expected!
> Create GravityFormWithImage template

- classes/patterns/class-block-pattern.php
- classes/patterns/class-deepdivetopic.php
- tests/acceptance/PatternsCept.php
Ref: https://jira.greenpeace.org/browse/PLANET-6738
> Create the "Deep dive topic" block pattern layout made up of P4 blocks and block patterns based on these [high-fidelity mockups](https://www.figma.com/file/leueo1LMrlPabJkZYs2NgW/IA%26nav_Final-mockups?node-id=1814%3A6708) for desktop and mobile.
Also trying to fix the failing Acceptance test (probably coming for a previous PR, it also fails for docker-compose nightly build) ~(doesn't look like it's working :thinking: )~
On an empty page, add the Deep Dive Topic layout either via the block inserter or via the page creation modal.
> PLANET-6738: Deep Dive Topic pattern

- classes/patterns/class-pageheader.php
This is needed for some pattern layouts such as the [Take Action](https://jira.greenpeace.org/browse/PLANET-6525) one.
On local, you can try manually adding the `background_color` attribute in the pattern's params (using a color from our [palette](https://github.com/greenpeace/planet4-master-theme/blob/master/theme.json#L12-L84)) and saving. After that, when adding the pattern to a page, you should see the header with the chosen background color. It should also work as expected when there is no background color specified in the params, meaning it should have `grey-05` background color applied by default 🙂 You can also test the High Level Topic pattern layout since it has the Page Header pattern.
> Add grey background color to PageHeader pattern

- classes/patterns/class-block-pattern.php
- classes/patterns/class-campaign.php
See [PLANET-6528](https://jira.greenpeace.org/browse/PLANET-6528)
**Note:** there are some small differences with the [mockup](https://www.figma.com/file/leueo1LMrlPabJkZYs2NgW/IA%26nav_Final-mockups?node-id=1805%3A3486), due to some blocks not being implemented yet. So, the `P4 Custom block` is for now replaced by a `Covers` block, and the `Reality Check` pattern (which is here a different version from the one we currently have) is replaced by `Side Image with Text and CTA`. These changes have been approved by the design team.
You can test the pattern layout either on local or on the [mars test instance](https://www-dev.greenpeace.org/test-mars), in all screen sizes. Also, make sure that the pattern layout shows in the page creation modal!
> PLANET-6528 Implement Campaign pattern layout

- classes/search/class-patternsearch.php
- classes/search/pattern/class-patternusage.php
- classes/search/pattern/class-patternusageapi.php
Ref: https://jira.greenpeace.org/browse/PLANET-6868
- Making optional the structure search
- Do not use structure search for the API count
On an international DB locally, this reduces the API call from 22 seconds to 3 seconds, for a Belgium DB 33s to 4s. Assuming the issue on large DBs is the pattern structure query, this should solve the timeout issue.
Flush the object cache between tests.
```console
> curl -k https://www-dev.greenpeace.org/test-sinope/wp-json/plugin_blocks/v3/plugin_blocks_report/ | jq
```
> PLANET-6868: Improve block report API responsiveness

- assets/src/components/HidePageTitle/HidePageTitle.js
- assets/src/components/Sidebar/ActionSidebar.js
See [PLANET-6890](https://jira.greenpeace.org/browse/PLANET-6890)
This new meta setting is in the sidebar. It's needed to comply with the Action pages designs.
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/1784
You can test the new checkbox either on local on any Action page, or on [this one](https://www-dev.greenpeace.org/test-telesto/action/the-first-action-page/) that I created for UAT. Note that just like the corresponding meta option available in pages/posts, you need to update (and not just preview) the page before you see the change applied!
> PLANET-6890 Add option to hide page title in Actions

- assets/src/blocks/ENForm/ENFormFrontend.js
See [PLANET-6859](https://jira.greenpeace.org/browse/PLANET-6859)
This happens on the frontend when the block's description is left empty in the backend
You can compare the fixed version [here](https://www-dev.greenpeace.org/test-titan/en-form-with-no-description/) with the broken version [here](https://www-dev.greenpeace.org/test-telesto/en-form-with-no-description/) for example!
> PLANET-6859 Fix undefined description in EN form

- assets/src/styles/blocks/ColumnsEditor.scss
- assets/src/styles/blocks/TakeActionBoxout/edit.scss
- assets/src/styles/components/ImageHoverButtons.scss
- assets/src/styles/editorStyle.scss
These looked off in the editor:
- Take Action boxout (placeholder not centered):
- P4 Columns (button full width):
You can compare the fixed version [here](https://www-dev.greenpeace.org/test-oberon/wp-admin/post.php?post=51128&action=edit) with the broken version [here](https://www-dev.greenpeace.org/test-leda/wp-admin/post.php?post=1171&action=edit).
> Small CSS fixes for image hover buttons

- assets/src/blocks/Articles/useArticlesFetch.js
- assets/src/blocks/Covers/useCovers.js
- assets/src/blocks/Gallery/useGalleryImages.js
- assets/src/functions/getAbortController.js
Ref: https://jira.greenpeace.org/browse/PLANET-6921
We're currently getting this log error when any Cover, Article or Gallery block is unmounted without finishing the request.
We solve this by implementing a clean up function (i.e. [here](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/940#discussion_r978820100)) and aborting all the API fetch that were requested by the Block.  
Doing this we will avoid to run a ton of unexpected requests.
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
1. Create a new page
2. Close the Search pattern modal after 10 seconds, this is depending on your …
> Maintenance: Implement the ability to abort API fetch requests

- classes/controller/menu/class-blocks-usage-controller.php
- classes/controller/menu/class-reusable-blocks-controller.php
- classes/controller/menu/class-settings-controller.php
Ref: https://jira.greenpeace.org/browse/PLANET-6862
This PR enables Editors to navigate through the reusable blocks page into the Admin panel.
I've also left more info into comments, please validate them 🙏 .
Login within an Editor user and check if that user can navigate to `Blocks > Reusable blocks`
> PLANET-6862: Enable reusable blocks for editors

- assets/src/BlockFilters.js
Ref https://jira.greenpeace.org/browse/PLANET-6843
**Testing:**
- Add a gravity form block on page and check the "AJAX" toggle setting under Advanced tab, it should be by default enabled.
**eg.** 
https://www-dev.greenpeace.org/test-sinope/wp-admin/post-new.php?post_type=page
> PLANET-6843 Added a block filter to enforce "AJAX" toggle setting enabled by default on GF block.

- assets/src/components/Sidebar/ActionSidebar.js
- assets/src/components/Sidebar/CampaignThemeSidebar.js
- assets/src/components/Sidebar/PageHeaderSidebar.js
- assets/src/components/SidebarFields/CheckboxSidebarField.js
- assets/src/components/SidebarFields/ImageSidebarField.js
- assets/src/components/SidebarFields/TextSidebarField.js
- assets/src/components/SidebarFields/TextareaSidebarField.js
- assets/src/setupCustomSidebar.js
See [PLANET-6901](https://jira.greenpeace.org/browse/PLANET-6901)
These settings used to be in the metabox (see [related PR](https://github.com/greenpeace/planet4-master-theme/pull/1803) to remove them from there) but we move them to the sidebar in order to keep all settings in the same place
You can test the changes in any page or campaign, either on local or on the tavros test instance!
> PLANET-6901 Move Page Header metabox fields to sidebar

- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
- assets/src/components/Sidebar/ActionSidebar.js
- classes/blocks/class-covers.php
- classes/blocks/class-takeactionboxout.php
See [PLANET-4444](https://jira.greenpeace.org/browse/PLANET-4444)
This text will be shown in the Covers block, the Take Action boxout, and in search results.
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/1824
You can test the 3 possibilities (no button text, default button text, and custom button text)
- in the Covers block on [this page](https://www-dev.greenpeace.org/test-titan/text-actions-button-texts/) for example
- in the Search page [here](https://www-dev.greenpeace.org/test-titan/?s=button+text&orderby=_score) for example
You can also test changing the default text in the [P4 settings](https://www-dev.greenpeace.org/test-titan/wp-admin/admin.php?page=planet4_settings_defaults_content) to see how the block and search results are impacted!
> PLANET-4444 Add action button text to Action sidebar

- assets/src/blocks/CarouselHeader/SlideBackground.js
- classes/patterns/templates/class-carouselheader.php
The previous implementation sometimes resulted in `NaN`
> Fix Carousel Header focal points

- assets/src/components/Sidebar/ActionSidebar.js
- assets/src/components/Sidebar/OpenGraphSidebar.js
- assets/src/components/Sidebar/PageHeaderSidebar.js
- assets/src/components/Sidebar/getSidebarFunctions.js
- assets/src/components/SidebarFields/ImageSidebarField.js
- assets/src/setupCustomSidebar.js
See [PLANET-6900](https://jira.greenpeace.org/browse/PLANET-6900)
These fields were removed from the metabox (see [related PR](https://github.com/greenpeace/planet4-master-theme/pull/1810)) and are now in the sidebar.
On your local or on the [mars test instance](https://www-dev.greenpeace.org/test-mars/), you can add the Open Graph meta fields from the sidebar to any post/campaign/page/action and update the page. On reload in the editor you should still see the data that you entered, and when inspecting the page in the frontend you should see the correct meta fields added to the `head`:
You can also test the fields using this tool: https://www.opengraph.xyz/
> PLANET-6900 Add Open Graph fields to the sidebar

- assets/src/components/TermSelector/TermSelector.js
- assets/src/replaceTaxonomyTermSelectors.js
See [PLANET-6947](https://jira.greenpeace.org/browse/PLANET-6947)
This is to be more user-friendly, and also to be more consistent with the categories selection. We actually use basically the [same component](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js) that WordPress uses for the categories, minus the hierarchical aspect since we don't need it here 🙂 
Either or on local or on the [janus test instance](https://www-dev.greenpeace.org/test-janus/), you can test the new tags selection (and creation) interface in any page/post/action
> PLANET-6947 Use checkboxes for tags selection

- assets/src/block-templates/quick-links/block.json
- assets/src/block-templates/quick-links/index.js
- assets/src/block-templates/quick-links/template.js
- assets/src/block-templates/template-list.js
- classes/patterns/class-action.php
- classes/patterns/class-deepdivetopic.php
- classes/patterns/class-getinformed.php
- classes/patterns/class-highleveltopic.php
- classes/patterns/class-quicklinks.php
- planet4-gutenberg-blocks.php
See [PLANET-6939](https://jira.greenpeace.org/browse/PLANET-6939)
You should be able to add a Quick Links pattern as before without any problems! And the layouts using it should also still work as expected.
> PLANET-6939 Convert Quick Links pattern into a block template

- classes/class-loader.php
Adding a new block template in the editor generates a Warning message in the browser console, saying that the block category is invalid.
`The block "planet4-block-templates/side-image-with-text-and-cta" is registered with an invalid category "planet4-block-templates".`
- Declare missing block templates category
> Fix warning on block templates category missing

- assets/src/components/TermSelector/TermSelector.js
See [PLANET-6980](https://jira.greenpeace.org/browse/PLANET-6980)
We forgot about this detail when implementing the new tags selector interface. Right now for non-admins, we add a restricted tags box which is no longer needed since we now handle the restriction here in the new tags selector. There is [another PR](https://github.com/greenpeace/planet4-master-theme/pull/1857) to remove the restricted box, especially because there was a bug in the removal of the "normal" tags box which caused 2 boxes to be shown 😬 
On local or on the [umbriel test instance](https://www-dev.greenpeace.org/test-umbriel/), whether you login as an admin or as a non-admin you should see only one "Tags" section in the sidebar. The only difference between the two interfaces should be the "Add new tag" button …
> PLANET-6980 Make sure non-admins cannot create new tags in the sidebar

- assets/src/addButtonLinkPasteWarning.js
This is to eventually completely stop using jQuery
The functionality should still work like before, so you should see the warning when adding a Button block and trying to paste a link into it.
> PLANET-6981 Remove jQuery from addButtonLinkPasteWarning

- assets/src/components/Sidebar/SearchEngineOptimizationsSidebar.js
- assets/src/components/SidebarFields/TextSidebarField.js
- assets/src/setupCustomSidebar.js
Description
See [PLANET-6960](https://jira.greenpeace.org/browse/PLANET-6960)
Associated [PR](https://github.com/greenpeace/planet4-master-theme/pull/1866)
Testing
On your local or [Umbriel Test Instance](https://www-dev.greenpeace.org/test-umbriel/), you can add the Canonical link from the sidebar (Search Engine Optimizations section), to any post type and update the page. On reload in the editor you should still see the data that you entered, and when inspecting the page in the frontend you should see the correct link tag added to the head.
> PLANET-6960 Add sidebar option to define canonical link

- assets/src/block-templates/issues/block.json
- assets/src/block-templates/issues/index.js
- assets/src/block-templates/issues/template.js
- assets/src/block-templates/template-list.js
- assets/src/components/Image/ImageBlockEdit.js
- assets/src/styles/blocks/core-overrides/Image.scss
- classes/patterns/class-issues.php
- planet4-gutenberg-blocks.php
Ref: [PLANET-6942](https://jira.greenpeace.org/browse/PLANET-6942)
- Converted the issues pattern to a block template
- Replaced the `core/media-text` to `core/image` which works better with media sizes (`width`, `height`). The `core/media-text` works with `%` and it's difficult to follow exactly the UI. 
[Demo page](https://www-dev.greenpeace.org/test-rhea/convert-issues-pattern-to-a-block-template/)
> Convert Issues pattern to a block template

- assets/src/block-templates/page-header/block.json
- assets/src/block-templates/page-header/index.js
- assets/src/block-templates/page-header/template.js
- assets/src/block-templates/template-list.js
- classes/patterns/class-pageheader.php
- planet4-gutenberg-blocks.php
**Description**
- Converted the Page Header pattern to a block template.
- Used the same code to handle both left and right page headers, added a condition in the `PageHeader` class to handle side image position based on the `media_position` variable.
> PLANET-6944 Convert Page Header Pattern into a Block Template

- assets/src/block-templates/highlighted-cta/block.json
- assets/src/block-templates/highlighted-cta/index.js
- assets/src/block-templates/highlighted-cta/template.js
- assets/src/block-templates/template-list.js
- assets/src/blocks/Covers/TakeActionCovers.js
- classes/patterns/class-highleveltopic.php
- classes/patterns/class-highlightedcta.php
- planet4-gutenberg-blocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-6941
> Following [ADR-0019](https://docs.google.com/document/d/18pN7U4_v5BRjxeemGyQUGXvxZy-bjCr1XpIKKv5IQb0), this is about converting the Highlighted CTA pattern.
> Requirements
>    - Convert pattern to Block Template
>    - Update other patterns that may include this one
>    - Show pattern only on the Patterns selection list
Tiny fix on _Take Action Covers_, variables set to `false` are throwing errors in the console when the Layout selector is loading.
- Create a new page
- Look for the _Highlighted CTA_ block in the block inserter
- the block template should appear
- Insert a _Highlighted CTA_ block
- it should work and look the same as the previous pattern
- the source code in the Code Editor shows the tag `<!-- …
> PLANET-6941: Convert Highlighted CTA Pattern into a Block Template

- assets/src/styles/blocks/Spreadsheet/SpreadsheetStyle.scss
Fixes greenpeace/planet4#183
Added style `white-space: pre-wrap;` to table cells. That way, line breaks from the source sheet will be rendered in the frontend.
Here's a Google sheet for testing:
- Edit URL: https://docs.google.com/spreadsheets/d/1-IcRk5UXDqg9Mxi-A8hzkJqJNbx-V1O5_IGtfSNa-Mw/edit?usp=sharing
- Published URL (use this one in the block): https://docs.google.com/spreadsheets/d/e/2PACX-1vRtQznqXzrUZzrE1KvzI9lQ1O4sTZhNHNdIg87b_BsyQ2qzqHfQcn8mJ7Jd29maqNk9Zsp24dohCFZi/pubhtml?gid=0&single=true
> Change style to render line breaks in table cells

- classes/blocks/class-covers.php
Ref: https://jira.greenpeace.org/browse/PLANET-7044 
Ref: https://github.com/greenpeace/planet4-master-theme/pull/1911
---
Since we are completely removing the Information Architecture section, we should adjust this check to work with the new setting.
> PLANET-7044 Adjust Covers taxonomy check to new IA setting

- planet4-gutenberg-blocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-7033
> When adding multiple items in either unordered or numeric lists in a page/article, simple hitting Enter does not add a new row with a new item.
It is not possible to add a new list item without allowing the core/list-item block.
Issue introduced by WordPress 6.1, cf. https://github.com/WordPress/gutenberg/issues/47185#issuecomment-1384637446
- Add a new page
- Add a List block
- add text to the first item, and use `enter` to add a new item
- a new list item line should appear
> PLANET-7033: Allow list item in block list

- .gitignore
- classes/class-loader.php
- package-lock.json
- package.json
- playwright.config.js
- tests/e2e/404.spec.js
See [PLANET-7055](https://jira.greenpeace.org/browse/PLANET-7055)
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/1908
On local, run `npm install` to install Playwright and its needed dependencies, and then to run the tests you can use the following commands:
- `npx playwright test` for all tests
- `npx playwright test tests/e2e/404.spec.js` for individual tests (added this very simple one for now just to test the setup)
> PLANET-7055 Setup Playwright

- classes/class-loader.php
Fix warning of undefined value  
`Notice: Undefined index: 404_page_bg_image in /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks/classes/class-loader.php on line 459`
`'page_bg_image_404'          => $option_values['404_page_bg_image'],`
> Hotfix: Fix undefined values

- assets/src/styles/blocks/Accordion/AccordionEditorStyle.scss
- assets/src/styles/blocks/Accordion/AccordionStyle.scss
- assets/src/styles/blocks/Articles.scss
- assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
- assets/src/styles/blocks/Columns.scss
- assets/src/styles/blocks/Cookies.scss
- assets/src/styles/blocks/CookiesEditor.scss
- assets/src/styles/blocks/Covers/CoversStyle.scss
- assets/src/styles/blocks/Covers/styles/ContentCovers.scss
- assets/src/styles/blocks/ENForm/ENFormStyle.scss
- assets/src/styles/blocks/ENForm/components/_enform-side-style.scss
- assets/src/styles/blocks/Gallery/styles/GalleryCarousel.scss
- assets/src/styles/blocks/Happypoint.scss
- assets/src/styles/blocks/OldENForm/components/_enform-side-style.scss
- assets/src/styles/blocks/SocialMedia/SocialMediaStyle.scss
- assets/src/styles/blocks/SplitTwoColumns.scss
- assets/src/styles/blocks/Spreadsheet/SpreadsheetStyle.scss
- assets/src/styles/blocks/Submenu.scss
- assets/src/styles/blocks/TakeActionBoxout/style.scss
- assets/src/styles/blocks/Timeline/TimelineStyle.scss
- assets/src/styles/editorStyle.scss
- assets/src/styles/style.scss
This makes our code easier to customise, in preparation of [PLANET-6984](https://jira.greenpeace.org/browse/PLANET-6984) and other tickets related to the new identity. In some cases I was able to completely remove the usage of `$grey-80` since it was applied from somewhere else anyway.
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/1920
Everything should still look the same.
> Use CSS variables wherever possible for links and colors

- assets/src/blocks/Covers/CoversEditor.js
Ref. https://jira.greenpeace.org/browse/PLANET-7025
The Covers block Grid view have a option to load more covers on click of "Load more" button.  The "Load more" string is saved in `readMoreText` block attribute as a plain text, also we don't have a backend option to update the 'readMoreText' value after covers block added on page. 
The covers block snippet -
```
<div class="wp-block-planet4-blocks-covers is-style-content" data-render="planet4-blocks/covers" data-attributes="{&quot;attributes&quot;:{&quot;cover_type&quot;:&quot;content&quot;,&quot;initialRowsLimit&quot;:1,&quot;title&quot;:&quot;new Cover block&quot;,&quot;description&quot;:&quot;Content covers block&quot;,&quot;tags&quot;:[19,18,8],&quot;post_types&quot;:[],&quot;posts&quot;:[],&quot;version&quot;:2,&quot;layout&quot;:&qu …
```
> PLANET-7025 Fix Covers block 'Load more' button translation issue

- assets/src/variations/stretched-link/index.scss
See [PLANET-7094](https://jira.greenpeace.org/browse/PLANET-7094)
It seems it's not recommended to use `all` in CSS transitions, since browsers might interpret it in different ways. For Safari specifically, with a transition on the `transform` property, you need to add an additional `transformZ(0)` to the parent for some reason 😬 
In Safari you can test the broken version with [this page](https://www.greenpeace.org/finland/metsat/) and the fixed version with [this page](https://www-dev.greenpeace.org/test-leda/52387-2/) for example. Make sure it also works as expected in other browsers.
> PLANET-7094 Fix broken rounded images animation in Safari

- assets/src/styles/blocks/core-overrides/Image.scss
See [PLANET-7013](https://jira.greenpeace.org/browse/PLANET-7013)
Before this fix, in certain screen sizes the images became more oval, especially when more items were added. This solution uses the `aspect-ratio` CSS property which is supported by [all major browsers except IE](https://caniuse.com/mdn-css_properties_aspect-ratio)
You can compare the broken version [here](https://www.greenpeace.org/finland/metsat/) with the fixed one [here](https://www-dev.greenpeace.org/test-rhea/deep-dive-tests/) for example.
> PLANET-7013 Make sure Deep Dive images are always round

- classes/controller/menu/class-blocks-usage-controller.php
- classes/search/block/class-blockusageapi.php
- classes/search/block/class-blockusagetable.php
See [PLANET-7087](https://jira.greenpeace.org/browse/PLANET-7087)
Instead we use the new blocks and patterns reports that were previously in beta
In the backend, either on local or on the [pandora test instance](https://www-dev.greenpeace.org/test-pandora), in the `Blocks` menu you should no longer see the old block report and the previous `(Beta)` suffixes. When clicking on `Blocks > Report` or directly on `Blocks` you should open the blocks report, whereas on clicking `Blocks > Pattern Report` you should open the pattern report. Both reports should still work as expected, and you should be able to access them both as an admin and as an editor.
> PLANET-7087 Remove old blocks report

- assets/src/blocks/Gallery/GalleryBlock.js
- assets/src/blocks/Gallery/GalleryCarousel.js
- assets/src/blocks/Gallery/GalleryFrontend.js
- assets/src/blocks/Gallery/GalleryGrid.js
- assets/src/blocks/Gallery/GalleryScript.js
- assets/src/blocks/Gallery/GalleryThreeColumns.js
- assets/src/components/Lightbox/Lightbox.js
- assets/src/components/Lightbox/useLightbox.js
- assets/src/functions/hydrateBlock.js
- classes/blocks/class-base-block.php
- classes/blocks/class-gallery.php
Ref: https://jira.greenpeace.org/browse/PLANET-6874
**Major changes**
- `hydrate` the component because it was using a deprecated method when saved it. Now it's a fully SSR Component.
- Fix Gallery styles, not only the `slider`.
- Improve its performance.
- Update documentation.
**In addition to this, I've also left a bunch of comments on this PR explaining the reason of most of the new changes.**
👉  [Demo page](https://www-dev.greenpeace.org/test-nix/gallery-block-demo-page/)
> PLANET-6874: Fix the Gallery block

- assets/src/blocks/Columns/ColumnsTasks.js
- assets/src/styles/blocks/Accordion/AccordionStyle.scss
- assets/src/styles/blocks/Columns.scss
See [the designs](https://www.figma.com/file/9NtbY8n3at8uOEJTsLrETb/P4-Design-System?node-id=274-12607&t=aSmlq5qD1NFaw0rC-0)
These can be applied regardless of the new identity, the color changes though are part of the new identity so they are handled in a [separate master-theme PR](https://github.com/greenpeace/planet4-master-theme/pull/1952). Similarly, the new link styles will be added as part of [PLANET-6994](https://jira.greenpeace.org/browse/PLANET-6994).
You can test the improved version of this block on mobile/tablet either by creating one on local, or by checking [this page](https://www-dev.greenpeace.org/test-phoebe/the-new-columns-tasks/) that I made for UAT. The desktop version should not be changed at all.
> Small improvements for Columns Tasks on mobile/tablet

- assets/src/styles/blocks.scss
Reported by Quentin on [Slack](https://greenpeace-gpi.slack.com/archives/G015K63081W/p1680092872553299)
These should only be imported in the editor
> Remove stretched link edit styles from frontend

- assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
- assets/src/blocks/Spreadsheet/SpreadsheetEditorScript.js
- assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
- assets/src/styles/blocks/Spreadsheet/SpreadsheetStyle.scss
- classes/blocks/class-spreadsheet.php
This new version creates separate CSS variables for all colors of the block, that will be easier to override for the new identity ([PLANET-7017](https://jira.greenpeace.org/browse/PLANET-7017)). The actual color changes however are made in the master-theme repo, in [this PR](https://github.com/greenpeace/planet4-master-theme/pull/1967).
**Note:** we'll need to figure out how to deal with existing blocks, but [there are only 18 in production](https://docs.google.com/spreadsheets/d/1uAmZLIWYsxrBByqbhoF_vVtSM7WGebYWIc0xftPRPwE/edit?pli=1#gid=359432436) so we can probably manually update them. This new version should still work but they'll just show up as grey in the frontend regardless of the color previously selected, but it will show the `block recovery` message in the editor.
Add a …
> PLANET-7017 Refactor Spreadsheet block for new identity implementation

- assets/src/block-templates/highlighted-cta/template.js
See [PLANET-7022](https://jira.greenpeace.org/browse/PLANET-7022)
This is just about changing the background color that is applied by default, if the new identity styles are enabled. I know it's a bit different from what's required in the ticket, but as far as I know we can't change the color palette per pattern, only per block 😕 So this is why we only change the default background color, and anyway now when the new identity styles are enabled we only have access to the new color palette. For the text color, I don't think that we can change it automatically depending on what background editors select, but WordPress does show a warning if the color combination is hard to read so hopefully this is enough (in addition to the examples in the design system).
**Related PR:** …
> PLANET-7022 Apply new identity colors to Highlighted CTA pattern

- assets/src/blocks/ENForm/ENFormFrontend.js
There is an issue with the `useSelect` hook, which seems to be `undefined`. That's why I've implemented an extra validation on that. It occurs when no Planet 4 Engaging Networks form has been added. 
**No ticket needed.**
1. Just create a new ENForm and don't set any P4 EN Networks Form in any test instance.
2. Preview the page
3. Open the console and you'll see the error
Here is a [demo page](https://www-dev.greenpeace.org/test-neptune/empty-enform-demo-page/) to confirm the fixed issue.
> Hotfix: ENForm fields select validation when no P4 EN Networks Form

- assets/src/styles/blocks/PageHeader.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7130
The content is broken on smaller screens less than ~550px. Here is the [demo page with the issue](https://www-dev.greenpeace.org/international/test-page-header/) 
This is the [demo page with the fix](https://www-dev.greenpeace.org/test-phoebe/test-page-header/)
1. Create a new page
2. Add two page header patterns with different content
3. Preview the page on a small screen
> PLANET-7130: Fix PageHeader content width

- assets/src/blocks/Accordion/AccordionEditorScript.js
- assets/src/styles/blocks/Accordion/AccordionStyle.scss
See [PLANET-7014](https://jira.greenpeace.org/browse/PLANET-7014)
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/1974
You can add an Accordion block on local or on the janus test instance, making sure you enabled the new identity styles, and test out the various styles. You can also check [this page](https://www-dev.greenpeace.org/test-janus/all-the-accordions/) that I made for UAT. Make sure the block also still looks fine with the "old" styles, if the new identity is not enabled.
> PLANET-7014 Apply new identity colors to Accordion block

- assets/src/styles/blocks/Covers/styles/CampaignCovers.scss
- assets/src/styles/blocks/SplitTwoColumns.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7138
The idea comes from [here](https://github.com/greenpeace/planet4-master-theme/pull/1996#discussion_r1174932194)
Demo page: https://www-dev.greenpeace.org/test-proteus/test-text-links-without-shadow/
> PLANET-7138: Remove text shadows on links

- assets/src/styles/blocks/SplitTwoColumns.scss
Following up #1044, we noticed that we forgot to add the `:hover` pseudo.
> Implement missing hover styles to the SplitTwoColumns block

- assets/src/blocks/SocialMediaCards/SocialMediaCards.js
- assets/src/blocks/SubPages/SubPages.js
Ref: https://jira.greenpeace.org/browse/PLANET-7129
After Wordpress 6.2, this function is exported as default in a separate module.
Taken from the [Wordpress's official document](https://make.wordpress.org/core/2023/03/06/add-new-prop-to-serversiderender-component/)
> The ServerSideRender component has moved to its own package/script in WordPress 5.3 and accessing it using wp.components.ServerSideRender has been deprecated since. Starting WordPress 6.2, you should be able to access it directly using wp.serverSideRender.
And here is their [changed code](https://github.com/WordPress/gutenberg/pull/46106/files#diff-77df04898762524cd09f00a391d4977694eeed141eba84bcde4ca8eb7473a40bL51-L56).
__Please make sure to test and merge this new functionality after the next PRs__
- …
> PLANET-7129: Change the import of the ServerSideRender function

- tests/e2e/editor-selector.spec.js
**Description: [PLANET-7063](https://jira.greenpeace.org/browse/PLANET-7063)**
Testing: 
run `npx playwright test tests/e2e/editor-selector.spec.js` in the plugin directory and the test will run.
Ref PR: https://github.com/greenpeace/planet4-master-theme/pull/2003
> PLANET-7063 Re-write the Editor Selector test in Playwright

- assets/src/block-templates/edit.js
- assets/src/blocks/Accordion/AccordionEditor.js
- assets/src/blocks/Articles/ArticlesEditor.js
- assets/src/blocks/CarouselHeader/Caption.js
- assets/src/blocks/Columns/ColumnsEditor.js
- assets/src/blocks/Columns/EditableColumns.js
- assets/src/blocks/Counter/CounterEditor.js
- assets/src/blocks/Covers/CoversEditor.js
- assets/src/blocks/Gallery/GalleryEditor.js
- assets/src/blocks/Happypoint/HappypointEditor.js
- assets/src/blocks/Media/MediaEditor.js
- assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
- assets/src/blocks/SocialMediaCards/SocialMediaCards.js
- assets/src/blocks/Submenu/SubmenuEditor.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
- assets/src/blocks/Timeline/TimelineEditorScript.js
We have implemented different ways to get stuffs from the [WP's Block Editor package](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor). 
1. `import {...} from @wordpress/block-editor`
2. `import {...} from @wordpress/blockEditor`
3. `const {...} = wp.blockEditor;`
And I'd prefer to go with `import {...} from @wordpress/block-editor` since is the most used within our codebase.
This pull request is related to this [comment](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1039#issuecomment-1519551415) from #1039
> Standarize the import/destructure of the WP's block editor package

- tests/e2e/carousel-header.spec.js
- tests/e2e/editor-selector.spec.js
- tests/e2e/take-action-boxout.spec.js
- tests/e2e/tools/lib/columns.js
- Replace `fill` with `type` when typing `/block name` to ensure a popover with blocks choices appears
- Replace template modal closing logic
This allows the `planet4-develop` tests to pass https://app.circleci.com/pipelines/github/greenpeace/planet4-develop/152/workflows/27553cb1-eaa5-4f72-aa3b-e8afcca3f496
- [theme report](https://output.circle-artifacts.com/output/job/9b669246-4329-4da9-93b2-bbfe014ace4b/artifacts/0/home/circleci/artifacts/playwright/themes/e2e-report/index.html)
- [plugin report](https://output.circle-artifacts.com/output/job/9b669246-4329-4da9-93b2-bbfe014ace4b/artifacts/0/home/circleci/artifacts/playwright/plugins/e2e-report/index.html)
> Stabilize some e2e tests

- assets/src/block-templates/deep-dive-topic/block.json
- assets/src/block-templates/deep-dive-topic/index.js
- assets/src/block-templates/deep-dive-topic/template.js
- assets/src/block-templates/page-header/block.json
- assets/src/block-templates/page-header/template.js
- assets/src/block-templates/reality-check/template.js
- assets/src/block-templates/template-list.js
- classes/patterns/class-deepdivetopic.php
- planet4-gutenberg-blocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-7079
Demo of the _Deep Dive Topic_ layout done as a Block template.
Same pros as other templates:
- easy to identify in editor and in block report
- easier to maintain
> PLANET-7079: Convert Deep Dive Topic pattern layout into a Block Template

- assets/src/block-templates/homepage/block.json
- assets/src/block-templates/homepage/index.js
- assets/src/block-templates/homepage/template.js
- assets/src/block-templates/issues/block.json
- assets/src/block-templates/issues/template.js
- assets/src/block-templates/template-list.js
- assets/src/block-templates/templates/gravity-form-with-text.js
- classes/patterns/class-homepage.php
- planet4-gutenberg-blocks.php
**Description:** https://jira.greenpeace.org/browse/PLANET-7083
**Testing:** 
Open the editor on the assigned instance or on your local on this branch and the layout for the Homepage pattern should still look the same.
> PLANET-7083 Convert Homepage pattern layout to Block Templates

- assets/src/block-templates/campaign/block.json
- assets/src/block-templates/campaign/index.js
- assets/src/block-templates/campaign/template.js
- assets/src/block-templates/homepage/template.js
- assets/src/block-templates/page-header/block.json
- assets/src/block-templates/page-header/template.js
- assets/src/block-templates/template-list.js
- assets/src/block-templates/templates/gravity-form-with-text.js
- classes/patterns/class-campaign.php
- planet4-gutenberg-blocks.php
See [PLANET-7082](https://jira.greenpeace.org/browse/PLANET-7082)
You should still be able to add the Campaign pattern layout from the `Layouts` category, and it should look just like before.
> PLANET-7082 Convert Campaign pattern layout into a Block Template

- assets/src/components/Sidebar/SearchEngineOptimizationsSidebar.js
See [PLANET-7170](https://jira.greenpeace.org/browse/PLANET-7170)
This is to clarify that the permalink will be used by default
> PLANET-7170 Add help text to canonical link sidebar option

- assets/src/block-templates/take-action/block.json
- assets/src/block-templates/take-action/index.js
- assets/src/block-templates/take-action/template.js
- assets/src/block-templates/template-list.js
- classes/patterns/class-takeaction.php
- planet4-gutenberg-blocks.php
See [PLANET-7084](https://jira.greenpeace.org/browse/PLANET-7084)
You should still be able to add the Take Action pattern layout from the `Layouts` category, and it should look just like before.
> PLANET-7084 Convert Take Action pattern layout into a Block Template

- tests/e2e/spreadsheet.spec.js
See [PLANET-5423](https://jira.greenpeace.org/browse/PLANET-5423)
This is to increase our test coverage
On local, you can check the test either using the VSCode extension, or via command line by running `npx playwright test tests/e2e/spreadsheet.spec.js`
> PLANET-5423 Add Playwright test for Spreadsheet block

- tests/e2e/carousel-header.spec.js
- tests/e2e/editor-selector.spec.js
- tests/e2e/enform.spec.js
- tests/e2e/split-two-columns.spec.js
- tests/e2e/tools/lib/columns.js
- tests/e2e/tools/lib/covers.js
- tests/e2e/tools/lib/login.js
- tests/e2e/tools/lib/new-page.js
- tests/e2e/tools/lib/new-post.js
- tests/e2e/tools/lib/nonce.js
This PR includes several things:
- removing/adding some `await` statements
- linting fixes
- adding image selection to the Columns Images test so that the attachments are always there in the frontend
- rewriting parts of the Covers tests, making them easier to read and hopefully less flaky 🤞 
All tests should still pass, but the Covers one with `Take Action` style has an issue where sometimes the block crashes when trying to manually select pages, I'm still looking into that 👀
> Improve Playwright tests 

- assets/src/block-templates/action/block.json
- assets/src/block-templates/action/index.js
- assets/src/block-templates/action/template.js
- assets/src/block-templates/template-list.js
- assets/src/block-templates/templates/gravity-form-with-text.js
- classes/patterns/class-action.php
- classes/patterns/class-deepdivetopic.php
- planet4-gutenberg-blocks.php
See [PLANET-7078](https://jira.greenpeace.org/browse/PLANET-7078)
This is easier to maintain
You should still be able to add the `Action` pattern layout from the sidebar, and it should look just like before the change.
> PLANET-7078 Convert Action pattern layout into a Block Template

- assets/src/block-templates/get-informed/block.json
- assets/src/block-templates/get-informed/index.js
- assets/src/block-templates/get-informed/template.js
- assets/src/block-templates/homepage/template.js
- assets/src/block-templates/issues/block.json
- assets/src/block-templates/issues/template.js
- assets/src/block-templates/template-list.js
- classes/patterns/class-getinformed.php
- planet4-gutenberg-blocks.php
See [PLANET-7081](https://jira.greenpeace.org/browse/PLANET-7081)
This is easier to write and maintain
Either on local or on the test instance, you should still be able to add the `Get Informed` pattern layout, and it should look the same as before.
> PLANET-7081 Convert Get Informed pattern layout to block template

- assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
- assets/src/blocks/CarouselHeader/CarouselHeaderScript.js
- assets/src/blocks/Covers/CoversScript.js
- assets/src/blocks/ENForm/ENFormScript.js
- assets/src/blocks/Gallery/GalleryBlock.js
- assets/src/blocks/Spreadsheet/SpreadsheetScript.js
- assets/src/components/Lightbox/setupLightboxForImages.js
- assets/src/frontendIndex.js
- assets/src/functions/hydrateBlock.js
**Description: [PLANET-7189](https://jira.greenpeace.org/browse/PLANET-7189)**
**Testing:**
Nothing should change visually, only upgraded imports to match React 18 [recommendations](https://react.dev/blog/2022/03/08/react-18-upgrade-guide).
> PLANET-7189 Remove our uses of ReactDOM.render

- classes/blocks/class-carouselheader.php
Ref: https://sentry.greenpeace.org/organizations/greenpeace-org/issues/802/
```
Twig\Error\RuntimeError
An exception has been thrown during the rendering of a template ("{"error":{"code":403,"message":"testgpap@planet-4-151612.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).","errors":[{"message":"testgpap@planet-4-151612.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).","domain":"global","reason":"forbidden"}]}}").
```
Catch exception instead of crashing when gcloud returns 403 for images in Carousel.
- This was breaking homepage on …
> Fix broken page on gcloud 403

- assets/src/blocks/CarouselHeader/CarouselControls.js
- assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
- assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
- assets/src/blocks/CarouselHeader/Sidebar.js
- assets/src/blocks/CarouselHeader/SidebarSlide.js
- assets/src/blocks/CarouselHeader/useSlides.js
Revert some change from [PLANET-7189](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/commit/7e6724d44c39abc4b734e879e6dd6f4a75de54e0#) PR
**Testing:**
- You can test fix at - https://www-dev.greenpeace.org/test-telesto/test-carousel-header-block-fliker-image-issue/
[Demo page](https://www-dev.greenpeace.org/test-telesto/carousel-header-demo-page/) with the fix (editor and frontend), also tested on the [international dev site](https://github.com/greenpeace/planet4-international/blob/main/composer-local.json#L6).
> PLANET-7217 Fix carousel header flicker issue

- assets/src/ImageBlockExtension.js
- assets/src/blocks/Accordion/AccordionEditor.js
- assets/src/blocks/CarouselHeader/EditableBackground.js
- assets/src/blocks/Submenu/SubmenuEditor.js
- assets/src/functions/hydrateBlock.js
Ref: https://jira.greenpeace.org/browse/PLANET-7153
Since we're about to upgrade to [WordPress 6.2 “Dolphy”](https://wordpress.org/news/2023/03/dolphy/) we would need to make sure our code is up to date with the new requirements. Some of them has been deprecated since [WordPress 6.1 “Misha”](https://wordpress.org/news/2022/11/misha/).
**The current PR should be merged after**
- https://github.com/greenpeace/planet4-base/pull/244
Make sure to run `Wordpress 6.2` on your local.
> PLANET-7153: Follow up Wordpress 6.2 deprecations

- assets/src/functions/hydrateBlock.js
Before the implementation of `hydrateRoot` the `blockNode` has been evaulated as an `Array` instead of an `HTML Selector`. This `if ` clause is added to avoid inconsistencies within the component since in some cases we're getting a warning message something similar to "`<div>` is rendered but should be `<p>`".
The problem was raised after the merge of [this line](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/commit/baf89cb928e78228d8776165ddd021f365d1118c#diff-ea83b4bc3c4de5b445d5e8cc611f40046841a40eb55e6205430201302584c4dcR16-R18) and it affected the `CarouselHeader` among other blocks.
Using the current branch within the [international dev site](https://github.com/greenpeace/planet4-international/blob/main/composer-local.json#L6).
> Fix hydrateBlock method

- assets/src/blocks/Columns/Columns.js
- assets/src/blocks/Columns/imageSizes.js
- assets/src/blocks/Covers/imageSizes.js
- classes/blocks/class-columns.php
Ref: https://jira.greenpeace.org/browse/PLANET-6855
- Update Covers images `sizes` attribute to various viewport widths
- Update Columns code to insert images `srcset` and `sizes` attributes
Locally, install gpi `npm run nro:install international`
- compare images used for `/tag/about-us/` , the image format queried should now vary depending on viewport
- use Network tab in browser inspector tools, filter by image filename
- on prod
- on local
> PLANET-6855: Add covers thumbnail size for large screen

- assets/src/blocks/GuestBook/GuestBookBlock.js
- assets/src/blocks/GuestBook/GuestBookEditorScript.js
- assets/src/blocks/GuestBook/GuestBookFrontend.js
- assets/src/blocks/GuestBook/GuestBookScript.js
- assets/src/editorIndex.js
- assets/src/frontendIndex.js
- classes/blocks/class-guestbook.php
- webpack.config.js
This is to stop using the deprecated `frontendRendered` function
> Refactor GuestBook block

- assets/src/blocks/Counter/CounterBlock.js
- assets/src/blocks/Counter/CounterEditor.js
- assets/src/blocks/Counter/CounterEditorScript.js
- assets/src/blocks/Counter/CounterFrontend.js
- assets/src/blocks/Counter/CounterScript.js
- assets/src/editorIndex.js
- assets/src/frontendIndex.js
- assets/src/styles/blocks.scss
- assets/src/styles/blocks/Counter/CounterStyle.scss
- classes/blocks/class-counter.php
- webpack.config.js
This is to stop using the deprecated `frontendRendered` function. This PR also includes splitting the files for the Counter block.
You can check out different styles of the block now using hydration on local or on [this page](https://www-dev.greenpeace.org/test-janus/counter-tests/) for example.
> PLANET-6917 Refactor Counter block to use hydration

- assets/src/styles/blocks/PageHeader.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7242
Requires: https://github.com/greenpeace/planet4-master-theme/pull/2113
> On some of the header pages, the title may appear as though it's blocked or covered by the background of the second line.
__Before__
__After__
[Test page on Leda](https://www-dev.greenpeace.org/test-leda/1176-2/)
> PLANET-7242: Fix title text covered by background

- assets/src/styles/blocks/Gallery/styles/GalleryCarousel.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7252
> Replace the "GP Sans" with the "Source Sans3" typeface for the caption of images in the Gallery Carousel block.
On local or [test instance](https://www-dev.greenpeace.org/test-rhea/about-us-2/)
- check that carousel caption font is `SourceSans3` with new Visual identity is enabled (in Appearance > Customize > Site Identity)
> PLANET-7252: Incorrect typeface used for caption in Gallery Carousel block

- planet4-gutenberg-blocks.php
- tests/e2e/split-two-columns.spec.js
This disables the block when new IA is enabled. The block relies on Explore page children pages, so it can't be used when new IA feature flag is on.
This also conditionally runs its e2e test only when new IA is off.
1. Disable new IA from: _Planet 4 > Navigation_
2. Navigate to the plugin directory and run: `npx playwright test tests/e2e/split-two-columns.spec.js`
3. Test should pass
4. Enabled new IA form: _Planet 4 > Navigation_
5. Re-run: `npx playwright test tests/e2e/split-two-columns.spec.js`
6. Test should pass (report should say skipped)
> Disable Split Two Columns blocks on new IA

- classes/search/block/class-blockusage.php
- classes/search/block/class-blockusageapi.php
Block count was filtering blocks for only post/page/campaign post types, missing at least p4_action.
- Create an action page (`p4_action`) and add a block to it
- it should appear in block report (Blocks > Report)
> Use requested post types in block count

- assets/src/blocks/Accordion/AccordionEditor.js
- assets/src/blocks/Articles/ArticlesEditor.js
- assets/src/blocks/CarouselHeader/Caption.js
- assets/src/blocks/Columns/ColumnsEditor.js
- assets/src/blocks/Columns/EditableColumns.js
- assets/src/blocks/Cookies/CookiesFrontend.js
- assets/src/blocks/Counter/CounterEditor.js
- assets/src/blocks/Covers/CoversEditor.js
- assets/src/blocks/ENForm/ENFormInPlaceEdit.js
- assets/src/blocks/Gallery/GalleryEditor.js
- assets/src/blocks/Media/MediaEditor.js
- assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
- assets/src/blocks/SplitTwoColumns/SplitTwoColumnsInPlaceEdit.js
- assets/src/blocks/Submenu/SubmenuEditor.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
- assets/src/blocks/Timeline/TimelineEditorScript.js
[PLANET-6958](https://jira.greenpeace.org/browse/PLANET-6958).
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1042
- [Migrate to InnerBlocks](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/nested-blocks-inner-blocks/)
> PLANET-6958: Remove deprecated multiline prop

- assets/src/blocks/SplitTwoColumns/SplitTwoColumnsEditor.js
- assets/src/blocks/SplitTwoColumns/SplitTwoColumnsFrontend.js
- assets/src/blocks/SplitTwoColumns/SplitTwoColumnsInPlaceEdit.js
- assets/src/blocks/SplitTwoColumns/SplitTwoColumnsSettings.js
- assets/src/blocks/SplitTwoColumns/register.js
- assets/src/frontendIndex.js
We should use camel case. This is in preparation for a bigger refactor to stop using the deprecated `frontendRendered` function.
> Fix Split Two Columns components name case

- assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
- assets/src/replaceTaxonomyTermSelectors.js
See [PLANET-7256](https://jira.greenpeace.org/browse/PLANET-7256)
For this component we override a [WordPress component](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/post-taxonomies/flat-term-selector.js) that they rewrote since then, so we need to update our version too. We essentially use the same code but remove the possibility to create new post types in the editor.
You can test either on any post either on local or on the atlas test instance, and make sure creating new post types isn't possible via the editor.
> PLANET-7256 Refactor post Post Types selector

- assets/src/blocks/SplitTwoColumns/SplitTwoColumnsEditor.js
Otherwise we get a console warning: 
```
Warning: Cannot update a component (`EditorInitialization`) while rendering a different component (`SplitTwoColumnsEditor`).
```
Both existing and new Split Two Columns blocks should still work as expected. On `main` branch you should see the console warning, but not on this branch.
> Fix Split Two Columns editor component

- assets/src/blocks/ENForm/ENFormInPlaceEdit.js
This will avoid to create new paragraphs [after the removal of the multiline prop](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1050).
Create a new `ENForm` and fill out a description
https://developer.wordpress.org/reference/functions/wpautop/
> Remove autop wrapped function

- assets/src/blocks/Columns/Columns.js
Without this fix we sometimes pass a boolean as src set, and that results in the following console warning:
```
Warning: Received `false` for a non-boolean attribute `srcSet`.
If you want to write it to the DOM, pass a string instead: srcSet="false" or srcSet={value.toString()}.
If you used to conditionally omit it with srcSet={condition && value}, pass srcSet={condition ? value : undefined} instead.
```
In order to solve this, I applied the same fix as the one we used for the [Articles block](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/assets/src/blocks/Articles/ArticlePreview.js#L71).
On local I see this warning on the homepage on the `main` branch, but not after this fix.
> Fix Columns block src set console warnings

- classes/blocks/class-accordion.php
- classes/blocks/class-carouselheader.php
- classes/blocks/class-enform.php
- classes/blocks/class-gallery.php
- classes/blocks/class-guestbook.php
- classes/blocks/class-socialmedia.php
- classes/blocks/class-spreadsheet.php
- classes/blocks/class-takeactionboxout.php
- classes/blocks/class-timeline.php
- classes/class-loader.php
- tests/e2e/spreadsheet.spec.js
Ref: https://jira.greenpeace.org/browse/PLANET-7197
Related to: https://github.com/greenpeace/planet4-master-theme/pull/2020
Adapt blocks loading logic to allow master-theme to load blocks in priority.
- load all blocks via hook `add_action('init')`
- blocks were not uniformly loaded, some right away with plugin loading and others through `init`
- loading globally with `init` allows to set a `priority` parameter and make it higher(later) than master-theme
- fix GuestBook assets loading
- camelized name was not matching assets name
- rewrite Spreadsheet test to not depend on external API
- mock of spreadsheet API calls with static data, this will speed the test and avoid a backend call to google API
> PLANET-7197: Adapt block loading order

- assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
- assets/src/blocks/Gallery/GalleryFrontend.js
See [PLANET-7279](https://jira.greenpeace.org/browse/PLANET-7279)
We need to force a re-render to make sure that the component renders the same content server-side as it does during the initial client-side render.
I found this explanation and fix [here](https://nextjs.org/docs/messages/react-hydration-error#solution-1-using-useeffect-to-run-on-the-client-only).
On local on `main` branch, I see the hydration warnings on the homepage for example but on this branch they are gone.
> Fix hydration-related console errors

- assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
**REF: [PLANET-7287](https://jira.greenpeace.org/browse/PLANET-7287)**
**Testing:**
Before fix block crashed when trying to add in the editor. Now the block can be added and used.
> PLANET-7287 Social Media block crashes in the editor

- assets/src/blocks/Timeline/TimelineBlock.js
- assets/src/blocks/Timeline/TimelineFrontend.js
- assets/src/blocks/Timeline/TimelineScript.js
- classes/blocks/class-timeline.php
This is to stop using the deprecated `frontendRendered` function.
The Timeline (both old and new blocks) should still behave as expected. You can use [this sheet](https://docs.google.com/spreadsheets/d/1XruuRzjiu4t2ia7NaBXMqItr4NAbc7ctcolg1uhlIL4/edit#gid=0) for testing! It seems that the Timeline block is broken in test instances, I get a message error there (both before and after this refactor, there's actually a [bug ticket](https://jira.greenpeace.org/browse/PLANET-7175) about it) but on local it works fine
> Refactor Timeline block to use hydration

- assets/src/blocks/ENForm/ENFormBlock.js
- assets/src/blocks/ENForm/ENFormFrontend.js
- assets/src/blocks/ENForm/ENFormScript.js
- assets/src/blocks/ENForm/deprecated/ENFormV2.js
- assets/src/frontendIndex.js
- classes/blocks/class-enform.php
This is to stop using the deprecated `frontendRendered` function
Both existing and new EN form blocks should still behave as expected in the frontend and in the editor.
> Refactor ENForm block to use hydration

- assets/src/blocks/SplitTwoColumns/SplitTwoColumnsBlock.js
- assets/src/blocks/SplitTwoColumns/SplitTwoColumnsEditor.js
- assets/src/blocks/SplitTwoColumns/SplitTwoColumnsFrontend.js
- assets/src/blocks/SplitTwoColumns/SplitTwoColumnsScript.js
- classes/blocks/class-splittwocolumns.php
This is to stop using the deprecated `frontendRendered` function
Both existing and new Split Two Columns blocks should still behave as expected.
> Refactor Split Two Columns block to use hydration

- assets/src/blocks/Articles/ArticlesBlock.js
- assets/src/blocks/Articles/ArticlesEditor.js
- assets/src/blocks/Articles/ArticlesFrontend.js
- assets/src/blocks/Articles/ArticlesScript.js
- classes/blocks/class-articles.php
This is to stop using the deprecated `frontendRendered` function
Both new and existing Articles blocks (including the ones in posts) should still behave as expected.
> PLANET-6917 Refactor Articles block to use hydration

- assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
- assets/src/blocks/CarouselHeader/CarouselHeaderScript.js
- assets/src/blocks/CarouselHeader/SlideBackground.js
This fixes some console warnings. The new `decoding` attribute [was added with WordPress 6.1](https://www.wpexplorer.com/remove-async-decoding-wordpress-images/). Hopefully this also solves some hydration errors that we see on live sites.
~For some reason, it seems the `decoding` attribute is not added on test instances...~ This attribute is only added when we use hydration, so with old blocks that still use `data-render` it won't be present. Code has been updated to reflect that! 
On the test instance, here are the 2 examples you can use for testing:
- [new block using hydration](https://www-dev.greenpeace.org/test-phoebe/test-hydrated-carouselheader/), should have the new attribute
- [old block not using hydration](https://www-dev.greenpeace.org/test-phoebe/), should **not** have the …
> Add missing attribute to SlideBackground

- assets/src/blocks/Covers/CoversScript.js
- assets/src/blocks/ENForm/ENFormScript.js
- assets/src/blocks/Gallery/GalleryScript.js
- assets/src/blocks/Timeline/TimelineScript.js
- assets/src/functions/hydrateBlock.js
- classes/blocks/class-base-block.php
We need to make sure that blocks without the `data-hydrate` attribute are rendered correctly. Before this fix we would sometimes render blocks with `data-render` inside of a `data-hydrate` attribute which would result in duplicated blocks.
I've added a commit for some old blocks not rendering in the frontend, which might solve [PLANET-7202](https://jira.greenpeace.org/browse/PLANET-7202) for the Gallery block for example
All hydration-related console errors and warnings should be gone. If you have a page with previously duplicated blocks (for example on local I had it on the `Explore` page) it should no longer be happening. All blocks (both with `data-hydrate` and `data-render`) should be rendered properly.
>  Fix hydration errors and duplicated blocks

- assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
This change is based on [this comment](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1102#discussion_r1365445772). It's to avoid creating multiple functions when rendering.
The Spreadsheet sorting function should still behave as expected.
> Refactor Spreadsheet sorting function to use dataset

- assets/src/styles/blocks/PageHeader.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7313
👉 [Demo page](https://www-dev.greenpeace.org/test-nix/1263-2/)
Standardize the header line height avoiding issues within different sizes. Now, the `PageHeader heading` layout is following its [proper layout](https://www.figma.com/file/9NtbY8n3at8uOEJTsLrETb/P4-Design-System?type=design&node-id=720-31483&mode=dev)
> PLANET-7313: Fix header text cut off

- classes/blocks/class-blocklist.php
This was introduced at 9f2037e7b8973601e954bdd7e38a0f1cc7983c4c but broke patterns report since it introduced a new argument with no default value needed at [pattern search](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/9f2037e7b8973601e954bdd7e38a0f1cc7983c4c/classes/search/pattern/class-patterndata.php#L113).
Exception raised before this fix when visiting
`/wp-json/plugin_blocks/v3/plugin_blocks_report/`:
```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function
P4GBKS\Blocks\BlockList::parse_block_list(), 1 passed in
/var/www/html/wp-content/plugins/planet4-plugin-gutenberg-blocks/classes/search/pattern/class-patterndata.php
on line 113 and exactly 4 expected in
/var/www/html/wp-content/plugins/planet4-plugin-gutenberg-blocks/classes/blocks/class-b …
```
> PLANET-7295 Fix related articles block and block patterns report

- assets/src/blocks/Covers/CoversScript.js
We forgot to add quotation marks 😬 resulting in the block not showing in the frontend and the following error message in the console:
```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '[data-render=planet4-blocks/covers]' is not a valid selector.
```
[Example live page](https://www.greenpeace.org/aotearoa/petition/open-letter-oil-exploration-petition/)
- [Broken version](https://www-dev.greenpeace.org/test-rhea/take-action/)
- [Fixed version](https://www-dev.greenpeace.org/test-pandora/take-action/)
> Fix CoversScript selector

- assets/src/blocks/Columns/ColumnsTasks.js
- assets/src/styles/blocks/Columns.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7310
> Update the secondary buttons on the P4 Columns block, Tasks style on mobile devices
> Instead of link format, show a transparent button style instead
<table><tr>
<td><img src="https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/assets/617346/1d656cdf-691b-42d9-8da2-7809047b3884"/></td>
<td><img src="https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/assets/617346/38954bbc-7498-48d8-b39a-2e39370db0b7"/></td>
</tr></table>
On small/medium width, the Action link of P4 Columns Tasks should appear as a button instead of a link.
Cf. [test page on test instance](https://www-dev.greenpeace.org/test-pluto/1246-2/)
> PLANET-7310: Update secondary button of Columns block

- assets/src/ImageBlockExtension.js
- assets/src/blocks/Accordion/AccordionEditor.js
- assets/src/blocks/Happypoint/HappypointEditor.js
- assets/src/blocks/Media/MediaEditor.js
- assets/src/blocks/SplitTwoColumns/SplitTwoColumnsInPlaceEdit.js
- assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
- assets/src/blocks/Timeline/TimelineEditorScript.js
- assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
- assets/src/components/ColorPaletteControl/ColorPaletteControl.js
- assets/src/components/TermSelector/TermSelector.js
- package-lock.json
- package.json
Ref: https://jira.greenpeace.org/browse/PLANET-7323
> WordPress 6.4 removes Lodash dependency and provide alternative implementations of its functions.
We are currently using Lodash for duplication of WP components and some utilities but not importing it ourselves, so the Editor crashes in 6.4.
This is a port of Gutenberg removal of Lodash ([remove _.get](https://github.com/WordPress/gutenberg/pull/52561), [remove _.debounce](https://github.com/WordPress/gutenberg/pull/43943), etc.)
- E2E tests should pass
- Our port of the FlatTermSelector should still work as expected (Post Types selection in post edition)
> PLANET-7323: Remove Lodash dependencies

- classes/blocks/class-carouselheader.php
- classes/blocks/class-gallery.php
Ref: https://jira.greenpeace.org/browse/PLANET-7326
> When a Carousel Header is used in a Reusable block, the dependency library Hammer is not loaded. It is because we use the `has_block()` native function that can't read into reusable blocks.
Same issue for Gallery block.
Cf. [demo page on test instance](https://www-dev.greenpeace.org/test-neptune/reusable-block-test-page/)
- create a reusable block with a Carousel Header in it
- use this reusable block in a page
- frontend should show the Carousel and not crash with a console message `Hammer is not defined`
> PLANET-7326: Detect Carousel header in reusable block

- tests/e2e/blocks-report-api.spec.js
Ref: https://jira.greenpeace.org/browse/PLANET-7318
> Write a Playwright test to ensure the blocks report API endpoint works. 
The test verifies
- HTTP code and header for response
- Response properties
- Content not empty
Run locally with 
```
npx playwright test --project="firefox" tests/e2e/blocks-report-api.spec.js
```
> PLANET-7318: E2E test for blocks report API endpoint

- classes/blocks/class-covers.php
Ref: https://jira.greenpeace.org/browse/PLANET-7330
---
The `menu_order` option was missing from the `orderby` parapmeters.
Since we also still look for Act children pages, sorting after merging the two arrays was also adjusted to use that option instead of publication date.
1. Add a Covers block with a Tag that has at least 3 Actions to show.
2. See the one that is shown first. Probably it's going to be the one with the most recent publication date.
3. Edit one of this Actions and in the Sidebar change the Order to `2` under "Post Attributes".
4. Refresh the frontend page with the Covers block. Now that Action should be the last one.
1. Uncheck the "New IA" feature flag under _Planet 4 > Navigation_ in order to see what page is designated as the "Act" page. If none, select one and save. …
> PLANET-7330 Take menu order option into account for ordering Covers block

- classes/controller/menu/class-blocks-usage-controller.php
- classes/search/block/sql/class-like.php
- classes/search/block/sql/class-sqlquery.php
- classes/search/class-patternsearch.php
- classes/search/pattern/class-patternusageapi.php
Ref: https://jira.greenpeace.org/browse/PLANET-7331
3 strategies to avoid timeouts during report request:
- Change `REGEX` queries to `LIKE`
- this gives 30 to 50% gain on query speed
- results are still filtered in PHP afterward, so it doesn't change the end result
- Query the namespaces of pattern templates instead of full names
- this effectively reduces the number of queries for templates from `n` templates to 1
- Cache result
- to avoid any query spam, results are cached 5 minutes 
This branch is deployed on [Belgium dev site](https://www-dev.greenpeace.org/belgium/wp-json/plugin_blocks/v3/plugin_blocks_report), prod site is currently timing out on this request.
Tested locally using Belgium database, and diffing api result on main branch and this branch - json object should be the …
> PLANET-7331: Optimize Block report queries

- classes/class-loader.php
Ref: https://jira.greenpeace.org/browse/PLANET-7336
Requires: https://github.com/greenpeace/planet4-master-theme/pull/2152
Category `planet4-blocks` was registered twice, once in this repo and another in planet4-master-theme.  
We remove this registration, and reorder the one in master-theme to appear on top of the list.
Both branches are deployed on [Pandora](https://www-dev.greenpeace.org/test-pandora/)
> PLANET-7336: planet4-blocks category is registered twice

- assets/src/blocks/CarouselHeader/SidebarSlide.js
See [PLANET-7297](https://jira.greenpeace.org/browse/PLANET-7297)
Before this fix, it would go wild in the editor if several slides were open at the same time via the sidebar.
In the editor, add a CarouselHeader with at least 2 slides. Then open said slides one after another using the sidebar tabs. On `main` branch the block will keep going back and forth between the 2 slides, whereas on this branch it will stay on the latest open one which is the expected behaviour.
> PLANET-7297 Fix Carousel Header editor slide change

- assets/src/blocks/ENForm/ENFormFrontend.js
- assets/src/blocks/ENForm/ENFormInPlaceEdit.js
- tests/e2e/covers-content.spec.js
- tests/e2e/tools/lib/covers.js
Update tests [failing](https://output.circle-artifacts.com/output/job/37c06ecc-62a1-492e-81fb-7209d893abb8/artifacts/0/home/circleci/artifacts/playwright/plugins/e2e-report/index.html) in WordPress 6.4.
- EN Form test failing because of a `useSelect` used in a frontend component passed in `renderToString`
- Covers content test failing because the style selector now shows the name `Content` instead of `Default`
> PLANET-7238: Update test for WP6.4

- assets/src/styles/blocks/Happypoint.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7334
A Happy Point containing an embed Hubspot form with Recaptcha doesn't always fit the entire form, the submit button is pushed down when Recaptcha appears after page loading; the wrapper div can't resize for that.
Passing its height to `auto` on mobile allows it to resize according to the change of the content.
> PLANET-7334: Fix HappyPoint height on mobile with Recaptcha

- assets/src/BlockEditorValidation.js
Ref: https://jira.greenpeace.org/browse/PLANET-7340
Requires: https://github.com/greenpeace/planet4-master-theme/pull/2158
> Do a pre-publish check so that Post title is not empty
> Enforce the rule for publishing or updating a Post
> This should be applied in all post types
On test instance [Pluto](https://www-dev.greenpeace.org/test-pluto/), try to:
- Publish a post/page with and without a title
- Quick edit a post/page with and without a title
> PLANET-7340: Make Post title mandatory for publishing

- assets/src/components/Parallax/setupParallax.js
See [PLANET-7286](https://jira.greenpeace.org/browse/PLANET-7286)
It looked broken when applied to blocks situated lower on the page. This solution is not perfect, but I think that it already looks much better and it's a quick fix!
Make sure to test in different screen sizes. As you scroll down the page, the parallax effect should now look better than before:
- [Fixed version](https://www-dev.greenpeace.org/test-rhea/parallax-tests-2/)
- [Broken version](https://www-dev.greenpeace.org/test-saturn/parallax-tests-broken-version/)
> PLANET-7286 Fix Media & Text parallax effect

- assets/src/styles/blocks/PageHeader.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7314
Demo page: https://www-dev.greenpeace.org/test-rhea/page-header-demo-page/
Remove the `min-width` property since seems not be not necessary in this case.
> PLANET-7314: Fix Page Header on small screens

- classes/blocks/class-carouselheader.php
Ref: https://jira.greenpeace.org/browse/PLANET-7301
Move the CarouselHeader block to master-theme
Related to https://github.com/greenpeace/planet4-master-theme/pull/2171
> PLANET-7301: Ensure to not re-instantiate the Carousel Header block from plugin

- classes/blocks/class-accordion.php
Ref: [PLANET-7300](https://jira.greenpeace.org/browse/PLANET-7300)
Move the Accordion block to master-theme
Related to [#2173](https://github.com/greenpeace/planet4-master-theme/pull/2173)
> PLANET-7300: Ensure to not re-instantiate the Accrordion class block from plugin

- assets/src/blocks/Cookies/CookiesFieldResetButton.js
- assets/src/styles/blocks/Cookies/CookiesEditor.scss
- classes/blocks/class-cookies.php
See [PLANET-7302](https://jira.greenpeace.org/browse/PLANET-7302)
This PR also includes small style fixes for the `CookiesFieldResetButton` component, following this [mockup](https://www.figma.com/file/9NtbY8n3at8uOEJTsLrETb/P4-Design-System?type=design&node-id=4843%3A11035&mode=design&t=9qnx7PZ7YsEeosgJ-1). This was forgotten when working on the new identity.
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2167
> PLANET-7302 Make sure Cookies block isn't already registered

- classes/blocks/class-counter.php
Ref: [PLANET-7305](https://jira.greenpeace.org/browse/PLANET-7305)
Move the Counter block to master-theme
Related to [#2175](https://github.com/greenpeace/planet4-master-theme/pull/2176)
> PLANET-7305: Make sure to not instantiate the Counter class twice

- classes/blocks/class-takeactionboxout.php
Ref: [PLANET-7306](https://jira.greenpeace.org/browse/PLANET-7306)
Move the Take Action Boxout block into master-theme
Related to [#2175](https://github.com/greenpeace/planet4-master-theme/pull/2183)
> PLANET-7306: Make sure to not instantiate the Take Action Boxout class twice

- composer.json
- composer.lock
- tests/bootstrap.php
Update polyfills to match [WordPress 6.4](https://github.com/WordPress/wordpress-develop/commit/f0d53f8100d5bc274b126995e5f08a509a70d91c)
- update `yoast/phpunit-polyfills` to 1.1.0
- lock `doctrine/instantiator` to 1.5 for php7.4 compatibility
- add  `WP_DEBUG:false` to test to avoid deprecation messages
> Update phpunit polyfills

- assets/src/components/PostTypeSelector/PostTypeSelector.js
- assets/src/components/TagSelector/TagSelector.js
- assets/src/functions/useSelector.js
Ref: https://jira.greenpeace.org/browse/PLANET-6924
There are a bunch of improvements included on this PR.
You can validate by following the next steps:
1. Create a new page and insert an [Articles block ](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/28368631fa78eda6a4d15761f9b9251792828bbe/assets/src/blocks/Articles)
2. You can test it on filling with wrong tags or post types (that solves the issue reported)
Also..
- Since the [TagSelector](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/4fd6f3b6798e2106c33ae35908aba8b019441004/assets/src/components/TagSelector/TagSelector.js) and the [PostTypeSelector](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/4fd6f3b6798e2106c33ae35908aba8b019441004/assets/src/components/PostTypeSelector/ …
> PLANET-6924: Fix Tag and Post Type selector

- assets/src/blocks/Articles/ArticlesEditor.js
- assets/src/blocks/Articles/ArticlesFrontend.js
- assets/src/blocks/Articles/useArticlesFetch.js
- classes/blocks/class-articles.php
See [PLANET-7425](https://jira.greenpeace.org/browse/PLANET-7425)
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2212
Both in Pages and Posts, the `ignore_categories` attribute should now work as expected!
> PLANET-7425 Fix ignore_categories behaviour for the Articles block

- assets/src/styles/blocks/PageHeader.scss
**Description:** 
Removed extra padding on the top of Page Header layout to match [Figma](https://www.figma.com/file/9NtbY8n3at8uOEJTsLrETb/P4-Design-System?type=design&node-id=720-31759&mode=design&t=hestPSgmXBRcVBY8-0) designs. 
Also adjusted image height on smaller screens.
**Testing:**
Test instance [page](https://www-dev.greenpeace.org/test-iocaste/test-page-header/) with fix 
Control [Page](https://www-dev.greenpeace.org/africa/en/testing-page-header/)
> Fix Page Header padding values

- assets/src/styles/blocks/core-overrides/Image.scss
See [PLANET-7444](https://jira.greenpeace.org/browse/PLANET-7444)
This was only working in posts.
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2226
I've added the various Image alignments on the following:
- [Page](https://www-dev.greenpeace.org/test-pandora/page-with-images/)
- [Post](https://www-dev.greenpeace.org/test-pandora/story/1273/post-with-images/)
- [Action](https://www-dev.greenpeace.org/test-pandora/petitions/action-with-images/)
> PLANET-7444 Fix left/right aligned images in all post types

- assets/src/blocks/ENForm/ENFormFrontend.js
Provide default content_title_size if it's missing from the block attributes
Locally, import `africa` DB
- try to edit this page `/en/legacy-donation/`
- on `main` branch, editor crashes (page becomes empty)
- on this branch, page is editable
> Fix ENForm breaking page when missing title size

- assets/src/styles/blocks/PageHeader.scss
See [PLANET-7486](https://jira.greenpeace.org/browse/PLANET-7486)
I've asked Houssam to have a look to make sure that the behaviour is the one we want.
You can compare the fixed version with the broken one by adding `dir="rtl"` to the html element on the following pages:
- [broken](https://www-dev.greenpeace.org/test-rhea/page-headers/)
- [fixed](https://www-dev.greenpeace.org/test-oberon/page-headers/)
Please make sure to test all screen sizes. Of course the LTR version should still look good as well 🙂
> PLANET-7486 Fix Page Header block for RTL sites

- assets/src/styles/blocks/ENForm/ENFormEditorStyle.scss
- assets/src/styles/blocks/ENForm/components/_enform-full-width-bg.scss
- assets/src/styles/blocks/ENForm/components/_enform-full-width.scss
- assets/src/styles/blocks/ENForm/components/_enform.scss
The full width version of the block (without background image) should have a green background, see [Slack thread](https://greenpeace-gpi.slack.com/archives/G015K63081W/p1712740351855869)
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2252
On the jupiter instance you can deactivate the ["all blocks" feature](https://www-dev.greenpeace.org/test-jupiter/wp-admin/admin.php?page=planet4_settings_features), and then use [this page](https://www-dev.greenpeace.org/test-jupiter/just-an-enform/) to test the plugin version of the block.
> Fix ENForm background color

- classes/blocks/class-columns.php
See [PLANET-7442](https://jira.greenpeace.org/browse/PLANET-7442)
This is needed now that we are moving it to the theme
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2256
This PR can already be merged even if the master-theme one isn't ready yet.
> PLANET-7442 Make sure P4 Columns block isn't registered twice

- planet4-gutenberg-blocks.php
- templates/blocks/enform/enform_post.twig
See [Slack thread](https://greenpeace-gpi.slack.com/archives/C016H6ELXAL/p1713776950660969)
This is to avoid registering the same function twice
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2265
> Rename object_to_array function

- assets/src/BlockEditorValidation.js
Ref: https://jira.greenpeace.org/browse/PLANET-7565
<hr>
**DESCRIPTION:**
This PR replaces the `PluginPrePublishPanel` component of being imported from `wp.editPost` with `wp.editor` according to the changes introduced by WordPress 6.6
> PLANET-7565: Replaced deprecated imports in WordPress 6.6.x

- tests/e2e/tools/lib/editor.js
- tests/e2e/tools/lib/post.js
Ref: https://jira.greenpeace.org/browse/PLANET-7565
<hr>
**DESCRIPTION:**
This PR fixes the failing automated tests after upgrading WordPress to its LTS version ([6.6.1 of 23 July, 2024](https://wordpress.org/download/releases/)).
>  PLANET-7565: Fix tests broken by WordPress v6.6.x

- assets/src/functions/fetchJson.js
Ref: https://jira.greenpeace.org/browse/PLANET-7585
This PR fixes blocks not being supported in existing pages as described [here](https://jira.greenpeace.org/browse/PLANET-7585).
Similar to [this PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1222), the `regenerator-runtime` dependency has to be explicitly called due to changes implemented in WordPress 6.6
> PLANET 7585: Explicity import `regenerator-runtime` 

- assets/src/blocks/Columns/ColumnsBlock.js
- assets/src/blocks/Columns/ColumnsEditor.js
- assets/src/blocks/Happypoint/HappypointBlock.js
- assets/src/blocks/Happypoint/HappypointEditor.js
- assets/src/blocks/SocialMedia/SocialMediaBlock.js
- assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
- assets/src/blocks/Submenu/SubmenuBlock.js
- assets/src/blocks/Submenu/SubmenuEditor.js
- assets/src/blocks/Timeline/TimelineBlock.js
- assets/src/blocks/Timeline/TimelineEditorScript.js
Ref: https://jira.greenpeace.org/browse/PLANET-7220
<hr>
**DESCRIPTION:**
Based on [this mockup](https://www.figma.com/design/87AqKGnduB2Uq5fVkIcdcg/Handbook-Links-in-Backend?node-id=1-437&node-type=FRAME&t=bzJp6zu3cilsg1wU-0), this PR adds a description to some of the blocks in the P4 plugin and an additional collapsible panel body in the editor with a link to the P4 Handbook.
<hr>
**RELATED PR:**
https://github.com/greenpeace/planet4-master-theme/pull/2371
> PLANET-7220: Add definitions to blocks settings

- classes/class-loader.php
See [PLANET-7604](https://jira.greenpeace.org/browse/PLANET-7604)
These are now registered in the master theme, if we keep them here too they are duplicate in the backend.
On local or on the [nix test instance](https://www-dev.greenpeace.org/test-nix/), any Page/Post/Action should now show the Beta Blocks category only once in the editor.
> PLANET-7604 Remove block categories registration

- assets/src/styles/editorStyle.scss
These seem to not be needed anymore, and sometimes they even break our designs in the editor (see [PLANET-7584](https://jira.greenpeace.org/browse/PLANET-7584) and the [corresponding PR](https://github.com/greenpeace/planet4-master-theme/pull/2374))
Check out several Pages/Posts/Actions in the editor with the plugin activated, and make sure everything still looks fine.
I've asked Houssam to test this out as well, if he wants to keep the margins then the solution would be to move them to the master theme instead.
> PLANET-7584 Remove our custom editor layout margin values

- assets/src/BlockEditorValidation.js
See [PLANET-7560](https://jira.greenpeace.org/browse/PLANET-7560)
It should now be possible to publish patterns from `Blocks > All reusable blocks > Add new pattern`.
> PLANET-7560 Remove mandatory featured image check for patterns

- assets/src/components/Image/ImageBlockEdit.js
See [PLANET-7501](https://jira.greenpeace.org/browse/PLANET-7501)
This is to be consistent with the frontend.
You can check all use cases in the editor for [this page](https://www-dev.greenpeace.org/test-nix/image-tests/) for example.
> PLANET-7501 Show image credits in the editor even when no caption
